 ERROR root [0x00002e94] [2018-06-22 00:03:11,217] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00002e94] [2018-06-22 00:03:11,237] - The following logs sent to logger failed:
  WARN root [0x00002e94] [2018-06-22 00:03:11,237] - ==> [2018-06-22 00:03:11 214] TCPPacketReceiver::processPendingEvents(192.168.31.56:10100): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002e94] [2018-06-22 00:03:11,238] - ==> [2018-06-22 00:03:11 235] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00002e94] [2018-06-22 00:03:11,304] - TCPPacketReceiver::processPendingEvents(192.168.31.56:10103): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002e94] [2018-06-22 00:03:11,311] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00002e94] [2018-06-22 00:03:11,320] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00002e94] [2018-06-22 00:03:11,325] - Shutdowner::onShutdown: shutting down
  INFO root [0x00002e94] [2018-06-22 00:03:11,325] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00002e94] [2018-06-22 00:03:11,326] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x00002e94] [2018-06-22 00:03:11,326] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x00002e94] [2018-06-22 00:03:11,360] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002e94] [2018-06-22 00:03:11,360] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00002e94] [2018-06-22 00:03:11,360] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00002e94] [2018-06-22 00:03:11,361] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002e94] [2018-06-22 00:03:11,361] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00002e94] [2018-06-22 00:03:11,361] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002e94] [2018-06-22 00:03:11,361] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002e94] [2018-06-22 00:03:11,362] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00002e94] [2018-06-22 00:03:11,380] - Script::uninstall(): is successfully!
 DEBUG root [0x00002e94] [2018-06-22 00:03:11,380] - ThreadPool::destroy(): starting size 2.
  INFO root [0x000016e4] [2018-06-22 08:40:33,429] - 
  INFO root [0x000016e4] [2018-06-22 08:40:33,463] - -----------------------------------------------------------------------------------------


  INFO root [0x000016e4] [2018-06-22 08:40:33,465] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [0x000016e4] [2018-06-22 08:40:33,465] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [0x000016e4] [2018-06-22 08:40:33,465] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [0x000016e4] [2018-06-22 08:40:33,473] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:2547 )
  INFO root [0x000016e4] [2018-06-22 08:40:33,473] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:2547, SOMAXCONN=5.
  INFO root [0x000016e4] [2018-06-22 08:40:33,474] - server-configs:
  INFO root [0x000016e4] [2018-06-22 08:40:33,474] - 	gameUpdateHertz : 10
  INFO root [0x000016e4] [2018-06-22 08:40:33,474] - 	defaultAoIRadius : 80
  INFO root [0x000016e4] [2018-06-22 08:40:33,474] - 	defaultAoIHysteresisArea : 5
  INFO root [0x000016e4] [2018-06-22 08:40:33,474] - 	entryScriptFile : kbemain
  INFO root [0x000016e4] [2018-06-22 08:40:33,474] - 	internalAddr : 192.168.31.56:2547
  INFO root [0x000016e4] [2018-06-22 08:40:33,475] - 	componentID : 8001
  INFO root [0x000016e4] [2018-06-22 08:40:34,982] - ---- cellapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: D25B4E16028C33EB467B7BE2F3500426. Config: Debug X86. Built: 23:20:13 Jun 15 2018. AppID: 8001. UID: 404. PID: 6384 ----
  INFO root [0x000016e4] [2018-06-22 08:40:34,983] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [0x000016e4] [2018-06-22 08:40:34,984] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000016e4] [2018-06-22 08:40:34,985] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000016e4] [2018-06-22 08:40:35,151] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000016e4] [2018-06-22 08:40:35,152] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000016e4] [2018-06-22 08:40:35,153] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000016e4] [2018-06-22 08:40:35,160] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000016e4] [2018-06-22 08:40:35,161] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000016e4] [2018-06-22 08:40:35,161] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000016e4] [2018-06-22 08:40:35,162] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000016e4] [2018-06-22 08:40:35,231] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000016e4] [2018-06-22 08:40:35,307] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:17:57) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x000016e4] [2018-06-22 08:40:35,307] - Script::install(): KBExtra is successfully!
  INFO root [0x000016e4] [2018-06-22 08:40:35,350] - TelnetServer server is running on port 50000
  INFO root [0x000016e4] [2018-06-22 08:40:36,705] - ---- cellapp is running ----
 DEBUG root [0x000016e4] [2018-06-22 08:40:36,706] - Components::process(): Request for the process of identity...
  WARN root [0x000016e4] [2018-06-22 08:40:43,039] - EntityApp::checkTickPeriod: tick took 6334% (6.33 seconds)!
  INFO root [0x000016e4] [2018-06-22 08:40:44,066] - Components::findComponents: find logger(1)...
  INFO root [0x000016e4] [2018-06-22 08:40:44,164] - Components::findComponents: found logger, addr:192.168.31.56:2552
  INFO root [0x000016e4] [2018-06-22 08:40:44,165] - Components::addComponent: reset orderLog, uid=404!
  INFO root [0x000016e4] [2018-06-22 08:40:44,165] - Components::addComponent[logger], uid=404, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000016e4] [2018-06-22 08:40:44,167] - Components::findComponents: find dbmgr(2)...
  INFO root [0x000016e4] [2018-06-22 08:40:44,273] - Components::findComponents: found dbmgr, addr:192.168.31.56:2553
  INFO root [0x000016e4] [2018-06-22 08:40:44,274] - Components::addComponent: reset orderLog, uid=404!
  INFO root [0x000016e4] [2018-06-22 08:40:44,274] - Components::addComponent[dbmgr], uid=404, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000016e4] [2018-06-22 08:40:44,274] - Components::findComponents: found dbmgr, addr:192.168.31.56:2553
  WARN root [0x000016e4] [2018-06-22 08:40:45,274] - Forwarding logs to logger[192.168.31.56:2552/0/0/0]...
 ERROR root [0x000016e4] [2018-06-22 08:54:03,566] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x000016e4] [2018-06-22 08:54:03,574] - The following logs sent to logger failed:
  WARN root [0x000016e4] [2018-06-22 08:54:03,575] - ==> [2018-06-22 08:54:03 562] TCPPacketReceiver::processPendingEvents(192.168.31.56:2552): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000016e4] [2018-06-22 08:54:03,575] - ==> [2018-06-22 08:54:03 567] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x000016e4] [2018-06-22 08:54:03,664] - TCPPacketReceiver::processPendingEvents(192.168.31.56:2553): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000016e4] [2018-06-22 08:54:03,667] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x000016e4] [2018-06-22 08:54:03,677] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x000016e4] [2018-06-22 08:54:03,682] - Shutdowner::onShutdown: shutting down
  INFO root [0x000016e4] [2018-06-22 08:54:03,682] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x000016e4] [2018-06-22 08:54:03,682] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x000016e4] [2018-06-22 08:54:03,683] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x000016e4] [2018-06-22 08:54:03,723] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000016e4] [2018-06-22 08:54:03,723] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x000016e4] [2018-06-22 08:54:03,724] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x000016e4] [2018-06-22 08:54:03,724] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x000016e4] [2018-06-22 08:54:03,724] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x000016e4] [2018-06-22 08:54:03,725] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x000016e4] [2018-06-22 08:54:03,725] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x000016e4] [2018-06-22 08:54:03,725] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x000016e4] [2018-06-22 08:54:03,741] - Script::uninstall(): is successfully!
 DEBUG root [0x000016e4] [2018-06-22 08:54:03,741] - ThreadPool::destroy(): starting size 2.
  WARN root [0x000016e4] [2018-06-22 08:54:04,041] - ThreadPool::destroy(): waiting for thread(2)[0x1be2220,0x1be21b8,], try=1
  INFO root [0x00001fe0] [2018-06-22 08:54:12,274] - 
  INFO root [0x00001fe0] [2018-06-22 08:54:12,276] - -----------------------------------------------------------------------------------------


  INFO root [0x00001fe0] [2018-06-22 08:54:12,279] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [0x00001fe0] [2018-06-22 08:54:12,280] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [0x00001fe0] [2018-06-22 08:54:12,281] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [0x00001fe0] [2018-06-22 08:54:12,297] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:2853 )
  INFO root [0x00001fe0] [2018-06-22 08:54:12,298] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:2853, SOMAXCONN=5.
  INFO root [0x00001fe0] [2018-06-22 08:54:12,298] - server-configs:
  INFO root [0x00001fe0] [2018-06-22 08:54:12,298] - 	gameUpdateHertz : 10
  INFO root [0x00001fe0] [2018-06-22 08:54:12,299] - 	defaultAoIRadius : 80
  INFO root [0x00001fe0] [2018-06-22 08:54:12,299] - 	defaultAoIHysteresisArea : 5
  INFO root [0x00001fe0] [2018-06-22 08:54:12,299] - 	entryScriptFile : kbemain
  INFO root [0x00001fe0] [2018-06-22 08:54:12,299] - 	internalAddr : 192.168.31.56:2853
  INFO root [0x00001fe0] [2018-06-22 08:54:12,300] - 	componentID : 8001
  INFO root [0x00001fe0] [2018-06-22 08:54:13,827] - ---- cellapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: D25B4E16028C33EB467B7BE2F3500426. Config: Debug X86. Built: 23:20:13 Jun 15 2018. AppID: 8001. UID: 3079. PID: 8040 ----
  INFO root [0x00001fe0] [2018-06-22 08:54:13,828] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [0x00001fe0] [2018-06-22 08:54:13,829] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001fe0] [2018-06-22 08:54:13,833] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00001fe0] [2018-06-22 08:54:14,074] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001fe0] [2018-06-22 08:54:14,076] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00001fe0] [2018-06-22 08:54:14,078] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00001fe0] [2018-06-22 08:54:14,086] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001fe0] [2018-06-22 08:54:14,087] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00001fe0] [2018-06-22 08:54:14,087] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001fe0] [2018-06-22 08:54:14,089] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001fe0] [2018-06-22 08:54:14,202] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00001fe0] [2018-06-22 08:54:14,308] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:17:57) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00001fe0] [2018-06-22 08:54:14,309] - Script::install(): KBExtra is successfully!
  INFO root [0x00001fe0] [2018-06-22 08:54:14,339] - TelnetServer server is running on port 50000
  INFO root [0x00001fe0] [2018-06-22 08:54:16,050] - ---- cellapp is running ----
 DEBUG root [0x00001fe0] [2018-06-22 08:54:16,052] - Components::process(): Request for the process of identity...
  WARN root [0x00001fe0] [2018-06-22 08:54:22,414] - EntityApp::checkTickPeriod: tick took 6363% (6.36 seconds)!
  INFO root [0x00001fe0] [2018-06-22 08:54:23,451] - Components::findComponents: find logger(1)...
  INFO root [0x00001fe0] [2018-06-22 08:54:23,536] - Components::findComponents: found logger, addr:192.168.31.56:2860
  INFO root [0x00001fe0] [2018-06-22 08:54:23,536] - Components::addComponent: reset orderLog, uid=3079!
  INFO root [0x00001fe0] [2018-06-22 08:54:23,536] - Components::addComponent[logger], uid=3079, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001fe0] [2018-06-22 08:54:23,540] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00001fe0] [2018-06-22 08:54:23,641] - Components::findComponents: found dbmgr, addr:192.168.31.56:2854
  INFO root [0x00001fe0] [2018-06-22 08:54:23,641] - Components::addComponent: reset orderLog, uid=3079!
  INFO root [0x00001fe0] [2018-06-22 08:54:23,642] - Components::addComponent[dbmgr], uid=3079, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001fe0] [2018-06-22 08:54:23,642] - Components::findComponents: found dbmgr, addr:192.168.31.56:2854
  WARN root [0x00001fe0] [2018-06-22 08:54:24,642] - EntityApp::checkTickPeriod: tick took 1291% (1.29 seconds)!
  WARN root [0x00001fe0] [2018-06-22 08:54:24,643] - Forwarding logs to logger[192.168.31.56:2860/0/0/0]...
 ERROR root [0x00001fe0] [2018-06-22 09:08:32,075] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00001fe0] [2018-06-22 09:08:32,077] - The following logs sent to logger failed:
  WARN root [0x00001fe0] [2018-06-22 09:08:32,078] - ==> [2018-06-22 09:08:32 073] TCPPacketReceiver::processPendingEvents(192.168.31.56:2860): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001fe0] [2018-06-22 09:08:32,079] - ==> [2018-06-22 09:08:32 076] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00001fe0] [2018-06-22 09:08:32,182] - TCPPacketReceiver::processPendingEvents(192.168.31.56:2854): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001fe0] [2018-06-22 09:08:32,183] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00001fe0] [2018-06-22 09:08:32,190] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00001fe0] [2018-06-22 09:08:32,194] - Shutdowner::onShutdown: shutting down
  INFO root [0x00001fe0] [2018-06-22 09:08:32,194] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00001fe0] [2018-06-22 09:08:32,195] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x00001fe0] [2018-06-22 09:08:32,196] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x00001fe0] [2018-06-22 09:08:32,229] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001fe0] [2018-06-22 09:08:32,229] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00001fe0] [2018-06-22 09:08:32,230] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00001fe0] [2018-06-22 09:08:32,230] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001fe0] [2018-06-22 09:08:32,230] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00001fe0] [2018-06-22 09:08:32,231] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001fe0] [2018-06-22 09:08:32,231] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001fe0] [2018-06-22 09:08:32,231] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00001fe0] [2018-06-22 09:08:32,252] - Script::uninstall(): is successfully!
 DEBUG root [0x00001fe0] [2018-06-22 09:08:32,253] - ThreadPool::destroy(): starting size 2.
  WARN root [0x00001fe0] [2018-06-22 09:08:32,553] - ThreadPool::destroy(): waiting for thread(2)[0x1b2200,0x1b2198,], try=1
  INFO root [0x0000274c] [2018-06-22 09:08:40,974] - 
  INFO root [0x0000274c] [2018-06-22 09:08:40,975] - -----------------------------------------------------------------------------------------


  INFO root [0x0000274c] [2018-06-22 09:08:40,976] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [0x0000274c] [2018-06-22 09:08:40,977] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [0x0000274c] [2018-06-22 09:08:40,978] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [0x0000274c] [2018-06-22 09:08:40,996] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:3110 )
  INFO root [0x0000274c] [2018-06-22 09:08:40,997] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:3110, SOMAXCONN=5.
  INFO root [0x0000274c] [2018-06-22 09:08:40,997] - server-configs:
  INFO root [0x0000274c] [2018-06-22 09:08:40,998] - 	gameUpdateHertz : 10
  INFO root [0x0000274c] [2018-06-22 09:08:40,998] - 	defaultAoIRadius : 80
  INFO root [0x0000274c] [2018-06-22 09:08:40,998] - 	defaultAoIHysteresisArea : 5
  INFO root [0x0000274c] [2018-06-22 09:08:40,998] - 	entryScriptFile : kbemain
  INFO root [0x0000274c] [2018-06-22 09:08:40,999] - 	internalAddr : 192.168.31.56:3110
  INFO root [0x0000274c] [2018-06-22 09:08:40,999] - 	componentID : 8001
  INFO root [0x0000274c] [2018-06-22 09:08:42,516] - ---- cellapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: D25B4E16028C33EB467B7BE2F3500426. Config: Debug X86. Built: 23:20:13 Jun 15 2018. AppID: 8001. UID: 5913. PID: 7660 ----
  INFO root [0x0000274c] [2018-06-22 09:08:42,517] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [0x0000274c] [2018-06-22 09:08:42,518] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x0000274c] [2018-06-22 09:08:42,518] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x0000274c] [2018-06-22 09:08:42,700] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000274c] [2018-06-22 09:08:42,701] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x0000274c] [2018-06-22 09:08:42,702] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x0000274c] [2018-06-22 09:08:42,710] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000274c] [2018-06-22 09:08:42,711] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x0000274c] [2018-06-22 09:08:42,711] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000274c] [2018-06-22 09:08:42,713] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000274c] [2018-06-22 09:08:42,808] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x0000274c] [2018-06-22 09:08:42,904] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:17:57) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x0000274c] [2018-06-22 09:08:42,905] - Script::install(): KBExtra is successfully!
  INFO root [0x0000274c] [2018-06-22 09:08:42,934] - TelnetServer server is running on port 50000
  INFO root [0x0000274c] [2018-06-22 09:08:44,449] - ---- cellapp is running ----
 DEBUG root [0x0000274c] [2018-06-22 09:08:44,450] - Components::process(): Request for the process of identity...
  WARN root [0x0000274c] [2018-06-22 09:08:50,566] - EntityApp::checkTickPeriod: tick took 6116% (6.12 seconds)!
  INFO root [0x0000274c] [2018-06-22 09:08:51,580] - Components::findComponents: find logger(1)...
  INFO root [0x0000274c] [2018-06-22 09:08:51,605] - Components::findComponents: found logger, addr:192.168.31.56:3104
  INFO root [0x0000274c] [2018-06-22 09:08:51,605] - Components::addComponent: reset orderLog, uid=5913!
  INFO root [0x0000274c] [2018-06-22 09:08:51,605] - Components::addComponent[logger], uid=5913, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x0000274c] [2018-06-22 09:08:51,607] - Components::findComponents: find dbmgr(2)...
  INFO root [0x0000274c] [2018-06-22 09:08:51,709] - Components::findComponents: found dbmgr, addr:192.168.31.56:3105
  INFO root [0x0000274c] [2018-06-22 09:08:51,709] - Components::addComponent: reset orderLog, uid=5913!
  INFO root [0x0000274c] [2018-06-22 09:08:51,709] - Components::addComponent[dbmgr], uid=5913, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x0000274c] [2018-06-22 09:08:51,710] - Components::findComponents: found dbmgr, addr:192.168.31.56:3105
  WARN root [0x0000274c] [2018-06-22 09:08:52,710] - Forwarding logs to logger[192.168.31.56:3104/0/0/0]...
 ERROR root [0x0000274c] [2018-06-22 09:12:23,737] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x0000274c] [2018-06-22 09:12:23,755] - The following logs sent to logger failed:
  WARN root [0x0000274c] [2018-06-22 09:12:23,755] - ==> [2018-06-22 09:12:23 734] TCPPacketReceiver::processPendingEvents(192.168.31.56:3104): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000274c] [2018-06-22 09:12:23,756] - ==> [2018-06-22 09:12:23 738] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x0000274c] [2018-06-22 09:12:23,847] - TCPPacketReceiver::processPendingEvents(192.168.31.56:3105): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000274c] [2018-06-22 09:12:23,849] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x0000274c] [2018-06-22 09:12:23,857] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x0000274c] [2018-06-22 09:12:23,859] - Shutdowner::onShutdown: shutting down
  INFO root [0x0000274c] [2018-06-22 09:12:23,860] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x0000274c] [2018-06-22 09:12:23,861] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x0000274c] [2018-06-22 09:12:23,861] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x0000274c] [2018-06-22 09:12:23,895] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000274c] [2018-06-22 09:12:23,895] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x0000274c] [2018-06-22 09:12:23,895] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x0000274c] [2018-06-22 09:12:23,896] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000274c] [2018-06-22 09:12:23,896] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x0000274c] [2018-06-22 09:12:23,897] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000274c] [2018-06-22 09:12:23,897] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000274c] [2018-06-22 09:12:23,897] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x0000274c] [2018-06-22 09:12:23,917] - Script::uninstall(): is successfully!
 DEBUG root [0x0000274c] [2018-06-22 09:12:23,918] - ThreadPool::destroy(): starting size 2.
  WARN root [0x0000274c] [2018-06-22 09:12:24,218] - ThreadPool::destroy(): waiting for thread(2)[0x622200,0x622198,], try=1
  INFO root [0x0000111c] [2018-06-22 09:12:33,091] - 
  INFO root [0x0000111c] [2018-06-22 09:12:33,092] - -----------------------------------------------------------------------------------------


  INFO root [0x0000111c] [2018-06-22 09:12:33,094] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [0x0000111c] [2018-06-22 09:12:33,095] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [0x0000111c] [2018-06-22 09:12:33,095] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [0x0000111c] [2018-06-22 09:12:33,119] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:3215 )
  INFO root [0x0000111c] [2018-06-22 09:12:33,119] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:3215, SOMAXCONN=5.
  INFO root [0x0000111c] [2018-06-22 09:12:33,120] - server-configs:
  INFO root [0x0000111c] [2018-06-22 09:12:33,120] - 	gameUpdateHertz : 10
  INFO root [0x0000111c] [2018-06-22 09:12:33,120] - 	defaultAoIRadius : 80
  INFO root [0x0000111c] [2018-06-22 09:12:33,120] - 	defaultAoIHysteresisArea : 5
  INFO root [0x0000111c] [2018-06-22 09:12:33,121] - 	entryScriptFile : kbemain
  INFO root [0x0000111c] [2018-06-22 09:12:33,121] - 	internalAddr : 192.168.31.56:3215
  INFO root [0x0000111c] [2018-06-22 09:12:33,121] - 	componentID : 8001
  INFO root [0x0000111c] [2018-06-22 09:12:34,646] - ---- cellapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: D25B4E16028C33EB467B7BE2F3500426. Config: Debug X86. Built: 23:20:13 Jun 15 2018. AppID: 8001. UID: 6674. PID: 4744 ----
  INFO root [0x0000111c] [2018-06-22 09:12:34,648] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [0x0000111c] [2018-06-22 09:12:34,648] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x0000111c] [2018-06-22 09:12:34,653] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x0000111c] [2018-06-22 09:12:34,913] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000111c] [2018-06-22 09:12:34,914] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x0000111c] [2018-06-22 09:12:34,915] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x0000111c] [2018-06-22 09:12:34,923] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000111c] [2018-06-22 09:12:34,924] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x0000111c] [2018-06-22 09:12:34,924] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000111c] [2018-06-22 09:12:34,926] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000111c] [2018-06-22 09:12:35,096] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x0000111c] [2018-06-22 09:12:35,247] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:17:57) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x0000111c] [2018-06-22 09:12:35,248] - Script::install(): KBExtra is successfully!
  INFO root [0x0000111c] [2018-06-22 09:12:35,278] - TelnetServer server is running on port 50000
  INFO root [0x0000111c] [2018-06-22 09:12:36,512] - ---- cellapp is running ----
 DEBUG root [0x0000111c] [2018-06-22 09:12:36,512] - Components::process(): Request for the process of identity...
  WARN root [0x0000111c] [2018-06-22 09:12:42,622] - EntityApp::checkTickPeriod: tick took 6110% (6.11 seconds)!
  INFO root [0x0000111c] [2018-06-22 09:12:43,697] - Components::findComponents: find logger(1)...
  INFO root [0x0000111c] [2018-06-22 09:12:43,707] - Components::findComponents: found logger, addr:192.168.31.56:3213
  INFO root [0x0000111c] [2018-06-22 09:12:43,707] - Components::addComponent: reset orderLog, uid=6674!
  INFO root [0x0000111c] [2018-06-22 09:12:43,707] - Components::addComponent[logger], uid=6674, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x0000111c] [2018-06-22 09:12:43,709] - Components::findComponents: find dbmgr(2)...
  INFO root [0x0000111c] [2018-06-22 09:12:43,808] - Components::findComponents: found dbmgr, addr:192.168.31.56:3211
  INFO root [0x0000111c] [2018-06-22 09:12:43,808] - Components::addComponent: reset orderLog, uid=6674!
  INFO root [0x0000111c] [2018-06-22 09:12:43,809] - Components::addComponent[dbmgr], uid=6674, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x0000111c] [2018-06-22 09:12:43,809] - Components::findComponents: found dbmgr, addr:192.168.31.56:3211
  WARN root [0x0000111c] [2018-06-22 09:12:44,809] - Forwarding logs to logger[192.168.31.56:3213/0/0/0]...
 ERROR root [0x0000111c] [2018-06-22 09:18:31,046] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x0000111c] [2018-06-22 09:18:31,073] - The following logs sent to logger failed:
  WARN root [0x0000111c] [2018-06-22 09:18:31,073] - ==> [2018-06-22 09:18:31 044] TCPPacketReceiver::processPendingEvents(192.168.31.56:3213): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000111c] [2018-06-22 09:18:31,074] - ==> [2018-06-22 09:18:31 046] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x0000111c] [2018-06-22 09:18:31,198] - TCPPacketReceiver::processPendingEvents(192.168.31.56:3211): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000111c] [2018-06-22 09:18:31,201] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x0000111c] [2018-06-22 09:18:31,208] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x0000111c] [2018-06-22 09:18:31,210] - Shutdowner::onShutdown: shutting down
  INFO root [0x0000111c] [2018-06-22 09:18:31,210] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x0000111c] [2018-06-22 09:18:31,211] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x0000111c] [2018-06-22 09:18:31,211] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x0000111c] [2018-06-22 09:18:31,247] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000111c] [2018-06-22 09:18:31,248] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x0000111c] [2018-06-22 09:18:31,248] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x0000111c] [2018-06-22 09:18:31,248] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000111c] [2018-06-22 09:18:31,249] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x0000111c] [2018-06-22 09:18:31,249] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000111c] [2018-06-22 09:18:31,250] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000111c] [2018-06-22 09:18:31,250] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x0000111c] [2018-06-22 09:18:31,271] - Script::uninstall(): is successfully!
 DEBUG root [0x0000111c] [2018-06-22 09:18:31,271] - ThreadPool::destroy(): starting size 2.
  WARN root [0x0000111c] [2018-06-22 09:18:31,572] - ThreadPool::destroy(): waiting for thread(2)[0x4c2200,0x4c2198,], try=1
  INFO root [0x000019e0] [2018-06-22 09:18:37,948] - 
  INFO root [0x000019e0] [2018-06-22 09:18:37,956] - -----------------------------------------------------------------------------------------


  INFO root [0x000019e0] [2018-06-22 09:18:37,958] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [0x000019e0] [2018-06-22 09:18:37,959] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [0x000019e0] [2018-06-22 09:18:37,959] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [0x000019e0] [2018-06-22 09:18:37,976] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:3369 )
  INFO root [0x000019e0] [2018-06-22 09:18:37,977] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:3369, SOMAXCONN=5.
  INFO root [0x000019e0] [2018-06-22 09:18:37,977] - server-configs:
  INFO root [0x000019e0] [2018-06-22 09:18:37,977] - 	gameUpdateHertz : 10
  INFO root [0x000019e0] [2018-06-22 09:18:37,977] - 	defaultAoIRadius : 80
  INFO root [0x000019e0] [2018-06-22 09:18:37,978] - 	defaultAoIHysteresisArea : 5
  INFO root [0x000019e0] [2018-06-22 09:18:37,978] - 	entryScriptFile : kbemain
  INFO root [0x000019e0] [2018-06-22 09:18:37,978] - 	internalAddr : 192.168.31.56:3369
  INFO root [0x000019e0] [2018-06-22 09:18:37,979] - 	componentID : 8001
  INFO root [0x000019e0] [2018-06-22 09:18:39,496] - ---- cellapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: D25B4E16028C33EB467B7BE2F3500426. Config: Debug X86. Built: 23:20:13 Jun 15 2018. AppID: 8001. UID: 7863. PID: 5224 ----
  INFO root [0x000019e0] [2018-06-22 09:18:39,498] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [0x000019e0] [2018-06-22 09:18:39,499] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000019e0] [2018-06-22 09:18:39,499] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000019e0] [2018-06-22 09:18:39,664] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000019e0] [2018-06-22 09:18:39,664] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000019e0] [2018-06-22 09:18:39,665] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000019e0] [2018-06-22 09:18:39,670] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000019e0] [2018-06-22 09:18:39,671] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000019e0] [2018-06-22 09:18:39,671] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000019e0] [2018-06-22 09:18:39,672] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000019e0] [2018-06-22 09:18:39,734] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000019e0] [2018-06-22 09:18:39,805] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:17:57) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x000019e0] [2018-06-22 09:18:39,805] - Script::install(): KBExtra is successfully!
  INFO root [0x000019e0] [2018-06-22 09:18:39,828] - TelnetServer server is running on port 50000
  INFO root [0x000019e0] [2018-06-22 09:18:41,224] - ---- cellapp is running ----
 DEBUG root [0x000019e0] [2018-06-22 09:18:41,225] - Components::process(): Request for the process of identity...
  WARN root [0x000019e0] [2018-06-22 09:18:47,345] - EntityApp::checkTickPeriod: tick took 6120% (6.12 seconds)!
  INFO root [0x000019e0] [2018-06-22 09:18:48,364] - Components::findComponents: find logger(1)...
  INFO root [0x000019e0] [2018-06-22 09:18:48,455] - Components::findComponents: found logger, addr:192.168.31.56:3368
  INFO root [0x000019e0] [2018-06-22 09:18:48,456] - Components::addComponent: reset orderLog, uid=7863!
  INFO root [0x000019e0] [2018-06-22 09:18:48,456] - Components::addComponent[logger], uid=7863, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000019e0] [2018-06-22 09:18:48,459] - Components::findComponents: find dbmgr(2)...
  INFO root [0x000019e0] [2018-06-22 09:18:48,558] - Components::findComponents: found dbmgr, addr:192.168.31.56:3375
  INFO root [0x000019e0] [2018-06-22 09:18:48,558] - Components::addComponent: reset orderLog, uid=7863!
  INFO root [0x000019e0] [2018-06-22 09:18:48,560] - Components::addComponent[dbmgr], uid=7863, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000019e0] [2018-06-22 09:18:48,560] - Components::findComponents: found dbmgr, addr:192.168.31.56:3375
  WARN root [0x000019e0] [2018-06-22 09:18:49,560] - Forwarding logs to logger[192.168.31.56:3368/0/0/0]...
 ERROR root [0x000019e0] [2018-06-22 22:51:36,766] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x000019e0] [2018-06-22 22:51:36,918] - The following logs sent to logger failed:
  WARN root [0x000019e0] [2018-06-22 22:51:37,038] - ==> [2018-06-22 22:51:36 679] TCPPacketReceiver::processPendingEvents(192.168.31.56:3368): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000019e0] [2018-06-22 22:51:37,039] - ==> [2018-06-22 22:51:36 767] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x000019e0] [2018-06-22 22:51:37,054] - EntityApp::checkTickPeriod: tick took 474% (0.47 seconds)!
 ERROR root [0x000019e0] [2018-06-22 22:51:37,086] - 192.168.31.56:3371: TCPPacketSender::processSend(): Exception occurred: REASON_CLIENT_DISCONNECTED , errno: 10054
 ERROR root [0x000019e0] [2018-06-22 22:51:37,087] - Components::removeComponentByChannel: cellappmgr : 6000, Abnormal exit! errorno=10054
  INFO root [0x000019e0] [2018-06-22 22:51:37,147] - Shutdowner::onShutdownBegin: shutting down(period=1, tickPeriod=1)
  WARN root [0x000019e0] [2018-06-22 22:51:37,148] - TCPPacketReceiver::processPendingEvents(192.168.31.56:3375): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
  INFO root [0x000019e0] [2018-06-22 22:51:37,149] - Components::removeComponentByChannel: dbmgr : 4000, Normal exit!
  WARN root [0x000019e0] [2018-06-22 22:51:37,149] - ServerApp::shutDown:  In shuttingdown!
  WARN root [0x000019e0] [2018-06-22 22:51:37,150] - TCPPacketReceiver::processPendingEvents(192.168.31.56:3370): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
  INFO root [0x000019e0] [2018-06-22 22:51:37,150] - Components::removeComponentByChannel: baseappmgr : 5000, Normal exit!
  WARN root [0x000019e0] [2018-06-22 22:51:37,151] - TCPPacketReceiver::processPendingEvents(192.168.31.56:3372): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
  INFO root [0x000019e0] [2018-06-22 22:51:37,151] - Components::removeComponentByChannel: baseapp : 7001, Normal exit!
  INFO root [0x00002418] [2018-06-22 22:51:43,649] - 
  INFO root [0x00002418] [2018-06-22 22:51:43,650] - -----------------------------------------------------------------------------------------


  INFO root [0x00002418] [2018-06-22 22:51:43,717] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [0x00002418] [2018-06-22 22:51:43,717] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [0x00002418] [2018-06-22 22:51:43,718] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [0x00002418] [2018-06-22 22:51:43,726] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:11013 )
  INFO root [0x00002418] [2018-06-22 22:51:43,726] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:11013, SOMAXCONN=5.
  INFO root [0x00002418] [2018-06-22 22:51:43,727] - server-configs:
  INFO root [0x00002418] [2018-06-22 22:51:43,727] - 	gameUpdateHertz : 10
  INFO root [0x00002418] [2018-06-22 22:51:43,727] - 	defaultAoIRadius : 80
  INFO root [0x00002418] [2018-06-22 22:51:43,728] - 	defaultAoIHysteresisArea : 5
  INFO root [0x00002418] [2018-06-22 22:51:43,728] - 	entryScriptFile : kbemain
  INFO root [0x00002418] [2018-06-22 22:51:43,728] - 	internalAddr : 192.168.31.56:11013
  INFO root [0x00002418] [2018-06-22 22:51:43,728] - 	componentID : 8001
  INFO root [0x00002418] [2018-06-22 22:51:45,244] - ---- cellapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: D25B4E16028C33EB467B7BE2F3500426. Config: Debug X86. Built: 23:20:13 Jun 15 2018. AppID: 8001. UID: 3337. PID: 10736 ----
  INFO root [0x00002418] [2018-06-22 22:51:45,246] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [0x00002418] [2018-06-22 22:51:45,247] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00002418] [2018-06-22 22:51:45,248] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00002418] [2018-06-22 22:51:45,589] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002418] [2018-06-22 22:51:45,609] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00002418] [2018-06-22 22:51:45,633] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00002418] [2018-06-22 22:51:45,641] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002418] [2018-06-22 22:51:45,642] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00002418] [2018-06-22 22:51:45,643] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002418] [2018-06-22 22:51:45,645] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002418] [2018-06-22 22:51:45,735] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00002418] [2018-06-22 22:51:45,838] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:17:57) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00002418] [2018-06-22 22:51:45,838] - Script::install(): KBExtra is successfully!
  INFO root [0x00002418] [2018-06-22 22:51:45,922] - TelnetServer server is running on port 50000
  INFO root [0x00002418] [2018-06-22 22:51:48,021] - ---- cellapp is running ----
 DEBUG root [0x00002418] [2018-06-22 22:51:48,022] - Components::process(): Request for the process of identity...
  WARN root [0x00002418] [2018-06-22 22:51:54,155] - EntityApp::checkTickPeriod: tick took 6133% (6.13 seconds)!
  INFO root [0x00002418] [2018-06-22 22:51:55,220] - Components::findComponents: find logger(1)...
  INFO root [0x00002418] [2018-06-22 22:51:55,232] - Components::findComponents: found logger, addr:192.168.31.56:11017
  INFO root [0x00002418] [2018-06-22 22:51:55,233] - Components::addComponent: reset orderLog, uid=3337!
  INFO root [0x00002418] [2018-06-22 22:51:55,233] - Components::addComponent[logger], uid=3337, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002418] [2018-06-22 22:51:55,235] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00002418] [2018-06-22 22:51:55,335] - Components::findComponents: found dbmgr, addr:192.168.31.56:11020
  INFO root [0x00002418] [2018-06-22 22:51:55,336] - Components::addComponent: reset orderLog, uid=3337!
  INFO root [0x00002418] [2018-06-22 22:51:55,336] - Components::addComponent[dbmgr], uid=3337, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002418] [2018-06-22 22:51:55,337] - Components::findComponents: found dbmgr, addr:192.168.31.56:11020
  WARN root [0x00002418] [2018-06-22 22:51:56,337] - Forwarding logs to logger[192.168.31.56:11017/0/0/0]...
 ERROR root [0x00002418] [2018-06-22 23:12:41,467] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00002418] [2018-06-22 23:12:41,483] - The following logs sent to logger failed:
  WARN root [0x00002418] [2018-06-22 23:12:41,483] - ==> [2018-06-22 23:12:41 464] TCPPacketReceiver::processPendingEvents(192.168.31.56:11017): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002418] [2018-06-22 23:12:41,484] - ==> [2018-06-22 23:12:41 468] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00002418] [2018-06-22 23:12:41,566] - TCPPacketReceiver::processPendingEvents(192.168.31.56:11020): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002418] [2018-06-22 23:12:41,571] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00002418] [2018-06-22 23:12:41,578] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00002418] [2018-06-22 23:12:41,581] - Shutdowner::onShutdown: shutting down
  INFO root [0x00002418] [2018-06-22 23:12:41,582] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00002418] [2018-06-22 23:12:41,714] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x00002418] [2018-06-22 23:12:41,729] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x00002418] [2018-06-22 23:12:41,900] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002418] [2018-06-22 23:12:41,900] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00002418] [2018-06-22 23:12:41,900] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00002418] [2018-06-22 23:12:41,901] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002418] [2018-06-22 23:12:41,901] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00002418] [2018-06-22 23:12:41,901] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002418] [2018-06-22 23:12:41,902] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002418] [2018-06-22 23:12:41,902] - Script::uninstall_py_dlls(): PyInit_unicodedata
