  INFO root [0x000065cc] [2018-06-19 14:21:44,564] - 
  INFO root [0x000065cc] [2018-06-19 14:21:44,582] - -----------------------------------------------------------------------------------------


  INFO root [0x000065cc] [2018-06-19 14:21:45,300] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [0x000065cc] [2018-06-19 14:21:45,302] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [0x000065cc] [2018-06-19 14:21:45,303] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [0x000065cc] [2018-06-19 14:21:45,727] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:2648 )
  INFO root [0x000065cc] [2018-06-19 14:21:45,733] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:2648, SOMAXCONN=5.
  INFO root [0x000065cc] [2018-06-19 14:21:45,733] - server-configs:
  INFO root [0x000065cc] [2018-06-19 14:21:45,733] - 	gameUpdateHertz : 10
  INFO root [0x000065cc] [2018-06-19 14:21:45,899] - 	defaultAoIRadius : 80
  INFO root [0x000065cc] [2018-06-19 14:21:45,900] - 	defaultAoIHysteresisArea : 5
  INFO root [0x000065cc] [2018-06-19 14:21:45,900] - 	entryScriptFile : kbemain
  INFO root [0x000065cc] [2018-06-19 14:21:45,900] - 	internalAddr : 192.168.31.56:2648
  INFO root [0x000065cc] [2018-06-19 14:21:45,900] - 	componentID : 8001
  INFO root [0x000065cc] [2018-06-19 14:21:46,065] - Components::findLogger: found logger, addr:192.168.31.56:2627
  INFO root [0x000065cc] [2018-06-19 14:21:46,066] - Components::addComponent: reset orderLog, uid=7221!
  INFO root [0x000065cc] [2018-06-19 14:21:46,070] - Components::addComponent[logger], uid=7221, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000065cc] [2018-06-19 14:21:46,099] - ---- cellapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: D25B4E16028C33EB467B7BE2F3500426. Config: Debug X86. Built: 23:20:13 Jun 15 2018. AppID: 8001. UID: 7221. PID: 21884 ----
  INFO root [0x000065cc] [2018-06-19 14:21:46,101] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [0x000065cc] [2018-06-19 14:21:46,110] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000065cc] [2018-06-19 14:21:46,110] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000065cc] [2018-06-19 14:21:47,106] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000065cc] [2018-06-19 14:21:47,357] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000065cc] [2018-06-19 14:21:47,418] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000065cc] [2018-06-19 14:21:47,922] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000065cc] [2018-06-19 14:21:47,964] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000065cc] [2018-06-19 14:21:47,983] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000065cc] [2018-06-19 14:21:48,008] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000065cc] [2018-06-19 14:21:48,371] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000065cc] [2018-06-19 14:21:49,464] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:17:57) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x000065cc] [2018-06-19 14:21:49,465] - Script::install(): KBExtra is successfully!
  INFO root [0x000065cc] [2018-06-19 14:21:50,580] - TelnetServer server is running on port 50000
  INFO root [0x000065cc] [2018-06-19 14:21:51,315] - ---- cellapp is running ----
 DEBUG root [0x000065cc] [2018-06-19 14:21:51,372] - Components::process(): Request for the process of identity...
  WARN root [0x000065cc] [2018-06-19 14:21:57,706] - Forwarding logs to logger[192.168.31.56:2627/0/0/0]...
 ERROR root [0x000065cc] [2018-06-19 16:43:18,442] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x000065cc] [2018-06-19 16:43:18,530] - The following logs sent to logger failed:
  WARN root [0x000065cc] [2018-06-19 16:43:18,639] - ==> [2018-06-19 16:43:18 398] TCPPacketReceiver::processPendingEvents(192.168.31.56:2627): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000065cc] [2018-06-19 16:43:18,639] - ==> [2018-06-19 16:43:18 443] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x000065cc] [2018-06-19 16:43:18,666] - EntityApp::checkTickPeriod: tick took 349% (0.35 seconds)!
  WARN root [0x000065cc] [2018-06-19 16:43:18,667] - TCPPacketReceiver::processPendingEvents(192.168.31.56:2631): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000065cc] [2018-06-19 16:43:18,667] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x000065cc] [2018-06-19 16:43:18,704] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x000065cc] [2018-06-19 16:43:18,704] - Shutdowner::onShutdown: shutting down
  INFO root [0x000065cc] [2018-06-19 16:43:18,705] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x000065cc] [2018-06-19 16:43:18,776] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x000065cc] [2018-06-19 16:43:18,783] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x000065cc] [2018-06-19 16:43:18,886] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000065cc] [2018-06-19 16:43:18,887] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x000065cc] [2018-06-19 16:43:18,887] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x000065cc] [2018-06-19 16:43:18,887] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x000065cc] [2018-06-19 16:43:18,888] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x000065cc] [2018-06-19 16:43:18,888] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x000065cc] [2018-06-19 16:43:18,888] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x000065cc] [2018-06-19 16:43:18,888] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x000065cc] [2018-06-19 16:43:18,954] - Script::uninstall(): is successfully!
 DEBUG root [0x000065cc] [2018-06-19 16:43:18,966] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00005044] [2018-06-19 16:43:27,323] - 
  INFO root [0x00005044] [2018-06-19 16:43:27,324] - -----------------------------------------------------------------------------------------


  INFO root [0x00005044] [2018-06-19 16:43:27,326] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [0x00005044] [2018-06-19 16:43:27,327] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [0x00005044] [2018-06-19 16:43:27,328] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [0x00005044] [2018-06-19 16:43:27,343] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:5970 )
  INFO root [0x00005044] [2018-06-19 16:43:27,343] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:5970, SOMAXCONN=5.
  INFO root [0x00005044] [2018-06-19 16:43:27,344] - server-configs:
  INFO root [0x00005044] [2018-06-19 16:43:27,344] - 	gameUpdateHertz : 10
  INFO root [0x00005044] [2018-06-19 16:43:27,344] - 	defaultAoIRadius : 80
  INFO root [0x00005044] [2018-06-19 16:43:27,345] - 	defaultAoIHysteresisArea : 5
  INFO root [0x00005044] [2018-06-19 16:43:27,345] - 	entryScriptFile : kbemain
  INFO root [0x00005044] [2018-06-19 16:43:27,345] - 	internalAddr : 192.168.31.56:5970
  INFO root [0x00005044] [2018-06-19 16:43:27,346] - 	componentID : 8001
  WARN root [0x00005044] [2018-06-19 16:43:27,726] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20394, errorno=10048
  INFO root [0x00005044] [2018-06-19 16:43:27,740] - ---- cellapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: D25B4E16028C33EB467B7BE2F3500426. Config: Debug X86. Built: 23:20:13 Jun 15 2018. AppID: 8001. UID: 2247. PID: 29428 ----
  INFO root [0x00005044] [2018-06-19 16:43:27,741] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [0x00005044] [2018-06-19 16:43:27,741] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00005044] [2018-06-19 16:43:27,742] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00005044] [2018-06-19 16:43:27,920] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00005044] [2018-06-19 16:43:27,921] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00005044] [2018-06-19 16:43:27,923] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00005044] [2018-06-19 16:43:27,929] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00005044] [2018-06-19 16:43:27,930] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00005044] [2018-06-19 16:43:27,930] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00005044] [2018-06-19 16:43:27,931] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00005044] [2018-06-19 16:43:28,006] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00005044] [2018-06-19 16:43:28,078] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:17:57) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00005044] [2018-06-19 16:43:28,078] - Script::install(): KBExtra is successfully!
  INFO root [0x00005044] [2018-06-19 16:43:28,142] - TelnetServer server is running on port 50000
  INFO root [0x00005044] [2018-06-19 16:43:29,499] - ---- cellapp is running ----
 DEBUG root [0x00005044] [2018-06-19 16:43:29,501] - Components::process(): Request for the process of identity...
  WARN root [0x00005044] [2018-06-19 16:43:35,975] - EntityApp::checkTickPeriod: tick took 6475% (6.47 seconds)!
  INFO root [0x00005044] [2018-06-19 16:43:37,001] - Components::findComponents: find logger(1)...
  INFO root [0x00005044] [2018-06-19 16:43:37,027] - Components::findComponents: found logger, addr:192.168.31.56:5968
  INFO root [0x00005044] [2018-06-19 16:43:37,027] - Components::addComponent: reset orderLog, uid=2247!
  INFO root [0x00005044] [2018-06-19 16:43:37,028] - Components::addComponent[logger], uid=2247, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00005044] [2018-06-19 16:43:37,029] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00005044] [2018-06-19 16:43:37,133] - Components::findComponents: found dbmgr, addr:192.168.31.56:5973
  INFO root [0x00005044] [2018-06-19 16:43:37,133] - Components::addComponent: reset orderLog, uid=2247!
  INFO root [0x00005044] [2018-06-19 16:43:37,134] - Components::addComponent[dbmgr], uid=2247, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00005044] [2018-06-19 16:43:37,134] - Components::findComponents: found dbmgr, addr:192.168.31.56:5973
  WARN root [0x00005044] [2018-06-19 16:43:38,134] - EntityApp::checkTickPeriod: tick took 1233% (1.23 seconds)!
  WARN root [0x00005044] [2018-06-19 16:43:38,135] - Forwarding logs to logger[192.168.31.56:5968/0/0/0]...
 ERROR root [0x00005044] [2018-06-19 17:57:17,178] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00005044] [2018-06-19 17:57:17,193] - The following logs sent to logger failed:
  WARN root [0x00005044] [2018-06-19 17:57:17,193] - ==> [2018-06-19 17:57:17 175] TCPPacketReceiver::processPendingEvents(192.168.31.56:5968): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00005044] [2018-06-19 17:57:17,194] - ==> [2018-06-19 17:57:17 179] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00005044] [2018-06-19 17:57:17,301] - TCPPacketReceiver::processPendingEvents(192.168.31.56:5973): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00005044] [2018-06-19 17:57:17,304] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00005044] [2018-06-19 17:57:17,310] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00005044] [2018-06-19 17:57:17,321] - Shutdowner::onShutdown: shutting down
  INFO root [0x00005044] [2018-06-19 17:57:17,322] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00005044] [2018-06-19 17:57:17,323] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x00005044] [2018-06-19 17:57:17,323] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x00005044] [2018-06-19 17:57:17,380] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00005044] [2018-06-19 17:57:17,380] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00005044] [2018-06-19 17:57:17,380] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00005044] [2018-06-19 17:57:17,381] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00005044] [2018-06-19 17:57:17,381] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00005044] [2018-06-19 17:57:17,381] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00005044] [2018-06-19 17:57:17,381] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00005044] [2018-06-19 17:57:17,382] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00005044] [2018-06-19 17:57:17,395] - Script::uninstall(): is successfully!
 DEBUG root [0x00005044] [2018-06-19 17:57:17,396] - ThreadPool::destroy(): starting size 2.
  WARN root [0x00005044] [2018-06-19 17:57:17,696] - ThreadPool::destroy(): waiting for thread(2)[0x332288,0x332220,], try=1
  INFO root [0x000078f0] [2018-06-19 17:57:23,794] - 
  INFO root [0x000078f0] [2018-06-19 17:57:23,795] - -----------------------------------------------------------------------------------------


  INFO root [0x000078f0] [2018-06-19 17:57:23,797] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [0x000078f0] [2018-06-19 17:57:23,798] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [0x000078f0] [2018-06-19 17:57:23,809] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [0x000078f0] [2018-06-19 17:57:23,821] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:6991 )
  INFO root [0x000078f0] [2018-06-19 17:57:23,823] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:6991, SOMAXCONN=5.
  INFO root [0x000078f0] [2018-06-19 17:57:23,823] - server-configs:
  INFO root [0x000078f0] [2018-06-19 17:57:23,823] - 	gameUpdateHertz : 10
  INFO root [0x000078f0] [2018-06-19 17:57:23,824] - 	defaultAoIRadius : 80
  INFO root [0x000078f0] [2018-06-19 17:57:23,824] - 	defaultAoIHysteresisArea : 5
  INFO root [0x000078f0] [2018-06-19 17:57:23,824] - 	entryScriptFile : kbemain
  INFO root [0x000078f0] [2018-06-19 17:57:23,824] - 	internalAddr : 192.168.31.56:6991
  INFO root [0x000078f0] [2018-06-19 17:57:23,825] - 	componentID : 8001
  INFO root [0x000078f0] [2018-06-19 17:57:25,333] - ---- cellapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: D25B4E16028C33EB467B7BE2F3500426. Config: Debug X86. Built: 23:20:13 Jun 15 2018. AppID: 8001. UID: 16733. PID: 26628 ----
  INFO root [0x000078f0] [2018-06-19 17:57:25,334] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [0x000078f0] [2018-06-19 17:57:25,334] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000078f0] [2018-06-19 17:57:25,335] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000078f0] [2018-06-19 17:57:25,487] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000078f0] [2018-06-19 17:57:25,487] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000078f0] [2018-06-19 17:57:25,488] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000078f0] [2018-06-19 17:57:25,493] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000078f0] [2018-06-19 17:57:25,493] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000078f0] [2018-06-19 17:57:25,493] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000078f0] [2018-06-19 17:57:25,494] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000078f0] [2018-06-19 17:57:25,562] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000078f0] [2018-06-19 17:57:25,677] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:17:57) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x000078f0] [2018-06-19 17:57:25,678] - Script::install(): KBExtra is successfully!
  INFO root [0x000078f0] [2018-06-19 17:57:25,697] - TelnetServer server is running on port 50000
  INFO root [0x000078f0] [2018-06-19 17:57:27,819] - ---- cellapp is running ----
 DEBUG root [0x000078f0] [2018-06-19 17:57:27,821] - Components::process(): Request for the process of identity...
  WARN root [0x000078f0] [2018-06-19 17:57:34,071] - EntityApp::checkTickPeriod: tick took 6251% (6.25 seconds)!
  INFO root [0x000078f0] [2018-06-19 17:57:35,111] - Components::findComponents: find logger(1)...
  INFO root [0x000078f0] [2018-06-19 17:57:35,141] - Components::findComponents: found logger, addr:192.168.31.56:6997
  INFO root [0x000078f0] [2018-06-19 17:57:35,142] - Components::addComponent: reset orderLog, uid=16733!
  INFO root [0x000078f0] [2018-06-19 17:57:35,142] - Components::addComponent[logger], uid=16733, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000078f0] [2018-06-19 17:57:35,144] - Components::findComponents: find dbmgr(2)...
  INFO root [0x000078f0] [2018-06-19 17:57:35,245] - Components::findComponents: found dbmgr, addr:192.168.31.56:6993
  INFO root [0x000078f0] [2018-06-19 17:57:35,246] - Components::addComponent: reset orderLog, uid=16733!
  INFO root [0x000078f0] [2018-06-19 17:57:35,246] - Components::addComponent[dbmgr], uid=16733, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000078f0] [2018-06-19 17:57:35,246] - Components::findComponents: found dbmgr, addr:192.168.31.56:6993
  WARN root [0x000078f0] [2018-06-19 17:57:36,247] - Forwarding logs to logger[192.168.31.56:6997/0/0/0]...
 ERROR root [0x000078f0] [2018-06-19 17:57:36,248] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x000078f0] [2018-06-19 17:57:36,250] - The following logs sent to logger failed:
  WARN root [0x000078f0] [2018-06-19 17:57:36,250] - ==> [2018-06-19 17:57:36 248] TCPPacketReceiver::processPendingEvents(192.168.31.56:6997): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000078f0] [2018-06-19 17:57:36,251] - ==> [2018-06-19 17:57:36 248] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00000470] [2018-06-19 17:57:45,438] - 
  INFO root [0x00000470] [2018-06-19 17:57:45,442] - -----------------------------------------------------------------------------------------


  INFO root [0x00000470] [2018-06-19 17:57:45,444] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [0x00000470] [2018-06-19 17:57:45,445] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [0x00000470] [2018-06-19 17:57:45,445] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [0x00000470] [2018-06-19 17:57:45,479] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:7023 )
  INFO root [0x00000470] [2018-06-19 17:57:45,479] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:7023, SOMAXCONN=5.
  INFO root [0x00000470] [2018-06-19 17:57:45,480] - server-configs:
  INFO root [0x00000470] [2018-06-19 17:57:45,480] - 	gameUpdateHertz : 10
  INFO root [0x00000470] [2018-06-19 17:57:45,480] - 	defaultAoIRadius : 80
  INFO root [0x00000470] [2018-06-19 17:57:45,481] - 	defaultAoIHysteresisArea : 5
  INFO root [0x00000470] [2018-06-19 17:57:45,481] - 	entryScriptFile : kbemain
  INFO root [0x00000470] [2018-06-19 17:57:45,481] - 	internalAddr : 192.168.31.56:7023
  INFO root [0x00000470] [2018-06-19 17:57:45,482] - 	componentID : 8001
  INFO root [0x00000470] [2018-06-19 17:57:46,998] - ---- cellapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: D25B4E16028C33EB467B7BE2F3500426. Config: Debug X86. Built: 23:20:13 Jun 15 2018. AppID: 8001. UID: 16805. PID: 30464 ----
  INFO root [0x00000470] [2018-06-19 17:57:46,999] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [0x00000470] [2018-06-19 17:57:47,000] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00000470] [2018-06-19 17:57:47,001] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00000470] [2018-06-19 17:57:47,179] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00000470] [2018-06-19 17:57:47,180] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00000470] [2018-06-19 17:57:47,181] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00000470] [2018-06-19 17:57:47,186] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00000470] [2018-06-19 17:57:47,187] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00000470] [2018-06-19 17:57:47,187] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00000470] [2018-06-19 17:57:47,189] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00000470] [2018-06-19 17:57:47,310] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00000470] [2018-06-19 17:57:47,435] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:17:57) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00000470] [2018-06-19 17:57:47,436] - Script::install(): KBExtra is successfully!
  INFO root [0x00000470] [2018-06-19 17:57:47,488] - TelnetServer server is running on port 50000
  INFO root [0x00000470] [2018-06-19 17:57:48,795] - ---- cellapp is running ----
 DEBUG root [0x00000470] [2018-06-19 17:57:48,796] - Components::process(): Request for the process of identity...
  WARN root [0x00000470] [2018-06-19 17:57:54,945] - EntityApp::checkTickPeriod: tick took 6149% (6.15 seconds)!
  INFO root [0x00000470] [2018-06-19 17:57:55,996] - Components::findComponents: find logger(1)...
  INFO root [0x00000470] [2018-06-19 17:57:56,019] - Components::findComponents: found logger, addr:192.168.31.56:7020
  INFO root [0x00000470] [2018-06-19 17:57:56,020] - Components::addComponent: reset orderLog, uid=16805!
  INFO root [0x00000470] [2018-06-19 17:57:56,020] - Components::addComponent[logger], uid=16805, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00000470] [2018-06-19 17:57:56,022] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00000470] [2018-06-19 17:57:56,123] - Components::findComponents: found dbmgr, addr:192.168.31.56:7024
  INFO root [0x00000470] [2018-06-19 17:57:56,123] - Components::addComponent: reset orderLog, uid=16805!
  INFO root [0x00000470] [2018-06-19 17:57:56,123] - Components::addComponent[dbmgr], uid=16805, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00000470] [2018-06-19 17:57:56,124] - Components::findComponents: found dbmgr, addr:192.168.31.56:7024
  WARN root [0x00000470] [2018-06-19 17:57:57,124] - EntityApp::checkTickPeriod: tick took 1228% (1.23 seconds)!
  WARN root [0x00000470] [2018-06-19 17:57:57,125] - Forwarding logs to logger[192.168.31.56:7020/0/0/0]...
 ERROR root [0x00000470] [2018-06-19 18:01:14,845] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00000470] [2018-06-19 18:01:14,858] - The following logs sent to logger failed:
  WARN root [0x00000470] [2018-06-19 18:01:14,859] - ==> [2018-06-19 18:01:14 839] TCPPacketReceiver::processPendingEvents(192.168.31.56:7020): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00000470] [2018-06-19 18:01:14,860] - ==> [2018-06-19 18:01:14 846] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00000470] [2018-06-19 18:01:14,961] - TCPPacketReceiver::processPendingEvents(192.168.31.56:7024): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00000470] [2018-06-19 18:01:14,963] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00000470] [2018-06-19 18:01:14,976] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00000470] [2018-06-19 18:01:14,985] - Shutdowner::onShutdown: shutting down
  INFO root [0x00000470] [2018-06-19 18:01:14,985] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00000470] [2018-06-19 18:01:14,987] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x00000470] [2018-06-19 18:01:14,987] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x00000470] [2018-06-19 18:01:15,006] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00000470] [2018-06-19 18:01:15,025] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00000470] [2018-06-19 18:01:15,026] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00000470] [2018-06-19 18:01:15,026] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00000470] [2018-06-19 18:01:15,026] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00000470] [2018-06-19 18:01:15,026] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00000470] [2018-06-19 18:01:15,027] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00000470] [2018-06-19 18:01:15,027] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00000470] [2018-06-19 18:01:15,042] - Script::uninstall(): is successfully!
 DEBUG root [0x00000470] [2018-06-19 18:01:15,042] - ThreadPool::destroy(): starting size 2.
  WARN root [0x00000470] [2018-06-19 18:01:15,342] - ThreadPool::destroy(): waiting for thread(2)[0x1ce2198,0x1ce2130,], try=1
  INFO root [0x00007ab8] [2018-06-19 18:01:19,331] - 
  INFO root [0x00007ab8] [2018-06-19 18:01:19,332] - -----------------------------------------------------------------------------------------


  INFO root [0x00007ab8] [2018-06-19 18:01:19,334] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [0x00007ab8] [2018-06-19 18:01:19,335] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [0x00007ab8] [2018-06-19 18:01:19,336] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [0x00007ab8] [2018-06-19 18:01:19,349] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:7087 )
  INFO root [0x00007ab8] [2018-06-19 18:01:19,350] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:7087, SOMAXCONN=5.
  INFO root [0x00007ab8] [2018-06-19 18:01:19,350] - server-configs:
  INFO root [0x00007ab8] [2018-06-19 18:01:19,350] - 	gameUpdateHertz : 10
  INFO root [0x00007ab8] [2018-06-19 18:01:19,351] - 	defaultAoIRadius : 80
  INFO root [0x00007ab8] [2018-06-19 18:01:19,351] - 	defaultAoIHysteresisArea : 5
  INFO root [0x00007ab8] [2018-06-19 18:01:19,351] - 	entryScriptFile : kbemain
  INFO root [0x00007ab8] [2018-06-19 18:01:19,351] - 	internalAddr : 192.168.31.56:7087
  INFO root [0x00007ab8] [2018-06-19 18:01:19,352] - 	componentID : 8001
  INFO root [0x00007ab8] [2018-06-19 18:01:20,874] - ---- cellapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: D25B4E16028C33EB467B7BE2F3500426. Config: Debug X86. Built: 23:20:13 Jun 15 2018. AppID: 8001. UID: 17504. PID: 28724 ----
  INFO root [0x00007ab8] [2018-06-19 18:01:20,875] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [0x00007ab8] [2018-06-19 18:01:20,875] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00007ab8] [2018-06-19 18:01:20,876] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00007ab8] [2018-06-19 18:01:21,074] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00007ab8] [2018-06-19 18:01:21,075] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00007ab8] [2018-06-19 18:01:21,077] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00007ab8] [2018-06-19 18:01:21,083] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00007ab8] [2018-06-19 18:01:21,084] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00007ab8] [2018-06-19 18:01:21,085] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00007ab8] [2018-06-19 18:01:21,086] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00007ab8] [2018-06-19 18:01:21,171] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00007ab8] [2018-06-19 18:01:21,255] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:17:57) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00007ab8] [2018-06-19 18:01:21,255] - Script::install(): KBExtra is successfully!
  INFO root [0x00007ab8] [2018-06-19 18:01:21,275] - TelnetServer server is running on port 50000
  INFO root [0x00007ab8] [2018-06-19 18:01:22,539] - ---- cellapp is running ----
 DEBUG root [0x00007ab8] [2018-06-19 18:01:22,542] - Components::process(): Request for the process of identity...
  WARN root [0x00007ab8] [2018-06-19 18:01:28,686] - EntityApp::checkTickPeriod: tick took 6146% (6.15 seconds)!
  INFO root [0x00007ab8] [2018-06-19 18:01:29,738] - Components::findComponents: find logger(1)...
  INFO root [0x00007ab8] [2018-06-19 18:01:29,832] - Components::findComponents: found logger, addr:192.168.31.56:7083
  INFO root [0x00007ab8] [2018-06-19 18:01:29,833] - Components::addComponent: reset orderLog, uid=17504!
  INFO root [0x00007ab8] [2018-06-19 18:01:29,833] - Components::addComponent[logger], uid=17504, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00007ab8] [2018-06-19 18:01:29,834] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00007ab8] [2018-06-19 18:01:29,936] - Components::findComponents: found dbmgr, addr:192.168.31.56:7090
  INFO root [0x00007ab8] [2018-06-19 18:01:29,936] - Components::addComponent: reset orderLog, uid=17504!
  INFO root [0x00007ab8] [2018-06-19 18:01:29,937] - Components::addComponent[dbmgr], uid=17504, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00007ab8] [2018-06-19 18:01:29,937] - Components::findComponents: found dbmgr, addr:192.168.31.56:7090
  WARN root [0x00007ab8] [2018-06-19 18:01:30,937] - Forwarding logs to logger[192.168.31.56:7083/0/0/0]...
 ERROR root [0x00007ab8] [2018-06-19 18:01:31,539] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00007ab8] [2018-06-19 18:01:31,543] - The following logs sent to logger failed:
  WARN root [0x00007ab8] [2018-06-19 18:01:31,544] - ==> [2018-06-19 18:01:31 535] TCPPacketReceiver::processPendingEvents(192.168.31.56:7083): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00007ab8] [2018-06-19 18:01:31,544] - ==> [2018-06-19 18:01:31 540] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00007ab8] [2018-06-19 18:01:31,938] - Components::findComponents: find cellappmgr(1)...
  INFO root [0x00005e80] [2018-06-19 18:01:42,028] - 
  INFO root [0x00005e80] [2018-06-19 18:01:42,030] - -----------------------------------------------------------------------------------------


  INFO root [0x00005e80] [2018-06-19 18:01:42,031] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [0x00005e80] [2018-06-19 18:01:42,032] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [0x00005e80] [2018-06-19 18:01:42,033] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [0x00005e80] [2018-06-19 18:01:42,046] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:7113 )
  INFO root [0x00005e80] [2018-06-19 18:01:42,047] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:7113, SOMAXCONN=5.
  INFO root [0x00005e80] [2018-06-19 18:01:42,047] - server-configs:
  INFO root [0x00005e80] [2018-06-19 18:01:42,047] - 	gameUpdateHertz : 10
  INFO root [0x00005e80] [2018-06-19 18:01:42,048] - 	defaultAoIRadius : 80
  INFO root [0x00005e80] [2018-06-19 18:01:42,048] - 	defaultAoIHysteresisArea : 5
  INFO root [0x00005e80] [2018-06-19 18:01:42,048] - 	entryScriptFile : kbemain
  INFO root [0x00005e80] [2018-06-19 18:01:42,050] - 	internalAddr : 192.168.31.56:7113
  INFO root [0x00005e80] [2018-06-19 18:01:42,050] - 	componentID : 8001
  INFO root [0x00005e80] [2018-06-19 18:01:43,565] - ---- cellapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: D25B4E16028C33EB467B7BE2F3500426. Config: Debug X86. Built: 23:20:13 Jun 15 2018. AppID: 8001. UID: 17575. PID: 27744 ----
  INFO root [0x00005e80] [2018-06-19 18:01:43,567] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [0x00005e80] [2018-06-19 18:01:43,567] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00005e80] [2018-06-19 18:01:43,568] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00005e80] [2018-06-19 18:01:43,750] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00005e80] [2018-06-19 18:01:43,751] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00005e80] [2018-06-19 18:01:43,752] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00005e80] [2018-06-19 18:01:43,760] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00005e80] [2018-06-19 18:01:43,761] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00005e80] [2018-06-19 18:01:43,761] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00005e80] [2018-06-19 18:01:43,763] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00005e80] [2018-06-19 18:01:43,856] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00005e80] [2018-06-19 18:01:43,953] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:17:57) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00005e80] [2018-06-19 18:01:43,954] - Script::install(): KBExtra is successfully!
  INFO root [0x00005e80] [2018-06-19 18:01:43,974] - TelnetServer server is running on port 50000
  INFO root [0x00005e80] [2018-06-19 18:01:45,142] - ---- cellapp is running ----
 DEBUG root [0x00005e80] [2018-06-19 18:01:45,144] - Components::process(): Request for the process of identity...
  WARN root [0x00005e80] [2018-06-19 18:01:51,282] - EntityApp::checkTickPeriod: tick took 6139% (6.14 seconds)!
  INFO root [0x00005e80] [2018-06-19 18:01:52,335] - Components::findComponents: find logger(1)...
  INFO root [0x00005e80] [2018-06-19 18:01:52,431] - Components::findComponents: found logger, addr:192.168.31.56:7108
  INFO root [0x00005e80] [2018-06-19 18:01:52,431] - Components::addComponent: reset orderLog, uid=17575!
  INFO root [0x00005e80] [2018-06-19 18:01:52,432] - Components::addComponent[logger], uid=17575, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00005e80] [2018-06-19 18:01:52,434] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00005e80] [2018-06-19 18:01:52,535] - Components::findComponents: found dbmgr, addr:192.168.31.56:7110
  INFO root [0x00005e80] [2018-06-19 18:01:52,535] - Components::addComponent: reset orderLog, uid=17575!
  INFO root [0x00005e80] [2018-06-19 18:01:52,535] - Components::addComponent[dbmgr], uid=17575, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00005e80] [2018-06-19 18:01:52,537] - Components::findComponents: found dbmgr, addr:192.168.31.56:7110
  WARN root [0x00005e80] [2018-06-19 18:01:53,537] - Forwarding logs to logger[192.168.31.56:7108/0/0/0]...
 ERROR root [0x00005e80] [2018-06-19 18:02:20,309] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00005e80] [2018-06-19 18:02:20,320] - The following logs sent to logger failed:
  WARN root [0x00005e80] [2018-06-19 18:02:20,320] - ==> [2018-06-19 18:02:20 307] TCPPacketReceiver::processPendingEvents(192.168.31.56:7108): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00005e80] [2018-06-19 18:02:20,321] - ==> [2018-06-19 18:02:20 310] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00005e80] [2018-06-19 18:02:20,422] - TCPPacketReceiver::processPendingEvents(192.168.31.56:7110): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00005e80] [2018-06-19 18:02:20,425] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00005e80] [2018-06-19 18:02:20,431] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00005e80] [2018-06-19 18:02:20,437] - Shutdowner::onShutdown: shutting down
  INFO root [0x00005e80] [2018-06-19 18:02:20,437] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00005e80] [2018-06-19 18:02:20,438] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x00005e80] [2018-06-19 18:02:20,439] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x00005e80] [2018-06-19 18:02:20,471] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00005e80] [2018-06-19 18:02:20,471] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00005e80] [2018-06-19 18:02:20,471] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00005e80] [2018-06-19 18:02:20,472] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00005e80] [2018-06-19 18:02:20,472] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00005e80] [2018-06-19 18:02:20,472] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00005e80] [2018-06-19 18:02:20,472] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00005e80] [2018-06-19 18:02:20,473] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00005e80] [2018-06-19 18:02:20,488] - Script::uninstall(): is successfully!
 DEBUG root [0x00005e80] [2018-06-19 18:02:20,488] - ThreadPool::destroy(): starting size 2.
  WARN root [0x00005e80] [2018-06-19 18:02:20,788] - ThreadPool::destroy(): waiting for thread(2)[0x552198,0x552130,], try=1
  INFO root [0x000039c0] [2018-06-19 18:02:41,129] - 
  INFO root [0x000039c0] [2018-06-19 18:02:41,130] - -----------------------------------------------------------------------------------------


  INFO root [0x000039c0] [2018-06-19 18:02:41,132] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [0x000039c0] [2018-06-19 18:02:41,133] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [0x000039c0] [2018-06-19 18:02:41,134] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [0x000039c0] [2018-06-19 18:02:41,145] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:7154 )
  INFO root [0x000039c0] [2018-06-19 18:02:41,146] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:7154, SOMAXCONN=5.
  INFO root [0x000039c0] [2018-06-19 18:02:41,146] - server-configs:
  INFO root [0x000039c0] [2018-06-19 18:02:41,146] - 	gameUpdateHertz : 10
  INFO root [0x000039c0] [2018-06-19 18:02:41,147] - 	defaultAoIRadius : 80
  INFO root [0x000039c0] [2018-06-19 18:02:41,147] - 	defaultAoIHysteresisArea : 5
  INFO root [0x000039c0] [2018-06-19 18:02:41,147] - 	entryScriptFile : kbemain
  INFO root [0x000039c0] [2018-06-19 18:02:41,147] - 	internalAddr : 192.168.31.56:7154
  INFO root [0x000039c0] [2018-06-19 18:02:41,148] - 	componentID : 8001
  INFO root [0x000039c0] [2018-06-19 18:02:42,697] - ---- cellapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: D25B4E16028C33EB467B7BE2F3500426. Config: Debug X86. Built: 23:20:13 Jun 15 2018. AppID: 8001. UID: 17768. PID: 29136 ----
  INFO root [0x000039c0] [2018-06-19 18:02:42,698] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [0x000039c0] [2018-06-19 18:02:42,699] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000039c0] [2018-06-19 18:02:42,700] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000039c0] [2018-06-19 18:02:43,044] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000039c0] [2018-06-19 18:02:43,045] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000039c0] [2018-06-19 18:02:43,046] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000039c0] [2018-06-19 18:02:43,053] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000039c0] [2018-06-19 18:02:43,054] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000039c0] [2018-06-19 18:02:43,055] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000039c0] [2018-06-19 18:02:43,057] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000039c0] [2018-06-19 18:02:43,276] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000039c0] [2018-06-19 18:02:43,501] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:17:57) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x000039c0] [2018-06-19 18:02:43,502] - Script::install(): KBExtra is successfully!
  INFO root [0x000039c0] [2018-06-19 18:02:43,521] - TelnetServer server is running on port 50000
  INFO root [0x000039c0] [2018-06-19 18:02:44,925] - ---- cellapp is running ----
 DEBUG root [0x000039c0] [2018-06-19 18:02:44,926] - Components::process(): Request for the process of identity...
  WARN root [0x000039c0] [2018-06-19 18:02:51,073] - EntityApp::checkTickPeriod: tick took 6148% (6.15 seconds)!
 DEBUG root [0x000039c0] [2018-06-19 18:02:51,854] - Cellapp::lookApp: 192.168.31.56:7174/0/0/0
  INFO root [0x000039c0] [2018-06-19 18:02:52,136] - Components::findComponents: find logger(1)...
  INFO root [0x000039c0] [2018-06-19 18:02:52,214] - Components::findComponents: found logger, addr:192.168.31.56:7151
  INFO root [0x000039c0] [2018-06-19 18:02:52,214] - Components::addComponent: reset orderLog, uid=17768!
  INFO root [0x000039c0] [2018-06-19 18:02:52,215] - Components::addComponent[logger], uid=17768, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000039c0] [2018-06-19 18:02:52,217] - Components::findComponents: find dbmgr(2)...
  INFO root [0x000039c0] [2018-06-19 18:02:52,318] - Components::findComponents: found dbmgr, addr:192.168.31.56:7146
  INFO root [0x000039c0] [2018-06-19 18:02:52,319] - Components::addComponent: reset orderLog, uid=17768!
  INFO root [0x000039c0] [2018-06-19 18:02:52,319] - Components::addComponent[dbmgr], uid=17768, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000039c0] [2018-06-19 18:02:52,320] - Components::findComponents: found dbmgr, addr:192.168.31.56:7146
  WARN root [0x000039c0] [2018-06-19 18:02:53,320] - Forwarding logs to logger[192.168.31.56:7151/0/0/0]...
 ERROR root [0x000039c0] [2018-06-19 23:29:07,520] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x000039c0] [2018-06-19 23:29:07,611] - The following logs sent to logger failed:
  WARN root [0x000039c0] [2018-06-19 23:29:07,704] - ==> [2018-06-19 23:29:07 517] TCPPacketReceiver::processPendingEvents(192.168.31.56:7151): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000039c0] [2018-06-19 23:29:07,705] - ==> [2018-06-19 23:29:07 520] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x000039c0] [2018-06-19 23:29:07,735] - EntityApp::checkTickPeriod: tick took 275% (0.28 seconds)!
  WARN root [0x000039c0] [2018-06-19 23:29:07,736] - TCPPacketReceiver::processPendingEvents(192.168.31.56:7146): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000039c0] [2018-06-19 23:29:07,737] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x000039c0] [2018-06-19 23:29:07,795] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x000039c0] [2018-06-19 23:29:07,796] - Shutdowner::onShutdown: shutting down
  INFO root [0x000039c0] [2018-06-19 23:29:07,796] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x000039c0] [2018-06-19 23:29:07,861] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x000039c0] [2018-06-19 23:29:07,875] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x000039c0] [2018-06-19 23:29:07,967] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000039c0] [2018-06-19 23:29:07,967] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x000039c0] [2018-06-19 23:29:07,968] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x000039c0] [2018-06-19 23:29:07,968] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x000039c0] [2018-06-19 23:29:07,969] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x000039c0] [2018-06-19 23:29:07,969] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x000039c0] [2018-06-19 23:29:07,969] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x000039c0] [2018-06-19 23:29:07,969] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x000039c0] [2018-06-19 23:29:08,035] - Script::uninstall(): is successfully!
 DEBUG root [0x000039c0] [2018-06-19 23:29:08,046] - ThreadPool::destroy(): starting size 2.
