  INFO root [0x00004a60] [2018-06-17 12:15:41,661] - 
  INFO root [0x00004a60] [2018-06-17 12:15:41,810] - -----------------------------------------------------------------------------------------


  INFO root [0x00004a60] [2018-06-17 12:15:43,377] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [0x00004a60] [2018-06-17 12:15:43,378] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [0x00004a60] [2018-06-17 12:15:43,378] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [0x00004a60] [2018-06-17 12:15:43,726] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:38537 )
  INFO root [0x00004a60] [2018-06-17 12:15:43,800] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:38537, SOMAXCONN=5.
  INFO root [0x00004a60] [2018-06-17 12:15:43,800] - server-configs:
  INFO root [0x00004a60] [2018-06-17 12:15:43,800] - 	gameUpdateHertz : 10
  INFO root [0x00004a60] [2018-06-17 12:15:43,924] - 	defaultAoIRadius : 80
  INFO root [0x00004a60] [2018-06-17 12:15:43,924] - 	defaultAoIHysteresisArea : 5
  INFO root [0x00004a60] [2018-06-17 12:15:43,925] - 	entryScriptFile : kbemain
  INFO root [0x00004a60] [2018-06-17 12:15:43,925] - 	internalAddr : 192.168.31.56:38537
  INFO root [0x00004a60] [2018-06-17 12:15:43,925] - 	componentID : 8001
  INFO root [0x00004a60] [2018-06-17 12:15:44,408] - Components::findLogger: found logger, addr:192.168.31.56:38529
  INFO root [0x00004a60] [2018-06-17 12:15:44,408] - Components::addComponent: reset orderLog, uid=7919!
  INFO root [0x00004a60] [2018-06-17 12:15:44,409] - Components::addComponent[logger], uid=7919, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00004a60] [2018-06-17 12:15:44,626] - ---- cellapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: D25B4E16028C33EB467B7BE2F3500426. Config: Debug X86. Built: 23:20:13 Jun 15 2018. AppID: 8001. UID: 7919. PID: 13472 ----
  INFO root [0x00004a60] [2018-06-17 12:15:44,627] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [0x00004a60] [2018-06-17 12:15:44,701] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00004a60] [2018-06-17 12:15:44,753] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00004a60] [2018-06-17 12:15:47,305] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00004a60] [2018-06-17 12:15:47,321] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00004a60] [2018-06-17 12:15:47,398] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00004a60] [2018-06-17 12:15:48,495] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00004a60] [2018-06-17 12:15:48,496] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00004a60] [2018-06-17 12:15:48,531] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00004a60] [2018-06-17 12:15:48,559] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00004a60] [2018-06-17 12:15:48,678] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00004a60] [2018-06-17 12:15:49,306] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:17:57) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00004a60] [2018-06-17 12:15:49,307] - Script::install(): KBExtra is successfully!
  INFO root [0x00004a60] [2018-06-17 12:15:49,932] - TelnetServer server is running on port 50000
  INFO root [0x00004a60] [2018-06-17 12:15:50,596] - ---- cellapp is running ----
 DEBUG root [0x00004a60] [2018-06-17 12:15:50,618] - Components::process(): Request for the process of identity...
  WARN root [0x00004a60] [2018-06-17 12:15:56,752] - Forwarding logs to logger[192.168.31.56:38529/0/0/0]...
 ERROR root [0x00004a60] [2018-06-17 12:18:18,888] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00004a60] [2018-06-17 12:18:18,894] - The following logs sent to logger failed:
  WARN root [0x00004a60] [2018-06-17 12:18:18,895] - ==> [2018-06-17 12:18:18 886] TCPPacketReceiver::processPendingEvents(192.168.31.56:38529): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00004a60] [2018-06-17 12:18:18,896] - ==> [2018-06-17 12:18:18 889] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00005104] [2018-06-17 12:21:29,007] - 
  INFO root [0x00005104] [2018-06-17 12:21:29,008] - -----------------------------------------------------------------------------------------


  INFO root [0x00005104] [2018-06-17 12:21:29,009] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [0x00005104] [2018-06-17 12:21:29,010] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [0x00005104] [2018-06-17 12:21:29,010] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [0x00005104] [2018-06-17 12:21:29,020] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:38588 )
  INFO root [0x00005104] [2018-06-17 12:21:29,020] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:38588, SOMAXCONN=5.
  INFO root [0x00005104] [2018-06-17 12:21:29,020] - server-configs:
  INFO root [0x00005104] [2018-06-17 12:21:29,020] - 	gameUpdateHertz : 10
  INFO root [0x00005104] [2018-06-17 12:21:29,021] - 	defaultAoIRadius : 80
  INFO root [0x00005104] [2018-06-17 12:21:29,021] - 	defaultAoIHysteresisArea : 5
  INFO root [0x00005104] [2018-06-17 12:21:29,021] - 	entryScriptFile : kbemain
  INFO root [0x00005104] [2018-06-17 12:21:29,021] - 	internalAddr : 192.168.31.56:38588
  INFO root [0x00005104] [2018-06-17 12:21:29,021] - 	componentID : 8001
  INFO root [0x00005104] [2018-06-17 12:21:30,532] - ---- cellapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: D25B4E16028C33EB467B7BE2F3500426. Config: Debug X86. Built: 23:20:13 Jun 15 2018. AppID: 8001. UID: 9218. PID: 12280 ----
  INFO root [0x00005104] [2018-06-17 12:21:30,533] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [0x00005104] [2018-06-17 12:21:30,533] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00005104] [2018-06-17 12:21:30,534] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00005104] [2018-06-17 12:21:30,683] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00005104] [2018-06-17 12:21:30,684] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00005104] [2018-06-17 12:21:30,685] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00005104] [2018-06-17 12:21:30,689] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00005104] [2018-06-17 12:21:30,690] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00005104] [2018-06-17 12:21:30,690] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00005104] [2018-06-17 12:21:30,691] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00005104] [2018-06-17 12:21:30,740] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00005104] [2018-06-17 12:21:30,792] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:17:57) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00005104] [2018-06-17 12:21:30,793] - Script::install(): KBExtra is successfully!
  INFO root [0x00005104] [2018-06-17 12:21:30,807] - TelnetServer server is running on port 50000
  INFO root [0x00005104] [2018-06-17 12:21:32,264] - ---- cellapp is running ----
 DEBUG root [0x00005104] [2018-06-17 12:21:32,266] - Components::process(): Request for the process of identity...
  WARN root [0x00005104] [2018-06-17 12:21:38,459] - EntityApp::checkTickPeriod: tick took 6194% (6.19 seconds)!
  INFO root [0x00005104] [2018-06-17 12:21:39,512] - Components::findComponents: find logger(1)...
  INFO root [0x00005104] [2018-06-17 12:21:39,562] - Components::findComponents: found logger, addr:192.168.31.56:38594
  INFO root [0x00005104] [2018-06-17 12:21:39,562] - Components::addComponent: reset orderLog, uid=9218!
  INFO root [0x00005104] [2018-06-17 12:21:39,563] - Components::addComponent[logger], uid=9218, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00005104] [2018-06-17 12:21:39,565] - Components::findComponents: find dbmgr(2)...
  WARN root [0x00005104] [2018-06-17 12:21:40,666] - Forwarding logs to logger[192.168.31.56:38594/0/0/0]...
 ERROR root [0x00005104] [2018-06-17 12:22:49,746] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00005104] [2018-06-17 12:22:49,754] - The following logs sent to logger failed:
  WARN root [0x00005104] [2018-06-17 12:22:49,755] - ==> [2018-06-17 12:22:49 746] TCPPacketReceiver::processPendingEvents(192.168.31.56:38594): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00005104] [2018-06-17 12:22:49,756] - ==> [2018-06-17 12:22:49 747] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00005488] [2018-06-17 12:28:39,282] - 
  INFO root [0x00005488] [2018-06-17 12:28:39,282] - -----------------------------------------------------------------------------------------


  INFO root [0x00005488] [2018-06-17 12:28:39,284] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [0x00005488] [2018-06-17 12:28:39,284] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [0x00005488] [2018-06-17 12:28:39,284] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [0x00005488] [2018-06-17 12:28:39,294] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:38697 )
  INFO root [0x00005488] [2018-06-17 12:28:39,295] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:38697, SOMAXCONN=5.
  INFO root [0x00005488] [2018-06-17 12:28:39,295] - server-configs:
  INFO root [0x00005488] [2018-06-17 12:28:39,295] - 	gameUpdateHertz : 10
  INFO root [0x00005488] [2018-06-17 12:28:39,296] - 	defaultAoIRadius : 80
  INFO root [0x00005488] [2018-06-17 12:28:39,296] - 	defaultAoIHysteresisArea : 5
  INFO root [0x00005488] [2018-06-17 12:28:39,296] - 	entryScriptFile : kbemain
  INFO root [0x00005488] [2018-06-17 12:28:39,296] - 	internalAddr : 192.168.31.56:38697
  INFO root [0x00005488] [2018-06-17 12:28:39,296] - 	componentID : 8001
  INFO root [0x00005488] [2018-06-17 12:28:40,810] - ---- cellapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: D25B4E16028C33EB467B7BE2F3500426. Config: Debug X86. Built: 23:20:13 Jun 15 2018. AppID: 8001. UID: 10623. PID: 15544 ----
  INFO root [0x00005488] [2018-06-17 12:28:40,812] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [0x00005488] [2018-06-17 12:28:40,812] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00005488] [2018-06-17 12:28:40,813] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00005488] [2018-06-17 12:28:40,959] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00005488] [2018-06-17 12:28:40,960] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00005488] [2018-06-17 12:28:40,961] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00005488] [2018-06-17 12:28:40,965] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00005488] [2018-06-17 12:28:40,966] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00005488] [2018-06-17 12:28:40,966] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00005488] [2018-06-17 12:28:40,967] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00005488] [2018-06-17 12:28:41,026] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00005488] [2018-06-17 12:28:41,078] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:17:57) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00005488] [2018-06-17 12:28:41,078] - Script::install(): KBExtra is successfully!
  INFO root [0x00005488] [2018-06-17 12:28:41,089] - TelnetServer server is running on port 50000
  INFO root [0x00005488] [2018-06-17 12:28:42,201] - ---- cellapp is running ----
 DEBUG root [0x00005488] [2018-06-17 12:28:42,203] - Components::process(): Request for the process of identity...
  WARN root [0x00005488] [2018-06-17 12:28:48,363] - EntityApp::checkTickPeriod: tick took 6161% (6.16 seconds)!
  INFO root [0x00005488] [2018-06-17 12:28:49,386] - Components::findComponents: find logger(1)...
  INFO root [0x00005488] [2018-06-17 12:28:49,460] - Components::findComponents: found logger, addr:192.168.31.56:38701
  INFO root [0x00005488] [2018-06-17 12:28:49,460] - Components::addComponent: reset orderLog, uid=10623!
  INFO root [0x00005488] [2018-06-17 12:28:49,460] - Components::addComponent[logger], uid=10623, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00005488] [2018-06-17 12:28:49,462] - Components::findComponents: find dbmgr(2)...
  WARN root [0x00005488] [2018-06-17 12:28:50,564] - Forwarding logs to logger[192.168.31.56:38701/0/0/0]...
 ERROR root [0x00005488] [2018-06-17 12:28:54,700] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00005488] [2018-06-17 12:28:54,703] - The following logs sent to logger failed:
  WARN root [0x00005488] [2018-06-17 12:28:54,704] - ==> [2018-06-17 12:28:54 700] TCPPacketReceiver::processPendingEvents(192.168.31.56:38701): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00005488] [2018-06-17 12:28:54,704] - ==> [2018-06-17 12:28:54 701] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x000030f0] [2018-06-17 12:29:01,267] - 
  INFO root [0x000030f0] [2018-06-17 12:29:01,271] - -----------------------------------------------------------------------------------------


  INFO root [0x000030f0] [2018-06-17 12:29:01,273] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [0x000030f0] [2018-06-17 12:29:01,274] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [0x000030f0] [2018-06-17 12:29:01,274] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [0x000030f0] [2018-06-17 12:29:01,337] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:38723 )
  INFO root [0x000030f0] [2018-06-17 12:29:01,338] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:38723, SOMAXCONN=5.
  INFO root [0x000030f0] [2018-06-17 12:29:01,338] - server-configs:
  INFO root [0x000030f0] [2018-06-17 12:29:01,338] - 	gameUpdateHertz : 10
  INFO root [0x000030f0] [2018-06-17 12:29:01,338] - 	defaultAoIRadius : 80
  INFO root [0x000030f0] [2018-06-17 12:29:01,339] - 	defaultAoIHysteresisArea : 5
  INFO root [0x000030f0] [2018-06-17 12:29:01,339] - 	entryScriptFile : kbemain
  INFO root [0x000030f0] [2018-06-17 12:29:01,339] - 	internalAddr : 192.168.31.56:38723
  INFO root [0x000030f0] [2018-06-17 12:29:01,340] - 	componentID : 8001
  INFO root [0x000030f0] [2018-06-17 12:29:02,854] - ---- cellapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: D25B4E16028C33EB467B7BE2F3500426. Config: Debug X86. Built: 23:20:13 Jun 15 2018. AppID: 8001. UID: 10694. PID: 15604 ----
  INFO root [0x000030f0] [2018-06-17 12:29:02,855] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [0x000030f0] [2018-06-17 12:29:02,856] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000030f0] [2018-06-17 12:29:02,856] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000030f0] [2018-06-17 12:29:03,067] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000030f0] [2018-06-17 12:29:03,069] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000030f0] [2018-06-17 12:29:03,070] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000030f0] [2018-06-17 12:29:03,076] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000030f0] [2018-06-17 12:29:03,077] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000030f0] [2018-06-17 12:29:03,078] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000030f0] [2018-06-17 12:29:03,079] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000030f0] [2018-06-17 12:29:03,200] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000030f0] [2018-06-17 12:29:03,288] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:17:57) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x000030f0] [2018-06-17 12:29:03,288] - Script::install(): KBExtra is successfully!
  INFO root [0x000030f0] [2018-06-17 12:29:03,342] - TelnetServer server is running on port 50000
  INFO root [0x000030f0] [2018-06-17 12:29:04,961] - ---- cellapp is running ----
 DEBUG root [0x000030f0] [2018-06-17 12:29:04,962] - Components::process(): Request for the process of identity...
  WARN root [0x000030f0] [2018-06-17 12:29:11,075] - EntityApp::checkTickPeriod: tick took 6114% (6.11 seconds)!
  INFO root [0x000030f0] [2018-06-17 12:29:12,161] - Components::findComponents: find logger(1)...
  INFO root [0x000030f0] [2018-06-17 12:29:12,246] - Components::findComponents: found logger, addr:192.168.31.56:38718
  INFO root [0x000030f0] [2018-06-17 12:29:12,247] - Components::addComponent: reset orderLog, uid=10694!
  INFO root [0x000030f0] [2018-06-17 12:29:12,247] - Components::addComponent[logger], uid=10694, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000030f0] [2018-06-17 12:29:12,249] - Components::findComponents: find dbmgr(2)...
  WARN root [0x000030f0] [2018-06-17 12:29:13,350] - EntityApp::checkTickPeriod: tick took 1289% (1.29 seconds)!
  WARN root [0x000030f0] [2018-06-17 12:29:13,351] - Forwarding logs to logger[192.168.31.56:38718/0/0/0]...
  INFO root [0x00003d9c] [2018-06-17 12:34:06,603] - 
  INFO root [0x00003d9c] [2018-06-17 12:34:06,606] - -----------------------------------------------------------------------------------------


  INFO root [0x00003d9c] [2018-06-17 12:34:06,608] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [0x00003d9c] [2018-06-17 12:34:06,609] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [0x00003d9c] [2018-06-17 12:34:06,610] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [0x00003d9c] [2018-06-17 12:34:06,647] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:38774 )
  INFO root [0x00003d9c] [2018-06-17 12:34:06,647] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:38774, SOMAXCONN=5.
  INFO root [0x00003d9c] [2018-06-17 12:34:06,647] - server-configs:
  INFO root [0x00003d9c] [2018-06-17 12:34:06,648] - 	gameUpdateHertz : 10
  INFO root [0x00003d9c] [2018-06-17 12:34:06,648] - 	defaultAoIRadius : 80
  INFO root [0x00003d9c] [2018-06-17 12:34:06,648] - 	defaultAoIHysteresisArea : 5
  INFO root [0x00003d9c] [2018-06-17 12:34:06,649] - 	entryScriptFile : kbemain
  INFO root [0x00003d9c] [2018-06-17 12:34:06,649] - 	internalAddr : 192.168.31.56:38774
  INFO root [0x00003d9c] [2018-06-17 12:34:06,649] - 	componentID : 8001
  INFO root [0x00003d9c] [2018-06-17 12:34:08,163] - ---- cellapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: D25B4E16028C33EB467B7BE2F3500426. Config: Debug X86. Built: 23:20:13 Jun 15 2018. AppID: 8001. UID: 11690. PID: 11124 ----
  INFO root [0x00003d9c] [2018-06-17 12:34:08,164] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [0x00003d9c] [2018-06-17 12:34:08,164] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003d9c] [2018-06-17 12:34:08,165] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00003d9c] [2018-06-17 12:34:08,341] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003d9c] [2018-06-17 12:34:08,342] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00003d9c] [2018-06-17 12:34:08,343] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00003d9c] [2018-06-17 12:34:08,350] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003d9c] [2018-06-17 12:34:08,351] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00003d9c] [2018-06-17 12:34:08,352] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003d9c] [2018-06-17 12:34:08,353] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003d9c] [2018-06-17 12:34:08,437] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00003d9c] [2018-06-17 12:34:08,526] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:17:57) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00003d9c] [2018-06-17 12:34:08,526] - Script::install(): KBExtra is successfully!
  INFO root [0x00003d9c] [2018-06-17 12:34:08,544] - TelnetServer server is running on port 50000
  INFO root [0x00003d9c] [2018-06-17 12:34:09,929] - ---- cellapp is running ----
 DEBUG root [0x00003d9c] [2018-06-17 12:34:09,931] - Components::process(): Request for the process of identity...
  WARN root [0x00003d9c] [2018-06-17 12:34:16,066] - EntityApp::checkTickPeriod: tick took 6136% (6.14 seconds)!
  INFO root [0x00003d9c] [2018-06-17 12:34:17,113] - Components::findComponents: find logger(1)...
  INFO root [0x00003d9c] [2018-06-17 12:34:17,180] - Components::findComponents: found logger, addr:192.168.31.56:38772
  INFO root [0x00003d9c] [2018-06-17 12:34:17,180] - Components::addComponent: reset orderLog, uid=11690!
  INFO root [0x00003d9c] [2018-06-17 12:34:17,181] - Components::addComponent[logger], uid=11690, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003d9c] [2018-06-17 12:34:17,182] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00003d9c] [2018-06-17 12:34:17,284] - Components::findComponents: found dbmgr, addr:192.168.31.56:38776
  INFO root [0x00003d9c] [2018-06-17 12:34:17,284] - Components::addComponent: reset orderLog, uid=11690!
  INFO root [0x00003d9c] [2018-06-17 12:34:17,284] - Components::addComponent[dbmgr], uid=11690, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003d9c] [2018-06-17 12:34:17,285] - Components::findComponents: found dbmgr, addr:192.168.31.56:38776
  WARN root [0x00003d9c] [2018-06-17 12:34:18,285] - Forwarding logs to logger[192.168.31.56:38772/0/0/0]...
 ERROR root [0x00003d9c] [2018-06-17 12:34:47,084] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00003d9c] [2018-06-17 12:34:47,085] - The following logs sent to logger failed:
  WARN root [0x00003d9c] [2018-06-17 12:34:47,086] - ==> [2018-06-17 12:34:47 083] TCPPacketReceiver::processPendingEvents(192.168.31.56:38772): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003d9c] [2018-06-17 12:34:47,087] - ==> [2018-06-17 12:34:47 085] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00003d9c] [2018-06-17 12:34:47,218] - TCPPacketReceiver::processPendingEvents(192.168.31.56:38776): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003d9c] [2018-06-17 12:34:47,227] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00003d9c] [2018-06-17 12:34:47,258] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [0x00003d9c] [2018-06-17 12:34:47,259] - Shutdowner::onShutdown: shutting down
  INFO root [0x00003d9c] [2018-06-17 12:34:47,260] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [0x00003d9c] [2018-06-17 12:34:47,261] - EntityRef::destroyObjPool(): size 0.
 DEBUG root [0x00003d9c] [2018-06-17 12:34:47,261] - Witness::destroyObjPool(): size 0.
 DEBUG root [0x00003d9c] [2018-06-17 12:34:47,295] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003d9c] [2018-06-17 12:34:47,296] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00003d9c] [2018-06-17 12:34:47,297] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00003d9c] [2018-06-17 12:34:47,297] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003d9c] [2018-06-17 12:34:47,298] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00003d9c] [2018-06-17 12:34:47,298] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003d9c] [2018-06-17 12:34:47,298] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003d9c] [2018-06-17 12:34:47,299] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00003d9c] [2018-06-17 12:34:47,320] - Script::uninstall(): is successfully!
 DEBUG root [0x00003d9c] [2018-06-17 12:34:47,320] - ThreadPool::destroy(): starting size 2.
  WARN root [0x00003d9c] [2018-06-17 12:34:47,620] - ThreadPool::destroy(): waiting for thread(2)[0x6f2110,0x6f20a8,], try=1
