  INFO root [2018-06-17 12:15:20,680] - 
  INFO root [2018-06-17 12:15:20,877] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-17 12:15:23,181] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-17 12:15:23,182] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-17 12:15:23,182] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-17 12:15:23,592] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:38532 )
  INFO root [2018-06-17 12:15:23,593] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:38532, SOMAXCONN=5.
  INFO root [2018-06-17 12:15:23,593] - server-configs:
  INFO root [2018-06-17 12:15:23,593] - 	internalAddr : 192.168.31.56:38532
  INFO root [2018-06-17 12:15:23,593] - 	componentID : 4000
  INFO root [2018-06-17 12:15:24,019] - ---- dbmgr Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: 253D45E587CB031BFD545E02866042FC. Config: Debug X86. Built: 23:15:53 Jun 15 2018. AppID: 4000. UID: 7919. PID: 23336 ----
  INFO root [2018-06-17 12:15:24,020] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-17 12:15:24,143] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-17 12:15:24,164] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-17 12:15:30,163] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-17 12:15:30,588] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-17 12:15:31,026] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-17 12:15:33,647] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-17 12:15:33,648] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-17 12:15:33,836] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-17 12:15:34,132] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-17 12:15:34,665] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-17 12:15:38,941] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:15:28) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-17 12:15:38,942] - Script::install(): KBExtra is successfully!
  INFO root [2018-06-17 12:15:40,057] - Dbmgr::initializeEnd: digest(363BB7D9C7C9010E5779213C13D38542)
S_INFO root [2018-06-17 12:15:40,152] - onDBMgrReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-17 12:15:40,263] - TelnetServer server is running on port 32000
  INFO root [2018-06-17 12:15:40,263] - Dbmgr::initInterfacesHandler: interfaces addr(127.0.0.1:30099), accountType:(interfaces), chargeType:(interfaces).
  WARN root [2018-06-17 12:15:41,307] - DBUtil::initialize: db(default) password is not encrypted!
please use password(rsa):
6F15759FA475B9D109FD9719D936ACC3AA5BAE46159C657645603322B36F33868207A649DDA360B201458EB81AA93F39C2C90D00DF501544BA8AB27E0C1022F05ADD4977FAB635D875085D338C7F9CD532289D109A28053F4505FA137D44B99947B9AB8B9235BED02A4FECDDBEA6805E783AE20AAE3B991FDC7A60F37A665601
 DEBUG root [2018-06-17 12:15:42,250] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 ERROR root [2018-06-17 12:15:44,376] - DBInterfaceMysql::attach: mysql_errno=1045, mysql_error=Access denied for user 'kbe'@'localhost' (using password: YES)
 ERROR root [2018-06-17 12:15:44,377] - DBUtil::createInterface: attach to database failed!
	dbinterface=0x3bedac
	args=interface=default, dbtype=mysql, ip=localhost, port=3306, currdatabase=kbe, username=kbe, connected=no.

 ERROR root [2018-06-17 12:15:44,379] - Dbmgr::initDB(): can't create dbInterface!
  WARN root [2018-06-17 12:15:44,414] - c:\users\public\documents\workspace\kbe\kbengine-kbengine-v1.0.0\kbengine\kbe\src\server\dbmgr\dbmgr.cpp:293: Profile scriptCall took 4.32 seconds
 ERROR root [2018-06-17 12:15:44,415] - app::initialize(): initialization failed!
 DEBUG root [2018-06-17 12:15:44,416] - ThreadPool::destroy(): starting size 0.
 DEBUG root [2018-06-17 12:15:44,816] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-06-17 12:15:44,816] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-17 12:15:44,816] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-17 12:15:44,817] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-17 12:15:44,817] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-17 12:15:44,817] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-17 12:15:44,817] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-17 12:15:44,817] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-17 12:15:44,817] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-17 12:15:44,830] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-17 12:15:44,830] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-17 12:15:45,130] - ThreadPool::destroy(): waiting for thread(2)[0x4fa218,0x4fa1b0,], try=1
 DEBUG root [2018-06-17 12:15:45,530] - TPThread::~TPThread(): 0x4fa218
 DEBUG root [2018-06-17 12:15:45,530] - TPThread::~TPThread(): 0x4fa1b0
 DEBUG root [2018-06-17 12:15:45,530] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-06-17 12:15:45,531] - Bundle::destroyObjPool(): size 14.
 DEBUG root [2018-06-17 12:15:45,531] - Channel::destroyObjPool(): size 15.
 DEBUG root [2018-06-17 12:15:45,531] - TCPPacket::destroyObjPool(): size 0.
 DEBUG root [2018-06-17 12:15:45,531] - UDPPacket::destroyObjPool(): size 14.
 DEBUG root [2018-06-17 12:15:45,532] - EndPoint::destroyObjPool(): size 15.
 DEBUG root [2018-06-17 12:15:45,532] - Address::destroyObjPool(): size 0.
 DEBUG root [2018-06-17 12:15:45,532] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2018-06-17 12:15:45,532] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2018-06-17 12:15:52,332] - EventDispatcher()::~EventDispatcher: Num timers = 1
  INFO root [2018-06-17 12:21:29,420] - 
  INFO root [2018-06-17 12:21:29,421] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-17 12:21:29,422] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-17 12:21:29,423] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-17 12:21:29,424] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-17 12:21:29,456] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:38595 )
  INFO root [2018-06-17 12:21:29,456] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:38595, SOMAXCONN=5.
  INFO root [2018-06-17 12:21:29,456] - server-configs:
  INFO root [2018-06-17 12:21:29,457] - 	internalAddr : 192.168.31.56:38595
  INFO root [2018-06-17 12:21:29,457] - 	componentID : 4000
  INFO root [2018-06-17 12:21:30,980] - ---- dbmgr Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: 253D45E587CB031BFD545E02866042FC. Config: Debug X86. Built: 23:15:53 Jun 15 2018. AppID: 4000. UID: 9218. PID: 11148 ----
  INFO root [2018-06-17 12:21:30,983] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-17 12:21:30,984] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-17 12:21:30,984] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-17 12:21:31,205] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-17 12:21:31,207] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-17 12:21:31,209] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-17 12:21:31,216] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-17 12:21:31,217] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-17 12:21:31,217] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-17 12:21:31,219] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-17 12:21:31,300] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-17 12:21:31,390] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:15:28) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-17 12:21:31,391] - Script::install(): KBExtra is successfully!
  INFO root [2018-06-17 12:21:31,406] - Dbmgr::initializeEnd: digest(363BB7D9C7C9010E5779213C13D38542)
S_INFO root [2018-06-17 12:21:31,406] - onDBMgrReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-17 12:21:31,407] - TelnetServer server is running on port 32000
  INFO root [2018-06-17 12:21:31,408] - Dbmgr::initInterfacesHandler: interfaces addr(127.0.0.1:30099), accountType:(interfaces), chargeType:(interfaces).
  WARN root [2018-06-17 12:21:32,225] - DBUtil::initialize: db(default) password is not encrypted!
please use password(rsa):
67B48F0C4007E0220CD5B0FCB39817C212F52EE4CC9DB9C70F96E09469B0FB8ED4F5719EB5D7368EED66C349521163BD89F607CACF4EC9DBD646C06576F9E06F8A001BC5BD0585845F8F1EB0BB10A8083408700D0ECD12AE06BF89EABBEA70F9D46C1F83CB3BB76AAB7F76627BC716A22BADFC85EEC6AFBD58F18112293D2912
 DEBUG root [2018-06-17 12:21:32,245] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 ERROR root [2018-06-17 12:21:32,285] - DBInterfaceMysql::attach: mysql_errno=1045, mysql_error=Access denied for user 'kbe'@'localhost' (using password: YES)
 ERROR root [2018-06-17 12:21:32,286] - DBUtil::createInterface: attach to database failed!
	dbinterface=0x194f240
	args=interface=default, dbtype=mysql, ip=localhost, port=3306, currdatabase=kbe, username=kbe, connected=no.

 ERROR root [2018-06-17 12:21:32,288] - Dbmgr::initDB(): can't create dbInterface!
  WARN root [2018-06-17 12:21:32,289] - c:\users\public\documents\workspace\kbe\kbengine-kbengine-v1.0.0\kbengine\kbe\src\server\dbmgr\dbmgr.cpp:293: Profile scriptCall took 0.88 seconds
 ERROR root [2018-06-17 12:21:32,289] - app::initialize(): initialization failed!
 DEBUG root [2018-06-17 12:21:32,290] - ThreadPool::destroy(): starting size 0.
 DEBUG root [2018-06-17 12:21:32,691] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-06-17 12:21:32,691] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-17 12:21:32,691] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-17 12:21:32,691] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-17 12:21:32,692] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-17 12:21:32,692] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-17 12:21:32,692] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-17 12:21:32,692] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-17 12:21:32,692] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-17 12:21:32,705] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-17 12:21:32,705] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-17 12:21:33,005] - ThreadPool::destroy(): waiting for thread(2)[0x1ca218,0x1ca1b0,], try=1
 DEBUG root [2018-06-17 12:21:33,406] - TPThread::~TPThread(): 0x1ca218
 DEBUG root [2018-06-17 12:21:33,406] - TPThread::~TPThread(): 0x1ca1b0
 DEBUG root [2018-06-17 12:21:33,406] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-06-17 12:21:33,407] - Bundle::destroyObjPool(): size 14.
 DEBUG root [2018-06-17 12:21:33,407] - Channel::destroyObjPool(): size 15.
 DEBUG root [2018-06-17 12:21:33,407] - TCPPacket::destroyObjPool(): size 0.
 DEBUG root [2018-06-17 12:21:33,407] - UDPPacket::destroyObjPool(): size 14.
 DEBUG root [2018-06-17 12:21:33,408] - EndPoint::destroyObjPool(): size 15.
 DEBUG root [2018-06-17 12:21:33,408] - Address::destroyObjPool(): size 0.
 DEBUG root [2018-06-17 12:21:33,408] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2018-06-17 12:21:33,408] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2018-06-17 12:21:40,208] - EventDispatcher()::~EventDispatcher: Num timers = 1
  INFO root [2018-06-17 12:28:39,623] - 
  INFO root [2018-06-17 12:28:39,624] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-17 12:28:39,626] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-17 12:28:39,627] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-17 12:28:39,628] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-17 12:28:39,640] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:38705 )
  INFO root [2018-06-17 12:28:39,641] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:38705, SOMAXCONN=5.
  INFO root [2018-06-17 12:28:39,641] - server-configs:
  INFO root [2018-06-17 12:28:39,641] - 	internalAddr : 192.168.31.56:38705
  INFO root [2018-06-17 12:28:39,642] - 	componentID : 4000
  INFO root [2018-06-17 12:28:41,155] - ---- dbmgr Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: 253D45E587CB031BFD545E02866042FC. Config: Debug X86. Built: 23:15:53 Jun 15 2018. AppID: 4000. UID: 10623. PID: 16764 ----
  INFO root [2018-06-17 12:28:41,157] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-17 12:28:41,157] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-17 12:28:41,158] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-17 12:28:41,323] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-17 12:28:41,324] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-17 12:28:41,324] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-17 12:28:41,329] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-17 12:28:41,329] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-17 12:28:41,330] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-17 12:28:41,331] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-17 12:28:41,405] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-17 12:28:41,467] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:15:28) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-17 12:28:41,467] - Script::install(): KBExtra is successfully!
  INFO root [2018-06-17 12:28:41,478] - Dbmgr::initializeEnd: digest(363BB7D9C7C9010E5779213C13D38542)
S_INFO root [2018-06-17 12:28:41,479] - onDBMgrReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-17 12:28:41,480] - TelnetServer server is running on port 32000
  INFO root [2018-06-17 12:28:41,481] - Dbmgr::initInterfacesHandler: interfaces addr(127.0.0.1:30099), accountType:(interfaces), chargeType:(interfaces).
  WARN root [2018-06-17 12:28:42,270] - DBUtil::initialize: db(default) password is not encrypted!
please use password(rsa):
16F3483332F37A6ADE97D109327865C98EDEC6335A9DDA4C8B8B99E4AFB7970856959E9CACE9A3301FD9F6551ADB1FABF54EF61616FF5AE7B4A59EF875266E0E8FC37AE64B628F221A7B87F25F983486B5842C94F8ACDBE6A5A4DF51618DB1FAC6B592BD48204FCE57263412E3B3CF7569F432E49CD5FFE5B6D1C47019925AD0
 DEBUG root [2018-06-17 12:28:42,292] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 ERROR root [2018-06-17 12:28:42,313] - DBInterfaceMysql::attach: mysql_errno=1045, mysql_error=Access denied for user 'kbe'@'localhost' (using password: YES)
 ERROR root [2018-06-17 12:28:42,316] - DBUtil::createInterface: attach to database failed!
	dbinterface=0x39f2a0
	args=interface=default, dbtype=mysql, ip=localhost, port=3306, currdatabase=kbe1, username=kbe, connected=no.

 ERROR root [2018-06-17 12:28:42,319] - Dbmgr::initDB(): can't create dbInterface!
  WARN root [2018-06-17 12:28:42,321] - c:\users\public\documents\workspace\kbe\kbengine-kbengine-v1.0.0\kbengine\kbe\src\server\dbmgr\dbmgr.cpp:293: Profile scriptCall took 0.84 seconds
 ERROR root [2018-06-17 12:28:42,322] - app::initialize(): initialization failed!
 DEBUG root [2018-06-17 12:28:42,323] - ThreadPool::destroy(): starting size 0.
 DEBUG root [2018-06-17 12:28:42,724] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-06-17 12:28:42,725] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-17 12:28:42,727] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-17 12:28:42,727] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-17 12:28:42,727] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-17 12:28:42,728] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-17 12:28:42,728] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-17 12:28:42,728] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-17 12:28:42,729] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-17 12:28:42,747] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-17 12:28:42,747] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-17 12:28:43,048] - ThreadPool::destroy(): waiting for thread(2)[0x85a290,0x85a228,], try=1
 DEBUG root [2018-06-17 12:28:43,448] - TPThread::~TPThread(): 0x85a290
 DEBUG root [2018-06-17 12:28:43,448] - TPThread::~TPThread(): 0x85a228
 DEBUG root [2018-06-17 12:28:43,448] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-06-17 12:28:43,449] - Bundle::destroyObjPool(): size 14.
 DEBUG root [2018-06-17 12:28:43,449] - Channel::destroyObjPool(): size 15.
 DEBUG root [2018-06-17 12:28:43,449] - TCPPacket::destroyObjPool(): size 0.
 DEBUG root [2018-06-17 12:28:43,450] - UDPPacket::destroyObjPool(): size 14.
 DEBUG root [2018-06-17 12:28:43,450] - EndPoint::destroyObjPool(): size 15.
 DEBUG root [2018-06-17 12:28:43,450] - Address::destroyObjPool(): size 0.
 DEBUG root [2018-06-17 12:28:43,450] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2018-06-17 12:28:43,450] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2018-06-17 12:28:50,250] - EventDispatcher()::~EventDispatcher: Num timers = 1
  INFO root [2018-06-17 12:29:01,185] - 
  INFO root [2018-06-17 12:29:01,187] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-17 12:29:01,189] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-17 12:29:01,191] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-17 12:29:01,193] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-17 12:29:01,240] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:38722 )
  INFO root [2018-06-17 12:29:01,241] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:38722, SOMAXCONN=5.
  INFO root [2018-06-17 12:29:01,241] - server-configs:
  INFO root [2018-06-17 12:29:01,241] - 	internalAddr : 192.168.31.56:38722
  INFO root [2018-06-17 12:29:01,241] - 	componentID : 4000
  INFO root [2018-06-17 12:29:02,752] - ---- dbmgr Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: 253D45E587CB031BFD545E02866042FC. Config: Debug X86. Built: 23:15:53 Jun 15 2018. AppID: 4000. UID: 10694. PID: 12020 ----
  INFO root [2018-06-17 12:29:02,753] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-17 12:29:02,753] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-17 12:29:02,753] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-17 12:29:02,932] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-17 12:29:02,933] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-17 12:29:02,934] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-17 12:29:02,941] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-17 12:29:02,942] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-17 12:29:02,942] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-17 12:29:02,944] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-17 12:29:03,299] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-17 12:29:03,424] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:15:28) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-17 12:29:03,424] - Script::install(): KBExtra is successfully!
  INFO root [2018-06-17 12:29:03,436] - Dbmgr::initializeEnd: digest(363BB7D9C7C9010E5779213C13D38542)
S_INFO root [2018-06-17 12:29:03,436] - onDBMgrReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-17 12:29:03,438] - TelnetServer server is running on port 32000
  INFO root [2018-06-17 12:29:03,438] - Dbmgr::initInterfacesHandler: interfaces addr(127.0.0.1:30099), accountType:(interfaces), chargeType:(interfaces).
  WARN root [2018-06-17 12:29:04,545] - DBUtil::initialize: db(default) password is not encrypted!
please use password(rsa):
246C074C5DFD920AC64593900F2C80153FF23CE4DE0BA6FC4A9FDCBC0F13D96988D25111EE61DA506CF2CFC46438E88E8FB47761BF985889A90C6829134234837EDF7EEB406107E312EA0115B655B84759F1F67E23882282E8AA90942FDC4EB3A834D59E4E33E3A2020419B2E3EDFC7ACABFB0BF3D9C8A368FC4F8741B8E44C4
 DEBUG root [2018-06-17 12:29:04,550] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 ERROR root [2018-06-17 12:29:04,561] - DBInterfaceMysql::attach: mysql_errno=1045, mysql_error=Access denied for user 'kbe'@'localhost' (using password: YES)
 ERROR root [2018-06-17 12:29:04,563] - DBUtil::createInterface: attach to database failed!
	dbinterface=0x187ee90
	args=interface=default, dbtype=mysql, ip=localhost, port=3306, currdatabase=kbe1, username=kbe, connected=no.

 ERROR root [2018-06-17 12:29:04,565] - Dbmgr::initDB(): can't create dbInterface!
  WARN root [2018-06-17 12:29:04,567] - c:\users\public\documents\workspace\kbe\kbengine-kbengine-v1.0.0\kbengine\kbe\src\server\dbmgr\dbmgr.cpp:293: Profile scriptCall took 1.13 seconds
 ERROR root [2018-06-17 12:29:04,568] - app::initialize(): initialization failed!
 DEBUG root [2018-06-17 12:29:04,569] - ThreadPool::destroy(): starting size 0.
 DEBUG root [2018-06-17 12:29:04,969] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-06-17 12:29:04,969] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-17 12:29:04,969] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-17 12:29:04,969] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-17 12:29:04,970] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-17 12:29:04,970] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-17 12:29:04,970] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-17 12:29:04,970] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-17 12:29:04,970] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-17 12:29:04,985] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-17 12:29:04,986] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-17 12:29:05,286] - ThreadPool::destroy(): waiting for thread(2)[0x1bba290,0x1bba228,], try=1
 DEBUG root [2018-06-17 12:29:05,687] - TPThread::~TPThread(): 0x1bba290
 DEBUG root [2018-06-17 12:29:05,687] - TPThread::~TPThread(): 0x1bba228
 DEBUG root [2018-06-17 12:29:05,688] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-06-17 12:29:05,688] - Bundle::destroyObjPool(): size 14.
 DEBUG root [2018-06-17 12:29:05,689] - Channel::destroyObjPool(): size 15.
 DEBUG root [2018-06-17 12:29:05,689] - TCPPacket::destroyObjPool(): size 0.
 DEBUG root [2018-06-17 12:29:05,689] - UDPPacket::destroyObjPool(): size 14.
 DEBUG root [2018-06-17 12:29:05,690] - EndPoint::destroyObjPool(): size 15.
 DEBUG root [2018-06-17 12:29:05,690] - Address::destroyObjPool(): size 0.
 DEBUG root [2018-06-17 12:29:05,690] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2018-06-17 12:29:05,690] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2018-06-17 12:29:12,490] - EventDispatcher()::~EventDispatcher: Num timers = 1
  INFO root [2018-06-17 12:34:06,716] - 
  INFO root [2018-06-17 12:34:06,717] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-17 12:34:06,719] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-17 12:34:06,720] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-17 12:34:06,720] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-17 12:34:06,764] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:38776 )
  INFO root [2018-06-17 12:34:06,764] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:38776, SOMAXCONN=5.
  INFO root [2018-06-17 12:34:06,765] - server-configs:
  INFO root [2018-06-17 12:34:06,765] - 	internalAddr : 192.168.31.56:38776
  INFO root [2018-06-17 12:34:06,765] - 	componentID : 4000
  INFO root [2018-06-17 12:34:08,303] - ---- dbmgr Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: 253D45E587CB031BFD545E02866042FC. Config: Debug X86. Built: 23:15:53 Jun 15 2018. AppID: 4000. UID: 11690. PID: 21892 ----
  INFO root [2018-06-17 12:34:08,308] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-17 12:34:08,308] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-17 12:34:08,309] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-17 12:34:08,492] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-17 12:34:08,493] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-17 12:34:08,494] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-17 12:34:08,501] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-17 12:34:08,502] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-17 12:34:08,503] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-17 12:34:08,505] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-17 12:34:08,589] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-17 12:34:08,675] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:15:28) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-17 12:34:08,676] - Script::install(): KBExtra is successfully!
  INFO root [2018-06-17 12:34:08,687] - Dbmgr::initializeEnd: digest(363BB7D9C7C9010E5779213C13D38542)
S_INFO root [2018-06-17 12:34:08,687] - onDBMgrReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-17 12:34:08,689] - TelnetServer server is running on port 32000
  INFO root [2018-06-17 12:34:08,690] - Dbmgr::initInterfacesHandler: interfaces addr(127.0.0.1:30099), accountType:(interfaces), chargeType:(interfaces).
  WARN root [2018-06-17 12:34:09,575] - DBUtil::initialize: db(default) password is not encrypted!
please use password(rsa):
719DCEF3679A17285D7E6BF0A94D0562D7114D85145DFC4A9FEA5906CF2E0E5C620E09419C21FEFEDF13109564E94A0ED59B8274DBB374FD15C7E01405E5011D892669E15CEDB0895401CEB2E715C27E166E9CEDBA2E43F8E236CF65FCBBDB1C0F38375691B111E8FD6592751E7FD4A8804DBF15A583DD00B5BB4EE94E063312
 DEBUG root [2018-06-17 12:34:09,581] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2018-06-17 12:34:09,591] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
  INFO root [2018-06-17 12:34:09,592] - DBUtil::createInterface[0x24ef90]: interface=default, dbtype=mysql, ip=localhost, port=3306, currdatabase=kbe1, username=kbe, connected=yes.

  INFO root [2018-06-17 12:34:09,593] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-17 12:34:09,593] - ThreadPool::createThreadPool: successfully(5), newThreadCount=5, normalMaxThreadCount=5, maxThreadCount=5
 DEBUG root [2018-06-17 12:34:09,594] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2018-06-17 12:34:09,597] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2018-06-17 12:34:09,598] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2018-06-17 12:34:09,598] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2018-06-17 12:34:09,603] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2018-06-17 12:34:09,604] - DBThread::onStart(): 0x5f7248!
 DEBUG root [2018-06-17 12:34:09,605] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2018-06-17 12:34:09,606] - DBThread::onStart(): 0x5f73e0!
 DEBUG root [2018-06-17 12:34:09,608] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2018-06-17 12:34:09,612] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2018-06-17 12:34:09,612] - DBThread::onStart(): 0x5f7468!
 DEBUG root [2018-06-17 12:34:09,616] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2018-06-17 12:34:09,617] - DBThread::onStart(): 0x5f7358!
 DEBUG root [2018-06-17 12:34:09,619] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2018-06-17 12:34:09,619] - DBThread::onStart(): 0x5f72d0!
  INFO root [2018-06-17 12:34:09,698] - DBInterfaceMysql::query: successfully!
  INFO root [2018-06-17 12:34:09,709] - DBInterfaceMysql::query: successfully!
  WARN root [2018-06-17 12:34:09,710] - DBInterfaceRedis::checkErrors: not found Account table, reset kbe_* table...
  WARN root [2018-06-17 12:34:09,712] - DBInterfaceRedis::checkErrors: reset kbe_* table end!
  INFO root [2018-06-17 12:34:10,882] - DBInterfaceMysql::query: successfully!
  INFO root [2018-06-17 12:34:11,271] - DBInterfaceMysql::query: successfully!
  INFO root [2018-06-17 12:34:11,443] - DBInterfaceMysql::query: successfully!
  INFO root [2018-06-17 12:34:11,444] - DBInterfaceMysql::query: successfully!
  WARN root [2018-06-17 12:34:11,444] - DBTask::process(): took 1.73 seconds
sql:(CREATE TABLE IF NOT EXISTS kbe_accountinfos (`accountName` varchar(128) not null, PRIMARY KEY idKey (`accountName`),`password` varchar(255),`bindata` blob,`email` varchar(255) not null, UNIQUE KEY `email` (`email`),`entityDBID` bigint(20) unsigned not null DEFAULT 0, UNIQUE KEY `entityDBID` (`entityDBID`),`flags` int unsigned not null DEFAULT 0,`deadline` bigint(20) not null DEFAULT 0,`regtime` bigint(20) not null DEFAULT 0,`lasttime` bigint(20) not null DEFAULT 0,`numlogin` int unsigned not null DEFAULT 0)ENGINE=InnoDB)
  INFO root [2018-06-17 12:34:11,590] - DBInterfaceMysql::query: successfully!
  WARN root [2018-06-17 12:34:11,591] - DBTask::process(): took 1.88 seconds
sql:(delete from kbe_entitylog where logger in (4000))
  INFO root [2018-06-17 12:34:11,592] - DBInterfaceMysql::query: successfully!
  INFO root [2018-06-17 12:34:11,593] - DBInterfaceMysql::query: successfully!
  INFO root [2018-06-17 12:34:11,593] - DBInterfaceMysql::query: successfully!
  WARN root [2018-06-17 12:34:11,593] - DBTask::process(): took 1.88 seconds
sql:(delete from kbe_email_verification where logtime<1529206451 and type=3)
  WARN root [2018-06-17 12:34:11,632] - DBTask::process(): took 1.92 seconds
sql:(insert into kbe_serverlog (heartbeatTime, logger) values(1529210051,4000) ON DUPLICATE KEY UPDATE heartbeatTime=1529210051)
 DEBUG root [2018-06-17 12:34:11,700] - syncToDB(): Account->sm_autoLoad(tinyint not null DEFAULT 0).
  INFO root [2018-06-17 12:34:12,430] - DBInterfaceMysql::query: successfully!
  WARN root [2018-06-17 12:34:12,432] - DBTask::process(): took 2.72 seconds
sql:(show index from tbl_Account)
  WARN root [2018-06-17 12:34:12,453] - c:\users\public\documents\workspace\kbe\kbengine-kbengine-v1.0.0\kbengine\kbe\src\server\dbmgr\dbmgr.cpp:293: Profile scriptCall took 3.77 seconds
  INFO root [2018-06-17 12:34:12,942] - ---- dbmgr is running ----
 DEBUG root [2018-06-17 12:34:12,943] - Components::process(): Request for the process of identity...
  INFO root [2018-06-17 12:34:19,848] - ServerApp::onRegisterNewApp: uid:11690, username:, componentType:loginapp, componentID:9000, globalorderID=-1, grouporderID=-1, intaddr:192.168.31.56, intport:38775, extaddr:192.168.31.56, extport:20013,  from 192.168.31.56:38789/0/0/0.
  INFO root [2018-06-17 12:34:19,849] - Components::addComponent: reset orderLog, uid=11690!
  INFO root [2018-06-17 12:34:19,849] - Components::addComponent[loginapp], uid=11690, componentID=9000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-17 12:34:20,068] - Components::findComponents: find logger(1)...
  INFO root [2018-06-17 12:34:20,118] - Components::findComponents: found logger, addr:192.168.31.56:38772
  INFO root [2018-06-17 12:34:20,118] - Components::addComponent[logger], uid=11690, componentID=2000, globalorderid=2, grouporderid=1, totalcount=1
  WARN root [2018-06-17 12:34:20,122] - Forwarding logs to logger[192.168.31.56:38772/0/0/0]...
 ERROR root [2018-06-17 12:34:47,085] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-17 12:34:47,087] - The following logs sent to logger failed:
  WARN root [2018-06-17 12:34:47,087] - ==> [2018-06-17 12:34:47 083] TCPPacketReceiver::processPendingEvents(192.168.31.56:38772): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-17 12:34:47,088] - ==> [2018-06-17 12:34:47 085] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
