  INFO root [2018-06-27 16:44:54,714] - 
  INFO root [2018-06-27 16:44:54,741] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-27 16:44:56,557] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-27 16:44:56,558] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-27 16:44:56,558] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-27 16:44:57,123] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-27 16:44:57,165] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-27 16:44:57,168] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:39635 )
  INFO root [2018-06-27 16:44:57,168] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:39635, SOMAXCONN=128.
  INFO root [2018-06-27 16:44:57,216] - server-configs:
  INFO root [2018-06-27 16:44:57,216] - 	internalAddr : 192.168.31.56:39635
  INFO root [2018-06-27 16:44:57,216] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-27 16:44:57,216] - 	componentID : 9000
  INFO root [2018-06-27 16:44:58,312] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 31416. PID: 8756 ----
  INFO root [2018-06-27 16:44:58,313] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-27 16:44:58,373] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-27 16:44:58,466] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-27 16:45:05,475] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 16:45:05,605] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 16:45:05,759] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 16:45:07,115] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 16:45:07,188] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 16:45:07,348] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 16:45:07,525] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 16:45:08,296] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 16:45:10,633] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-27 16:45:10,634] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-27 16:45:10,787] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-27 16:45:10,800] - TelnetServer server is running on port 31000
  INFO root [2018-06-27 16:45:11,676] - ---- loginapp is running ----
 DEBUG root [2018-06-27 16:45:11,694] - Components::process(): Request for the process of identity...
  INFO root [2018-06-27 16:45:18,961] - Components::findComponents: find logger(1)...
  INFO root [2018-06-27 16:45:19,021] - Components::findComponents: found logger, addr:192.168.31.56:39629
  INFO root [2018-06-27 16:45:19,022] - Components::addComponent: reset orderLog, uid=31416!
  INFO root [2018-06-27 16:45:19,023] - Components::addComponent[logger], uid=31416, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 16:45:19,102] - Components::findComponents: find dbmgr(2)...
  WARN root [2018-06-27 16:45:20,131] - Forwarding logs to logger[192.168.31.56:39629/0/0/0]...
 ERROR root [2018-06-27 16:45:34,476] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 16:45:34,478] - The following logs sent to logger failed:
  WARN root [2018-06-27 16:45:34,487] - ==> [2018-06-27 16:45:34 465] TCPPacketReceiver::processPendingEvents(192.168.31.56:39629): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 16:45:34,487] - ==> [2018-06-27 16:45:34 477] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 16:45:50,798] - 
  INFO root [2018-06-27 16:45:50,799] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-27 16:45:50,800] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-27 16:45:50,800] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-27 16:45:50,800] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-27 16:45:50,811] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-27 16:45:50,811] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-27 16:45:50,814] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:39695 )
  INFO root [2018-06-27 16:45:50,814] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:39695, SOMAXCONN=128.
  INFO root [2018-06-27 16:45:50,814] - server-configs:
  INFO root [2018-06-27 16:45:50,814] - 	internalAddr : 192.168.31.56:39695
  INFO root [2018-06-27 16:45:50,815] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-27 16:45:50,815] - 	componentID : 9000
  INFO root [2018-06-27 16:45:52,996] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 31661. PID: 10696 ----
  INFO root [2018-06-27 16:45:52,997] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-27 16:45:52,998] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-27 16:45:52,998] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-27 16:45:53,152] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 16:45:53,154] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 16:45:53,155] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 16:45:53,160] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 16:45:53,160] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 16:45:53,161] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 16:45:53,161] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 16:45:53,236] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 16:45:53,308] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-27 16:45:53,308] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-27 16:45:53,312] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-27 16:45:53,313] - TelnetServer server is running on port 31000
  INFO root [2018-06-27 16:45:53,940] - ---- loginapp is running ----
 DEBUG root [2018-06-27 16:45:53,941] - Components::process(): Request for the process of identity...
  INFO root [2018-06-27 16:46:01,093] - Components::findComponents: find logger(1)...
  INFO root [2018-06-27 16:46:01,186] - Components::findComponents: found logger, addr:192.168.31.56:39703
  INFO root [2018-06-27 16:46:01,186] - Components::addComponent: reset orderLog, uid=31661!
  INFO root [2018-06-27 16:46:01,186] - Components::addComponent[logger], uid=31661, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 16:46:01,188] - Components::findComponents: find dbmgr(2)...
  WARN root [2018-06-27 16:46:02,290] - Forwarding logs to logger[192.168.31.56:39703/0/0/0]...
 ERROR root [2018-06-27 16:46:19,448] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 16:46:19,454] - The following logs sent to logger failed:
  WARN root [2018-06-27 16:46:19,456] - ==> [2018-06-27 16:46:19 445] TCPPacketReceiver::processPendingEvents(192.168.31.56:39703): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 16:46:19,456] - ==> [2018-06-27 16:46:19 448] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 16:46:19,674] - Components::findComponents: find dbmgr(11)...
  INFO root [2018-06-27 16:55:16,314] - 
  INFO root [2018-06-27 16:55:16,315] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-27 16:55:16,316] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-27 16:55:16,316] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-27 16:55:16,317] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-27 16:55:16,326] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-27 16:55:16,327] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-27 16:55:16,330] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:40084 )
  INFO root [2018-06-27 16:55:16,331] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:40084, SOMAXCONN=128.
  INFO root [2018-06-27 16:55:16,331] - server-configs:
  INFO root [2018-06-27 16:55:16,331] - 	internalAddr : 192.168.31.56:40084
  INFO root [2018-06-27 16:55:16,331] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-27 16:55:16,331] - 	componentID : 9000
  INFO root [2018-06-27 16:55:18,368] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 738. PID: 11144 ----
  INFO root [2018-06-27 16:55:18,369] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-27 16:55:18,369] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-27 16:55:18,371] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-27 16:55:18,554] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 16:55:18,556] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 16:55:18,557] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 16:55:18,570] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 16:55:18,571] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 16:55:18,571] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 16:55:18,573] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 16:55:18,669] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 16:55:18,730] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-27 16:55:18,730] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-27 16:55:18,734] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-27 16:55:18,735] - TelnetServer server is running on port 31000
  INFO root [2018-06-27 16:55:19,400] - ---- loginapp is running ----
 DEBUG root [2018-06-27 16:55:19,401] - Components::process(): Request for the process of identity...
  INFO root [2018-06-27 16:55:26,520] - Components::findComponents: find logger(1)...
  INFO root [2018-06-27 16:55:26,594] - Components::findComponents: found logger, addr:192.168.31.56:40092
  INFO root [2018-06-27 16:55:26,594] - Components::addComponent: reset orderLog, uid=738!
  INFO root [2018-06-27 16:55:26,594] - Components::addComponent[logger], uid=738, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 16:55:26,596] - Components::findComponents: find dbmgr(2)...
  WARN root [2018-06-27 16:55:27,698] - Forwarding logs to logger[192.168.31.56:40092/0/0/0]...
 ERROR root [2018-06-27 16:55:54,420] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 16:55:54,422] - The following logs sent to logger failed:
  WARN root [2018-06-27 16:55:54,423] - ==> [2018-06-27 16:55:54 419] TCPPacketReceiver::processPendingEvents(192.168.31.56:40092): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 16:55:54,423] - ==> [2018-06-27 16:55:54 420] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 17:01:41,838] - 
  INFO root [2018-06-27 17:01:41,840] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-27 17:01:41,841] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-27 17:01:41,842] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-27 17:01:41,843] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-27 17:01:41,856] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-27 17:01:41,856] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-27 17:01:41,862] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:40336 )
  INFO root [2018-06-27 17:01:41,863] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:40336, SOMAXCONN=128.
  INFO root [2018-06-27 17:01:41,863] - server-configs:
  INFO root [2018-06-27 17:01:41,864] - 	internalAddr : 192.168.31.56:40336
  INFO root [2018-06-27 17:01:41,864] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-27 17:01:41,864] - 	componentID : 9000
  INFO root [2018-06-27 17:01:43,896] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 1996. PID: 10760 ----
  INFO root [2018-06-27 17:01:43,897] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-27 17:01:43,898] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-27 17:01:43,898] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-27 17:01:44,039] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 17:01:44,040] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 17:01:44,041] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 17:01:44,045] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 17:01:44,046] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 17:01:44,046] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 17:01:44,047] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 17:01:44,097] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 17:01:44,147] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-27 17:01:44,147] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-27 17:01:44,151] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-27 17:01:44,152] - TelnetServer server is running on port 31000
  INFO root [2018-06-27 17:01:44,635] - ---- loginapp is running ----
 DEBUG root [2018-06-27 17:01:44,636] - Components::process(): Request for the process of identity...
  INFO root [2018-06-27 17:01:51,752] - Components::findComponents: find logger(1)...
  INFO root [2018-06-27 17:01:51,834] - Components::findComponents: found logger, addr:192.168.31.56:40334
  INFO root [2018-06-27 17:01:51,834] - Components::addComponent: reset orderLog, uid=1996!
  INFO root [2018-06-27 17:01:51,835] - Components::addComponent[logger], uid=1996, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 17:01:51,840] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-27 17:01:51,844] - Components::findComponents: found logger, addr:192.168.31.56:40334
  WARN root [2018-06-27 17:01:52,947] - Forwarding logs to logger[192.168.31.56:40334/0/0/0]...
 ERROR root [2018-06-27 17:02:15,599] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 17:02:15,604] - The following logs sent to logger failed:
  WARN root [2018-06-27 17:02:15,604] - ==> [2018-06-27 17:02:15 598] TCPPacketReceiver::processPendingEvents(192.168.31.56:40334): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 17:02:15,604] - ==> [2018-06-27 17:02:15 599] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 17:03:32,481] - 
  INFO root [2018-06-27 17:03:32,482] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-27 17:03:32,484] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-27 17:03:32,485] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-27 17:03:32,485] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-27 17:03:32,508] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-27 17:03:32,508] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-27 17:03:32,513] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:40408 )
  INFO root [2018-06-27 17:03:32,514] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:40408, SOMAXCONN=128.
  INFO root [2018-06-27 17:03:32,514] - server-configs:
  INFO root [2018-06-27 17:03:32,514] - 	internalAddr : 192.168.31.56:40408
  INFO root [2018-06-27 17:03:32,515] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-27 17:03:32,515] - 	componentID : 9000
  INFO root [2018-06-27 17:03:34,584] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 2358. PID: 7008 ----
  INFO root [2018-06-27 17:03:34,585] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-27 17:03:34,586] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-27 17:03:34,587] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-27 17:03:34,778] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 17:03:34,780] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 17:03:34,781] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 17:03:34,788] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 17:03:34,789] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 17:03:34,789] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 17:03:34,791] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 17:03:34,927] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 17:03:35,052] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-27 17:03:35,053] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-27 17:03:35,058] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-27 17:03:35,060] - TelnetServer server is running on port 31000
  INFO root [2018-06-27 17:03:35,806] - ---- loginapp is running ----
 DEBUG root [2018-06-27 17:03:35,807] - Components::process(): Request for the process of identity...
  INFO root [2018-06-27 17:03:42,958] - Components::findComponents: find logger(1)...
  INFO root [2018-06-27 17:03:43,052] - Components::findComponents: found logger, addr:192.168.31.56:40403
  INFO root [2018-06-27 17:03:43,053] - Components::addComponent: reset orderLog, uid=2358!
  INFO root [2018-06-27 17:03:43,053] - Components::addComponent[logger], uid=2358, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 17:03:43,061] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-27 17:03:43,167] - Components::findComponents: found dbmgr, addr:192.168.31.56:40405
  INFO root [2018-06-27 17:03:43,167] - Components::addComponent: reset orderLog, uid=2358!
  INFO root [2018-06-27 17:03:43,167] - Components::addComponent[dbmgr], uid=2358, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 17:03:43,168] - Components::findComponents: found dbmgr, addr:192.168.31.56:40405
  WARN root [2018-06-27 17:03:44,168] - Forwarding logs to logger[192.168.31.56:40403/0/0/0]...
 ERROR root [2018-06-27 17:04:04,024] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 17:04:04,043] - The following logs sent to logger failed:
  WARN root [2018-06-27 17:04:04,044] - ==> [2018-06-27 17:04:04 022] TCPPacketReceiver::processPendingEvents(192.168.31.56:40403): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 17:04:04,044] - ==> [2018-06-27 17:04:04 025] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-27 17:04:04,159] - TCPPacketReceiver::processPendingEvents(192.168.31.56:40405): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 17:04:04,164] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 17:04:04,186] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-27 17:04:04,187] - onLoginAppShutDown()
  INFO root [2018-06-27 17:04:04,187] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-27 17:04:04,187] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-27 17:04:04,188] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 17:04:04,188] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 17:04:04,188] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 17:04:04,188] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 17:04:04,189] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 17:04:04,189] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 17:04:04,189] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 17:04:04,189] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 17:04:04,206] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-27 17:04:04,206] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-27 17:04:04,506] - ThreadPool::destroy(): waiting for thread(2)[0x48de08,0x48dda0,], try=1
  INFO root [2018-06-27 17:07:17,821] - 
  INFO root [2018-06-27 17:07:17,832] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-27 17:07:17,835] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-27 17:07:17,836] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-27 17:07:17,836] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-27 17:07:17,923] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-27 17:07:17,923] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-27 17:07:17,940] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:40562 )
  INFO root [2018-06-27 17:07:17,941] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:40562, SOMAXCONN=128.
  INFO root [2018-06-27 17:07:17,941] - server-configs:
  INFO root [2018-06-27 17:07:17,941] - 	internalAddr : 192.168.31.56:40562
  INFO root [2018-06-27 17:07:17,941] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-27 17:07:17,942] - 	componentID : 9000
  INFO root [2018-06-27 17:07:18,879] - Components::findLogger: found logger, addr:192.168.31.56:40558
  INFO root [2018-06-27 17:07:18,881] - Components::addComponent: reset orderLog, uid=3093!
  INFO root [2018-06-27 17:07:18,881] - Components::addComponent[logger], uid=3093, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 17:07:18,894] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 3093. PID: 10504 ----
  INFO root [2018-06-27 17:07:18,895] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-27 17:07:18,897] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-27 17:07:18,897] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-27 17:07:19,060] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 17:07:19,061] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 17:07:19,062] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 17:07:19,068] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 17:07:19,069] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 17:07:19,070] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 17:07:19,070] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 17:07:19,148] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 17:07:19,233] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-27 17:07:19,233] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-27 17:07:19,239] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-27 17:07:19,240] - TelnetServer server is running on port 31000
  INFO root [2018-06-27 17:07:21,421] - ---- loginapp is running ----
 DEBUG root [2018-06-27 17:07:21,423] - Components::process(): Request for the process of identity...
  WARN root [2018-06-27 17:07:27,586] - Forwarding logs to logger[192.168.31.56:40558/0/0/0]...
 ERROR root [2018-06-27 17:08:03,940] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 17:08:03,964] - The following logs sent to logger failed:
  WARN root [2018-06-27 17:08:03,965] - ==> [2018-06-27 17:08:03 935] TCPPacketReceiver::processPendingEvents(192.168.31.56:40558): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 17:08:03,966] - ==> [2018-06-27 17:08:03 941] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-27 17:08:04,072] - TCPPacketReceiver::processPendingEvents(192.168.31.56:40563): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 17:08:04,078] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 17:08:04,087] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-27 17:08:04,099] - onLoginAppShutDown()
  INFO root [2018-06-27 17:08:04,100] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-27 17:08:04,100] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-27 17:08:04,101] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 17:08:04,101] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 17:08:04,101] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 17:08:04,101] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 17:08:04,102] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 17:08:04,102] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 17:08:04,102] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 17:08:04,103] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 17:08:04,125] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-27 17:08:04,125] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-27 17:08:04,426] - ThreadPool::destroy(): waiting for thread(2)[0x75de08,0x75dda0,], try=1
  INFO root [2018-06-27 17:09:13,449] - 
  INFO root [2018-06-27 17:09:13,450] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-27 17:09:13,452] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-27 17:09:13,453] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-27 17:09:13,453] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-27 17:09:13,474] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-27 17:09:13,474] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-27 17:09:13,479] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:40672 )
  INFO root [2018-06-27 17:09:13,479] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:40672, SOMAXCONN=128.
  INFO root [2018-06-27 17:09:13,480] - server-configs:
  INFO root [2018-06-27 17:09:13,480] - 	internalAddr : 192.168.31.56:40672
  INFO root [2018-06-27 17:09:13,480] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-27 17:09:13,481] - 	componentID : 9000
  INFO root [2018-06-27 17:09:15,820] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 3472. PID: 1276 ----
  INFO root [2018-06-27 17:09:15,822] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-27 17:09:15,823] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-27 17:09:15,823] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-27 17:09:15,996] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 17:09:15,997] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 17:09:15,999] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 17:09:16,007] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 17:09:16,008] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 17:09:16,009] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 17:09:16,011] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 17:09:16,100] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 17:09:16,193] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-27 17:09:16,193] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-27 17:09:16,198] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-27 17:09:16,200] - TelnetServer server is running on port 31000
  INFO root [2018-06-27 17:09:17,308] - ---- loginapp is running ----
 DEBUG root [2018-06-27 17:09:17,309] - Components::process(): Request for the process of identity...
  INFO root [2018-06-27 17:09:24,479] - Components::findComponents: find logger(1)...
  INFO root [2018-06-27 17:09:24,553] - Components::findComponents: found logger, addr:192.168.31.56:40669
  INFO root [2018-06-27 17:09:24,553] - Components::addComponent: reset orderLog, uid=3472!
  INFO root [2018-06-27 17:09:24,554] - Components::addComponent[logger], uid=3472, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 17:09:24,556] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-27 17:09:24,657] - Components::findComponents: found dbmgr, addr:192.168.31.56:40670
  INFO root [2018-06-27 17:09:24,657] - Components::addComponent: reset orderLog, uid=3472!
  INFO root [2018-06-27 17:09:24,657] - Components::addComponent[dbmgr], uid=3472, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 17:09:24,658] - Components::findComponents: found dbmgr, addr:192.168.31.56:40670
  WARN root [2018-06-27 17:09:25,658] - Forwarding logs to logger[192.168.31.56:40669/0/0/0]...
 ERROR root [2018-06-27 17:10:05,384] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 17:10:05,397] - The following logs sent to logger failed:
  WARN root [2018-06-27 17:10:05,397] - ==> [2018-06-27 17:10:05 383] TCPPacketReceiver::processPendingEvents(192.168.31.56:40669): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 17:10:05,398] - ==> [2018-06-27 17:10:05 385] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-27 17:10:05,516] - TCPPacketReceiver::processPendingEvents(192.168.31.56:40670): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 17:10:05,520] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 17:10:05,535] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-27 17:10:05,546] - onLoginAppShutDown()
  INFO root [2018-06-27 17:10:05,546] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-27 17:10:05,546] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-27 17:10:05,547] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 17:10:05,547] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 17:10:05,548] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 17:10:05,548] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 17:10:05,548] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 17:10:05,549] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 17:10:05,549] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 17:10:05,549] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 17:10:05,566] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-27 17:10:05,567] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-27 17:10:05,867] - ThreadPool::destroy(): waiting for thread(2)[0x5dde08,0x5ddda0,], try=1
  INFO root [2018-06-27 17:10:12,135] - 
  INFO root [2018-06-27 17:10:12,163] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-27 17:10:12,164] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-27 17:10:12,165] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-27 17:10:12,165] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-27 17:10:12,177] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-27 17:10:12,177] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-27 17:10:12,181] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:40747 )
  INFO root [2018-06-27 17:10:12,182] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:40747, SOMAXCONN=128.
  INFO root [2018-06-27 17:10:12,182] - server-configs:
  INFO root [2018-06-27 17:10:12,182] - 	internalAddr : 192.168.31.56:40747
  INFO root [2018-06-27 17:10:12,182] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-27 17:10:12,182] - 	componentID : 9000
  INFO root [2018-06-27 17:10:14,372] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 3664. PID: 7596 ----
  INFO root [2018-06-27 17:10:14,813] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-27 17:10:14,814] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-27 17:10:14,815] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-27 17:10:15,017] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 17:10:15,019] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 17:10:15,021] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 17:10:15,030] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 17:10:15,031] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 17:10:15,031] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 17:10:15,033] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 17:10:15,134] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 17:10:15,227] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-27 17:10:15,227] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-27 17:10:15,233] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-27 17:10:15,234] - TelnetServer server is running on port 31000
  INFO root [2018-06-27 17:10:16,654] - ---- loginapp is running ----
 DEBUG root [2018-06-27 17:10:16,654] - Components::process(): Request for the process of identity...
  INFO root [2018-06-27 17:10:23,833] - Components::findComponents: find logger(1)...
  INFO root [2018-06-27 17:10:23,833] - Components::findComponents: found logger, addr:192.168.31.56:40752
  INFO root [2018-06-27 17:10:23,833] - Components::addComponent: reset orderLog, uid=3664!
  INFO root [2018-06-27 17:10:23,833] - Components::addComponent[logger], uid=3664, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 17:10:23,833] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-27 17:10:24,050] - Components::findComponents: found dbmgr, addr:192.168.31.56:40746
  INFO root [2018-06-27 17:10:24,050] - Components::addComponent: reset orderLog, uid=3664!
  INFO root [2018-06-27 17:10:24,050] - Components::addComponent[dbmgr], uid=3664, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 17:10:24,050] - Components::findComponents: found dbmgr, addr:192.168.31.56:40746
  WARN root [2018-06-27 17:10:25,051] - Forwarding logs to logger[192.168.31.56:40752/0/0/0]...
 ERROR root [2018-06-27 17:15:56,039] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 17:15:56,039] - The following logs sent to logger failed:
  WARN root [2018-06-27 17:15:56,039] - ==> [2018-06-27 17:15:56 032] TCPPacketReceiver::processPendingEvents(192.168.31.56:40752): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 17:15:56,039] - ==> [2018-06-27 17:15:56 040] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-27 17:15:56,039] - TCPPacketReceiver::processPendingEvents(192.168.31.56:40746): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 17:15:56,039] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 17:15:56,039] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-27 17:15:56,039] - onLoginAppShutDown()
  INFO root [2018-06-27 17:15:56,039] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-27 17:15:56,039] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-27 17:15:56,039] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 17:15:56,039] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 17:15:56,039] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 17:15:56,039] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 17:15:56,039] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 17:15:56,039] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 17:15:56,039] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 17:15:56,039] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 17:15:56,039] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-27 17:15:56,039] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-27 17:15:56,039] - ThreadPool::destroy(): waiting for thread(2)[0x69de00,0x69dd98,], try=1
  INFO root [2018-06-27 17:16:01,604] - 
  INFO root [2018-06-27 17:16:01,605] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-27 17:16:01,608] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-27 17:16:01,609] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-27 17:16:01,610] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-27 17:16:01,673] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-27 17:16:01,674] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-27 17:16:01,685] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:41029 )
  INFO root [2018-06-27 17:16:01,686] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:41029, SOMAXCONN=128.
  INFO root [2018-06-27 17:16:01,687] - server-configs:
  INFO root [2018-06-27 17:16:01,688] - 	internalAddr : 192.168.31.56:41029
  INFO root [2018-06-27 17:16:01,688] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-27 17:16:01,689] - 	componentID : 9000
  INFO root [2018-06-27 17:16:03,982] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 4804. PID: 13728 ----
  INFO root [2018-06-27 17:16:03,984] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-27 17:16:03,985] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-27 17:16:03,988] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-27 17:16:04,250] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 17:16:04,252] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 17:16:04,254] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 17:16:04,263] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 17:16:04,264] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 17:16:04,265] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 17:16:04,303] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 17:16:04,533] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 17:16:04,670] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-27 17:16:04,671] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-27 17:16:04,677] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-27 17:16:04,680] - TelnetServer server is running on port 31000
  INFO root [2018-06-27 17:16:06,390] - ---- loginapp is running ----
 DEBUG root [2018-06-27 17:16:06,391] - Components::process(): Request for the process of identity...
  WARN root [2018-06-27 17:16:09,887] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20876, errorno=10048
  INFO root [2018-06-27 17:16:13,957] - Components::findComponents: find logger(1)...
  INFO root [2018-06-27 17:16:14,033] - Components::findComponents: found logger, addr:192.168.31.56:41024
  INFO root [2018-06-27 17:16:14,034] - Components::addComponent: reset orderLog, uid=4804!
  INFO root [2018-06-27 17:16:14,034] - Components::addComponent[logger], uid=4804, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 17:16:14,036] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-27 17:16:14,138] - Components::findComponents: found dbmgr, addr:192.168.31.56:41021
  INFO root [2018-06-27 17:16:14,138] - Components::addComponent: reset orderLog, uid=4804!
  INFO root [2018-06-27 17:16:14,139] - Components::addComponent[dbmgr], uid=4804, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 17:16:14,139] - Components::findComponents: found dbmgr, addr:192.168.31.56:41021
  WARN root [2018-06-27 17:16:15,139] - Forwarding logs to logger[192.168.31.56:41024/0/0/0]...
 ERROR root [2018-06-27 17:20:06,998] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 17:20:07,004] - The following logs sent to logger failed:
  WARN root [2018-06-27 17:20:07,005] - ==> [2018-06-27 17:20:06 996] TCPPacketReceiver::processPendingEvents(192.168.31.56:41024): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 17:20:07,006] - ==> [2018-06-27 17:20:06 999] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-27 17:20:07,116] - TCPPacketReceiver::processPendingEvents(192.168.31.56:41021): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 17:20:07,123] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 17:20:07,133] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-27 17:20:07,158] - onLoginAppShutDown()
  INFO root [2018-06-27 17:20:07,159] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-27 17:20:07,159] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-27 17:20:07,159] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 17:20:07,160] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 17:20:07,160] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 17:20:07,161] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 17:20:07,161] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 17:20:07,161] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 17:20:07,162] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 17:20:07,162] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 17:20:07,178] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-27 17:20:07,179] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-27 17:20:07,479] - ThreadPool::destroy(): waiting for thread(2)[0x3bde00,0x3bdd98,], try=1
  INFO root [2018-06-27 17:20:12,313] - 
  INFO root [2018-06-27 17:20:12,314] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-27 17:20:12,316] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-27 17:20:12,317] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-27 17:20:12,318] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-27 17:20:12,341] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-27 17:20:12,342] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-27 17:20:12,347] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:41237 )
  INFO root [2018-06-27 17:20:12,347] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:41237, SOMAXCONN=128.
  INFO root [2018-06-27 17:20:12,347] - server-configs:
  INFO root [2018-06-27 17:20:12,348] - 	internalAddr : 192.168.31.56:41237
  INFO root [2018-06-27 17:20:12,348] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-27 17:20:12,348] - 	componentID : 9000
  INFO root [2018-06-27 17:20:14,603] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 5620. PID: 12844 ----
  INFO root [2018-06-27 17:20:14,604] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-27 17:20:14,605] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-27 17:20:14,606] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-27 17:20:15,004] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 17:20:15,006] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 17:20:15,007] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 17:20:15,017] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 17:20:15,018] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 17:20:15,018] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 17:20:15,080] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 17:20:15,401] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 17:20:15,780] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-27 17:20:15,781] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-27 17:20:15,787] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-27 17:20:15,789] - TelnetServer server is running on port 31000
  INFO root [2018-06-27 17:20:17,463] - ---- loginapp is running ----
 DEBUG root [2018-06-27 17:20:17,464] - Components::process(): Request for the process of identity...
  INFO root [2018-06-27 17:20:24,622] - Components::findComponents: find logger(1)...
  INFO root [2018-06-27 17:20:24,639] - Components::findComponents: found logger, addr:192.168.31.56:41244
  INFO root [2018-06-27 17:20:24,641] - Components::addComponent: reset orderLog, uid=5620!
  INFO root [2018-06-27 17:20:24,641] - Components::addComponent[logger], uid=5620, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 17:20:24,644] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-27 17:20:24,749] - Components::findComponents: found dbmgr, addr:192.168.31.56:41238
  INFO root [2018-06-27 17:20:24,750] - Components::addComponent: reset orderLog, uid=5620!
  INFO root [2018-06-27 17:20:24,750] - Components::addComponent[dbmgr], uid=5620, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 17:20:24,753] - Components::findComponents: found dbmgr, addr:192.168.31.56:41238
  WARN root [2018-06-27 17:20:25,753] - Forwarding logs to logger[192.168.31.56:41244/0/0/0]...
 ERROR root [2018-06-27 17:34:55,814] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 17:34:55,818] - The following logs sent to logger failed:
  WARN root [2018-06-27 17:34:55,818] - ==> [2018-06-27 17:34:55 812] TCPPacketReceiver::processPendingEvents(192.168.31.56:41244): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 17:34:55,819] - ==> [2018-06-27 17:34:55 815] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-27 17:34:55,923] - TCPPacketReceiver::processPendingEvents(192.168.31.56:41238): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 17:34:55,926] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 17:34:55,930] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-27 17:34:55,933] - onLoginAppShutDown()
  INFO root [2018-06-27 17:34:55,933] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-27 17:34:55,934] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-27 17:34:55,934] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 17:34:55,935] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 17:34:55,936] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 17:34:55,936] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 17:34:55,936] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 17:34:55,937] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 17:34:55,937] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 17:34:55,937] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 17:34:55,956] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-27 17:34:55,957] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-27 17:34:56,258] - ThreadPool::destroy(): waiting for thread(2)[0x46de00,0x46dd98,], try=1
  INFO root [2018-06-27 17:35:37,745] - 
  INFO root [2018-06-27 17:35:37,746] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-27 17:35:37,748] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-27 17:35:37,749] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-27 17:35:37,750] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-27 17:35:37,762] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-27 17:35:37,763] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-27 17:35:37,768] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:41857 )
  INFO root [2018-06-27 17:35:37,768] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:41857, SOMAXCONN=128.
  INFO root [2018-06-27 17:35:37,768] - server-configs:
  INFO root [2018-06-27 17:35:37,769] - 	internalAddr : 192.168.31.56:41857
  INFO root [2018-06-27 17:35:37,769] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-27 17:35:37,769] - 	componentID : 9000
  INFO root [2018-06-27 17:35:39,915] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 8644. PID: 11696 ----
  INFO root [2018-06-27 17:35:39,918] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-27 17:35:39,919] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-27 17:35:39,920] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-27 17:35:40,095] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 17:35:40,097] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 17:35:40,098] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 17:35:40,106] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 17:35:40,107] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 17:35:40,107] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 17:35:40,109] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 17:35:40,234] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 17:35:40,364] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-27 17:35:40,365] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-27 17:35:40,370] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-27 17:35:40,406] - TelnetServer server is running on port 31000
  INFO root [2018-06-27 17:35:42,035] - ---- loginapp is running ----
 DEBUG root [2018-06-27 17:35:42,036] - Components::process(): Request for the process of identity...
  INFO root [2018-06-27 17:35:49,269] - 
  INFO root [2018-06-27 17:35:49,274] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-27 17:35:49,276] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-27 17:35:49,277] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-27 17:35:49,277] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-27 17:35:49,302] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-27 17:35:49,303] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-27 17:35:49,315] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:41881 )
  INFO root [2018-06-27 17:35:49,315] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:41881, SOMAXCONN=128.
  INFO root [2018-06-27 17:35:49,316] - server-configs:
  INFO root [2018-06-27 17:35:49,316] - 	internalAddr : 192.168.31.56:41881
  INFO root [2018-06-27 17:35:49,316] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-27 17:35:49,317] - 	componentID : 9000
  INFO root [2018-06-27 17:35:50,325] - Components::findLogger: found logger, addr:192.168.31.56:41874
  INFO root [2018-06-27 17:35:50,326] - Components::addComponent: reset orderLog, uid=8680!
  INFO root [2018-06-27 17:35:50,327] - Components::addComponent[logger], uid=8680, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 17:35:50,340] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 8680. PID: 13736 ----
  INFO root [2018-06-27 17:35:50,342] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-27 17:35:50,342] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-27 17:35:50,343] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-27 17:35:50,517] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 17:35:50,518] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 17:35:50,518] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 17:35:50,525] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 17:35:50,526] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 17:35:50,527] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 17:35:50,528] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 17:35:50,606] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 17:35:50,673] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-27 17:35:50,673] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-27 17:35:50,680] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-27 17:35:50,681] - TelnetServer server is running on port 31000
  INFO root [2018-06-27 17:35:52,948] - ---- loginapp is running ----
 DEBUG root [2018-06-27 17:35:52,951] - Components::process(): Request for the process of identity...
  WARN root [2018-06-27 17:35:59,141] - Forwarding logs to logger[192.168.31.56:41874/0/0/0]...
 ERROR root [2018-06-27 17:39:45,760] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 17:39:45,764] - The following logs sent to logger failed:
  WARN root [2018-06-27 17:39:45,765] - ==> [2018-06-27 17:39:45 759] TCPPacketReceiver::processPendingEvents(192.168.31.56:41874): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 17:39:45,765] - ==> [2018-06-27 17:39:45 760] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-27 17:39:45,878] - TCPPacketReceiver::processPendingEvents(192.168.31.56:41877): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 17:39:45,888] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 17:39:45,890] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-27 17:39:45,902] - onLoginAppShutDown()
  INFO root [2018-06-27 17:39:45,903] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-27 17:39:45,903] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-27 17:39:45,904] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 17:39:45,904] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 17:39:45,904] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 17:39:45,904] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 17:39:45,905] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 17:39:45,905] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 17:39:45,905] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 17:39:45,906] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 17:39:45,922] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-27 17:39:45,923] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-27 17:39:46,223] - ThreadPool::destroy(): waiting for thread(2)[0x1a9de00,0x1a9dd98,], try=1
  INFO root [2018-06-27 17:39:49,756] - 
  INFO root [2018-06-27 17:39:49,760] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-27 17:39:49,762] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-27 17:39:49,763] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-27 17:39:49,764] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-27 17:39:49,829] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-27 17:39:49,829] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-27 17:39:49,857] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:42106 )
  INFO root [2018-06-27 17:39:49,857] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:42106, SOMAXCONN=128.
  INFO root [2018-06-27 17:39:49,858] - server-configs:
  INFO root [2018-06-27 17:39:49,858] - 	internalAddr : 192.168.31.56:42106
  INFO root [2018-06-27 17:39:49,858] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-27 17:39:49,858] - 	componentID : 9000
  INFO root [2018-06-27 17:39:52,088] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 9467. PID: 16068 ----
  INFO root [2018-06-27 17:39:52,089] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-27 17:39:52,090] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-27 17:39:52,091] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-27 17:39:52,485] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 17:39:52,487] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 17:39:52,488] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 17:39:52,496] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 17:39:52,498] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 17:39:52,499] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 17:39:52,501] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 17:39:52,863] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 17:39:53,164] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-27 17:39:53,165] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-27 17:39:53,209] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-27 17:39:53,210] - TelnetServer server is running on port 31000
  INFO root [2018-06-27 17:39:54,806] - ---- loginapp is running ----
 DEBUG root [2018-06-27 17:39:54,807] - Components::process(): Request for the process of identity...
  INFO root [2018-06-27 17:40:01,930] - Components::findComponents: find logger(1)...
  INFO root [2018-06-27 17:40:01,972] - Components::findComponents: found logger, addr:192.168.31.56:42111
  INFO root [2018-06-27 17:40:01,973] - Components::addComponent: reset orderLog, uid=9467!
  INFO root [2018-06-27 17:40:01,973] - Components::addComponent[logger], uid=9467, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 17:40:01,976] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-27 17:40:02,079] - Components::findComponents: found dbmgr, addr:192.168.31.56:42107
  INFO root [2018-06-27 17:40:02,080] - Components::addComponent: reset orderLog, uid=9467!
  INFO root [2018-06-27 17:40:02,080] - Components::addComponent[dbmgr], uid=9467, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 17:40:02,080] - Components::findComponents: found dbmgr, addr:192.168.31.56:42107
  WARN root [2018-06-27 17:40:03,080] - Forwarding logs to logger[192.168.31.56:42111/0/0/0]...
 ERROR root [2018-06-27 17:48:42,861] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 17:48:42,882] - The following logs sent to logger failed:
  WARN root [2018-06-27 17:48:42,883] - ==> [2018-06-27 17:48:42 858] TCPPacketReceiver::processPendingEvents(192.168.31.56:42111): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 17:48:42,883] - ==> [2018-06-27 17:48:42 862] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-27 17:48:42,982] - TCPPacketReceiver::processPendingEvents(192.168.31.56:42107): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 17:48:42,986] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 17:48:42,992] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-27 17:48:43,003] - onLoginAppShutDown()
  INFO root [2018-06-27 17:48:43,003] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-27 17:48:43,004] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-27 17:48:43,004] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 17:48:43,005] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 17:48:43,005] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 17:48:43,005] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 17:48:43,005] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 17:48:43,006] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 17:48:43,006] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 17:48:43,006] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 17:48:43,023] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-27 17:48:43,024] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-27 17:48:43,324] - ThreadPool::destroy(): waiting for thread(2)[0x1bde00,0x1bdd98,], try=1
  INFO root [2018-06-27 17:48:46,824] - 
  INFO root [2018-06-27 17:48:46,825] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-27 17:48:46,827] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-27 17:48:46,828] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-27 17:48:46,829] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-27 17:48:46,846] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-27 17:48:46,846] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-27 17:48:46,852] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:42494 )
  INFO root [2018-06-27 17:48:46,853] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:42494, SOMAXCONN=128.
  INFO root [2018-06-27 17:48:46,853] - server-configs:
  INFO root [2018-06-27 17:48:46,854] - 	internalAddr : 192.168.31.56:42494
  INFO root [2018-06-27 17:48:46,854] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-27 17:48:46,854] - 	componentID : 9000
  INFO root [2018-06-27 17:48:47,857] - Components::findLogger: found logger, addr:192.168.31.56:42488
  INFO root [2018-06-27 17:48:47,858] - Components::addComponent: reset orderLog, uid=11221!
  INFO root [2018-06-27 17:48:47,859] - Components::addComponent[logger], uid=11221, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 17:48:47,867] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 11221. PID: 4440 ----
  INFO root [2018-06-27 17:48:47,868] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-27 17:48:47,870] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-27 17:48:47,870] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-27 17:48:48,047] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 17:48:48,048] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 17:48:48,049] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 17:48:48,056] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 17:48:48,057] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 17:48:48,057] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 17:48:48,058] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 17:48:48,149] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 17:48:48,246] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-27 17:48:48,247] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-27 17:48:48,252] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-27 17:48:48,254] - TelnetServer server is running on port 31000
  INFO root [2018-06-27 17:48:49,858] - ---- loginapp is running ----
 DEBUG root [2018-06-27 17:48:49,859] - Components::process(): Request for the process of identity...
  WARN root [2018-06-27 17:48:56,057] - Forwarding logs to logger[192.168.31.56:42488/0/0/0]...
 ERROR root [2018-06-27 17:55:08,119] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 17:55:08,121] - The following logs sent to logger failed:
  WARN root [2018-06-27 17:55:08,122] - ==> [2018-06-27 17:55:08 112] TCPPacketReceiver::processPendingEvents(192.168.31.56:42488): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 17:55:08,122] - ==> [2018-06-27 17:55:08 120] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-27 17:55:08,240] - TCPPacketReceiver::processPendingEvents(192.168.31.56:42491): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 17:55:08,243] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 17:55:08,249] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-27 17:55:08,250] - onLoginAppShutDown()
  INFO root [2018-06-27 17:55:08,250] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-27 17:55:08,251] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-27 17:55:08,251] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 17:55:08,252] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 17:55:08,252] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 17:55:08,252] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 17:55:08,252] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 17:55:08,253] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 17:55:08,253] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 17:55:08,253] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 17:55:08,271] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-27 17:55:08,272] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-27 17:55:08,572] - ThreadPool::destroy(): waiting for thread(2)[0x28de08,0x28dda0,], try=1
  INFO root [2018-06-27 17:55:12,574] - 
  INFO root [2018-06-27 17:55:12,575] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-27 17:55:12,577] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-27 17:55:12,578] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-27 17:55:12,578] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-27 17:55:12,605] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-27 17:55:12,606] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-27 17:55:12,611] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:42924 )
  INFO root [2018-06-27 17:55:12,611] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:42924, SOMAXCONN=128.
  INFO root [2018-06-27 17:55:12,612] - server-configs:
  INFO root [2018-06-27 17:55:12,612] - 	internalAddr : 192.168.31.56:42924
  INFO root [2018-06-27 17:55:12,612] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-27 17:55:12,612] - 	componentID : 9000
  INFO root [2018-06-27 17:55:13,556] - Components::findLogger: found logger, addr:192.168.31.56:42921
  INFO root [2018-06-27 17:55:13,556] - Components::addComponent: reset orderLog, uid=12481!
  INFO root [2018-06-27 17:55:13,556] - Components::addComponent[logger], uid=12481, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 17:55:13,566] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 12481. PID: 6044 ----
  INFO root [2018-06-27 17:55:13,566] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-27 17:55:13,567] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-27 17:55:13,567] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-27 17:55:13,734] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 17:55:13,735] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 17:55:13,735] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 17:55:13,742] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 17:55:13,742] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 17:55:13,742] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 17:55:13,743] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 17:55:13,819] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 17:55:13,889] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-27 17:55:13,889] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-27 17:55:13,894] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-27 17:55:13,895] - TelnetServer server is running on port 31000
  INFO root [2018-06-27 17:55:15,808] - ---- loginapp is running ----
 DEBUG root [2018-06-27 17:55:15,810] - Components::process(): Request for the process of identity...
  WARN root [2018-06-27 17:55:22,013] - Forwarding logs to logger[192.168.31.56:42921/0/0/0]...
 ERROR root [2018-06-27 18:04:39,332] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 18:04:39,342] - The following logs sent to logger failed:
  WARN root [2018-06-27 18:04:39,342] - ==> [2018-06-27 18:04:39 326] TCPPacketReceiver::processPendingEvents(192.168.31.56:42921): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 18:04:39,343] - ==> [2018-06-27 18:04:39 333] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-27 18:04:39,462] - TCPPacketReceiver::processPendingEvents(192.168.31.56:42918): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 18:04:39,475] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 18:04:39,483] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-27 18:04:39,484] - onLoginAppShutDown()
  INFO root [2018-06-27 18:04:39,484] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-27 18:04:39,484] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-27 18:04:39,485] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 18:04:39,486] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 18:04:39,486] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 18:04:39,486] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 18:04:39,487] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 18:04:39,487] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 18:04:39,487] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 18:04:39,488] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 18:04:39,512] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-27 18:04:39,512] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-27 18:04:39,812] - ThreadPool::destroy(): waiting for thread(2)[0x61de08,0x61dda0,], try=1
  INFO root [2018-06-27 18:04:46,006] - 
  INFO root [2018-06-27 18:04:46,007] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-27 18:04:46,009] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-27 18:04:46,010] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-27 18:04:46,011] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-27 18:04:46,025] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-27 18:04:46,025] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-27 18:04:46,030] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:43357 )
  INFO root [2018-06-27 18:04:46,030] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:43357, SOMAXCONN=128.
  INFO root [2018-06-27 18:04:46,031] - server-configs:
  INFO root [2018-06-27 18:04:46,031] - 	internalAddr : 192.168.31.56:43357
  INFO root [2018-06-27 18:04:46,031] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-27 18:04:46,031] - 	componentID : 9000
  INFO root [2018-06-27 18:04:47,969] - Components::findLogger: found logger, addr:192.168.31.56:43353
  INFO root [2018-06-27 18:04:47,970] - Components::addComponent: reset orderLog, uid=14353!
  INFO root [2018-06-27 18:04:47,971] - Components::addComponent[logger], uid=14353, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 18:04:47,989] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 14353. PID: 7220 ----
  INFO root [2018-06-27 18:04:47,990] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-27 18:04:47,992] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-27 18:04:47,993] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-27 18:04:48,234] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 18:04:48,236] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 18:04:48,237] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 18:04:48,246] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 18:04:48,247] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 18:04:48,248] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 18:04:48,284] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 18:04:48,494] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 18:04:48,693] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-27 18:04:48,694] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-27 18:04:48,700] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-27 18:04:48,702] - TelnetServer server is running on port 31000
  INFO root [2018-06-27 18:04:50,491] - ---- loginapp is running ----
 DEBUG root [2018-06-27 18:04:50,492] - Components::process(): Request for the process of identity...
  WARN root [2018-06-27 18:04:50,805] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20152, errorno=10048
  WARN root [2018-06-27 18:04:56,960] - Forwarding logs to logger[192.168.31.56:43353/0/0/0]...
 ERROR root [2018-06-27 19:02:00,268] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 19:02:00,271] - The following logs sent to logger failed:
  WARN root [2018-06-27 19:02:00,272] - ==> [2018-06-27 19:02:00 264] TCPPacketReceiver::processPendingEvents(192.168.31.56:43353): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 19:02:00,272] - ==> [2018-06-27 19:02:00 269] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-27 19:02:00,391] - TCPPacketReceiver::processPendingEvents(192.168.31.56:43355): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 19:02:00,395] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 19:02:00,400] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-27 19:02:00,401] - onLoginAppShutDown()
  INFO root [2018-06-27 19:02:00,401] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-27 19:02:00,401] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-27 19:02:00,402] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 19:02:00,402] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 19:02:00,402] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 19:02:00,403] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 19:02:00,403] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 19:02:00,403] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 19:02:00,404] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 19:02:00,404] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 19:02:00,422] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-27 19:02:00,422] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-27 19:02:00,722] - ThreadPool::destroy(): waiting for thread(2)[0x60cc78,0x60cc10,], try=1
  INFO root [2018-06-27 21:45:48,254] - 
  INFO root [2018-06-27 21:45:48,255] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-27 21:45:48,258] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-27 21:45:48,259] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-27 21:45:48,260] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-27 21:45:48,275] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-27 21:45:48,275] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-27 21:45:48,281] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:50471 )
  INFO root [2018-06-27 21:45:48,281] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:50471, SOMAXCONN=128.
  INFO root [2018-06-27 21:45:48,282] - server-configs:
  INFO root [2018-06-27 21:45:48,282] - 	internalAddr : 192.168.31.56:50471
  INFO root [2018-06-27 21:45:48,283] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-27 21:45:48,283] - 	componentID : 9000
  INFO root [2018-06-27 21:45:50,658] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 24889. PID: 15032 ----
  INFO root [2018-06-27 21:45:50,659] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-27 21:45:50,660] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-27 21:45:50,661] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-27 21:45:51,007] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 21:45:51,009] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 21:45:51,010] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 21:45:51,019] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 21:45:51,020] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 21:45:51,021] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 21:45:51,057] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 21:45:51,292] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 21:45:51,519] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-27 21:45:51,520] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-27 21:45:51,528] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-27 21:45:51,530] - TelnetServer server is running on port 31000
  INFO root [2018-06-27 21:45:53,398] - ---- loginapp is running ----
 DEBUG root [2018-06-27 21:45:53,399] - Components::process(): Request for the process of identity...
  INFO root [2018-06-27 21:46:00,663] - Components::findComponents: find logger(1)...
  INFO root [2018-06-27 21:46:00,735] - Components::findComponents: found logger, addr:192.168.31.56:50477
  INFO root [2018-06-27 21:46:00,735] - Components::addComponent: reset orderLog, uid=24889!
  INFO root [2018-06-27 21:46:00,736] - Components::addComponent[logger], uid=24889, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 21:46:00,739] - Components::findComponents: find dbmgr(2)...
  WARN root [2018-06-27 21:46:01,852] - Forwarding logs to logger[192.168.31.56:50477/0/0/0]...
 ERROR root [2018-06-27 21:46:04,109] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 21:46:04,124] - The following logs sent to logger failed:
  WARN root [2018-06-27 21:46:04,125] - ==> [2018-06-27 21:46:04 108] TCPPacketReceiver::processPendingEvents(192.168.31.56:50477): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 21:46:04,126] - ==> [2018-06-27 21:46:04 109] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 21:46:04,948] - Components::findComponents: find dbmgr(4)...
  INFO root [2018-06-27 21:46:24,019] - 
  INFO root [2018-06-27 21:46:24,020] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-27 21:46:24,023] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-27 21:46:24,023] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-27 21:46:24,024] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-27 21:46:24,038] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-27 21:46:24,039] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-27 21:46:24,045] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:50509 )
  INFO root [2018-06-27 21:46:24,045] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:50509, SOMAXCONN=128.
  INFO root [2018-06-27 21:46:24,046] - server-configs:
  INFO root [2018-06-27 21:46:24,046] - 	internalAddr : 192.168.31.56:50509
  INFO root [2018-06-27 21:46:24,046] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-27 21:46:24,046] - 	componentID : 9000
  INFO root [2018-06-27 21:46:26,406] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 25007. PID: 3424 ----
  INFO root [2018-06-27 21:46:26,407] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-27 21:46:26,408] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-27 21:46:26,409] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-27 21:46:26,642] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 21:46:26,644] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 21:46:26,645] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 21:46:26,653] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 21:46:26,654] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 21:46:26,655] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 21:46:26,656] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 21:46:26,876] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 21:46:27,064] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-27 21:46:27,065] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-27 21:46:27,070] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-27 21:46:27,072] - TelnetServer server is running on port 31000
  INFO root [2018-06-27 21:46:28,646] - ---- loginapp is running ----
 DEBUG root [2018-06-27 21:46:28,647] - Components::process(): Request for the process of identity...
  INFO root [2018-06-27 21:46:35,827] - Components::findComponents: find logger(1)...
  INFO root [2018-06-27 21:46:35,866] - Components::findComponents: found logger, addr:192.168.31.56:50513
  INFO root [2018-06-27 21:46:35,867] - Components::addComponent: reset orderLog, uid=25007!
  INFO root [2018-06-27 21:46:35,868] - Components::addComponent[logger], uid=25007, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 21:46:35,874] - Components::findComponents: find dbmgr(2)...
  WARN root [2018-06-27 21:46:36,971] - Forwarding logs to logger[192.168.31.56:50513/0/0/0]...
 ERROR root [2018-06-27 21:46:48,006] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 21:46:48,012] - The following logs sent to logger failed:
  WARN root [2018-06-27 21:46:48,013] - ==> [2018-06-27 21:46:48 004] TCPPacketReceiver::processPendingEvents(192.168.31.56:50513): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 21:46:48,014] - ==> [2018-06-27 21:46:48 007] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 21:46:48,428] - Components::findComponents: find dbmgr(8)...
  INFO root [2018-06-27 21:54:28,836] - 
  INFO root [2018-06-27 21:54:28,838] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-27 21:54:28,840] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-27 21:54:28,841] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-27 21:54:28,841] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-27 21:54:28,887] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-27 21:54:28,888] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-27 21:54:28,897] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:50872 )
  INFO root [2018-06-27 21:54:28,898] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:50872, SOMAXCONN=128.
  INFO root [2018-06-27 21:54:28,898] - server-configs:
  INFO root [2018-06-27 21:54:28,898] - 	internalAddr : 192.168.31.56:50872
  INFO root [2018-06-27 21:54:28,898] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-27 21:54:28,899] - 	componentID : 9000
  INFO root [2018-06-27 21:54:29,909] - Components::findLogger: found logger, addr:192.168.31.56:50869
  INFO root [2018-06-27 21:54:29,910] - Components::addComponent: reset orderLog, uid=26594!
  INFO root [2018-06-27 21:54:29,910] - Components::addComponent[logger], uid=26594, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 21:54:29,925] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 26594. PID: 2748 ----
  INFO root [2018-06-27 21:54:29,925] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-27 21:54:29,926] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-27 21:54:29,927] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-27 21:54:30,090] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 21:54:30,091] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 21:54:30,092] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 21:54:30,099] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 21:54:30,099] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 21:54:30,099] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 21:54:30,100] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 21:54:30,170] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 21:54:30,242] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-27 21:54:30,243] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-27 21:54:30,246] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-27 21:54:30,247] - TelnetServer server is running on port 31000
  INFO root [2018-06-27 21:54:31,444] - ---- loginapp is running ----
 DEBUG root [2018-06-27 21:54:31,445] - Components::process(): Request for the process of identity...
  WARN root [2018-06-27 21:54:37,604] - Forwarding logs to logger[192.168.31.56:50869/0/0/0]...
 ERROR root [2018-06-27 21:55:55,518] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 21:55:55,524] - The following logs sent to logger failed:
  WARN root [2018-06-27 21:55:55,525] - ==> [2018-06-27 21:55:55 512] TCPPacketReceiver::processPendingEvents(192.168.31.56:50869): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 21:55:55,526] - ==> [2018-06-27 21:55:55 518] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-27 21:55:55,767] - Components::findComponents: find dbmgr(38)...
delay time is too long, please check the dbmgr logs!
  INFO root [2018-06-27 21:57:08,099] - 
  INFO root [2018-06-27 21:57:08,100] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-27 21:57:08,102] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-27 21:57:08,102] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-27 21:57:08,103] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-27 21:57:08,117] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-27 21:57:08,117] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-27 21:57:08,134] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:51277 )
  INFO root [2018-06-27 21:57:08,135] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:51277, SOMAXCONN=128.
  INFO root [2018-06-27 21:57:08,135] - server-configs:
  INFO root [2018-06-27 21:57:08,135] - 	internalAddr : 192.168.31.56:51277
  INFO root [2018-06-27 21:57:08,135] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-27 21:57:08,136] - 	componentID : 9000
  INFO root [2018-06-27 21:57:09,129] - Components::findLogger: found logger, addr:192.168.31.56:51273
  INFO root [2018-06-27 21:57:09,130] - Components::addComponent: reset orderLog, uid=27113!
  INFO root [2018-06-27 21:57:09,130] - Components::addComponent[logger], uid=27113, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 21:57:09,141] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 27113. PID: 7336 ----
  INFO root [2018-06-27 21:57:09,141] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-27 21:57:09,142] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-27 21:57:09,142] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-27 21:57:09,297] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 21:57:09,297] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 21:57:09,298] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 21:57:09,303] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 21:57:09,304] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 21:57:09,305] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 21:57:09,306] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 21:57:09,378] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 21:57:09,452] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-27 21:57:09,453] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-27 21:57:09,456] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-27 21:57:09,458] - TelnetServer server is running on port 31000
  INFO root [2018-06-27 21:57:10,411] - ---- loginapp is running ----
 DEBUG root [2018-06-27 21:57:10,413] - Components::process(): Request for the process of identity...
  WARN root [2018-06-27 21:57:16,553] - Forwarding logs to logger[192.168.31.56:51273/0/0/0]...
  INFO root [2018-06-27 22:32:53,071] - 
  INFO root [2018-06-27 22:32:53,072] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-27 22:32:53,073] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-27 22:32:53,074] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-27 22:32:53,074] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-27 22:32:53,084] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-27 22:32:53,085] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-27 22:32:53,088] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:52539 )
  INFO root [2018-06-27 22:32:53,089] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:52539, SOMAXCONN=128.
  INFO root [2018-06-27 22:32:53,089] - server-configs:
  INFO root [2018-06-27 22:32:53,089] - 	internalAddr : 192.168.31.56:52539
  INFO root [2018-06-27 22:32:53,089] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-27 22:32:53,089] - 	componentID : 9000
  INFO root [2018-06-27 22:32:55,389] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 1350. PID: 368 ----
  INFO root [2018-06-27 22:32:55,391] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-27 22:32:55,391] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-27 22:32:55,392] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-27 22:32:55,843] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 22:32:55,845] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 22:32:55,846] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 22:32:55,856] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 22:32:55,857] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 22:32:55,858] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 22:32:55,860] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 22:32:56,188] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 22:32:56,461] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-27 22:32:56,462] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-27 22:32:56,470] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-27 22:32:56,471] - TelnetServer server is running on port 31000
  INFO root [2018-06-27 22:32:57,900] - ---- loginapp is running ----
 DEBUG root [2018-06-27 22:32:57,902] - Components::process(): Request for the process of identity...
  INFO root [2018-06-27 22:33:05,111] - Components::findComponents: find logger(1)...
  INFO root [2018-06-27 22:33:05,159] - Components::findComponents: found logger, addr:192.168.31.56:52542
  INFO root [2018-06-27 22:33:05,160] - Components::addComponent: reset orderLog, uid=1350!
  INFO root [2018-06-27 22:33:05,160] - Components::addComponent[logger], uid=1350, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 22:33:05,162] - Components::findComponents: find dbmgr(2)...
  WARN root [2018-06-27 22:33:06,266] - Forwarding logs to logger[192.168.31.56:52542/0/0/0]...
 ERROR root [2018-06-27 22:33:25,737] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 22:33:25,786] - The following logs sent to logger failed:
  WARN root [2018-06-27 22:33:25,786] - ==> [2018-06-27 22:33:25 732] TCPPacketReceiver::processPendingEvents(192.168.31.56:52542): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 22:33:25,787] - ==> [2018-06-27 22:33:25 738] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-27 22:33:25,976] - TCPPacketReceiver::processPendingEvents(192.168.31.56:52540): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 22:33:25,984] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 22:33:26,019] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-27 22:33:26,024] - onLoginAppShutDown()
  INFO root [2018-06-27 22:33:26,025] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-27 22:33:26,025] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-27 22:33:26,026] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 22:33:26,026] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 22:33:26,027] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 22:33:26,027] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 22:33:26,027] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 22:33:26,028] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 22:33:26,028] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 22:33:26,028] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 22:33:26,049] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-27 22:33:26,049] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-27 22:33:26,349] - ThreadPool::destroy(): waiting for thread(2)[0x83de08,0x83dda0,], try=1
  INFO root [2018-06-27 22:49:36,820] - 
  INFO root [2018-06-27 22:49:36,821] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-27 22:49:36,823] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-27 22:49:36,824] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-27 22:49:36,824] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-27 22:49:36,839] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-27 22:49:36,839] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-27 22:49:36,844] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:53489 )
  INFO root [2018-06-27 22:49:36,845] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:53489, SOMAXCONN=128.
  INFO root [2018-06-27 22:49:36,845] - server-configs:
  INFO root [2018-06-27 22:49:36,845] - 	internalAddr : 192.168.31.56:53489
  INFO root [2018-06-27 22:49:36,845] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-27 22:49:36,846] - 	componentID : 9000
  INFO root [2018-06-27 22:49:39,290] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 4629. PID: 13240 ----
  INFO root [2018-06-27 22:49:39,293] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-27 22:49:39,294] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-27 22:49:39,295] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-27 22:49:39,487] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 22:49:39,489] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 22:49:39,490] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 22:49:39,498] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 22:49:39,499] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 22:49:39,500] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 22:49:39,502] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 22:49:39,639] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 22:49:39,777] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-27 22:49:39,777] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-27 22:49:39,784] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-27 22:49:39,786] - TelnetServer server is running on port 31000
  INFO root [2018-06-27 22:49:40,496] - ---- loginapp is running ----
 DEBUG root [2018-06-27 22:49:40,497] - Components::process(): Request for the process of identity...
  INFO root [2018-06-27 22:49:47,664] - Components::findComponents: find logger(1)...
  INFO root [2018-06-27 22:49:47,725] - Components::findComponents: found logger, addr:192.168.31.56:53484
  INFO root [2018-06-27 22:49:47,725] - Components::addComponent: reset orderLog, uid=4629!
  INFO root [2018-06-27 22:49:47,726] - Components::addComponent[logger], uid=4629, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 22:49:47,730] - Components::findComponents: find dbmgr(2)...
  WARN root [2018-06-27 22:49:48,850] - Forwarding logs to logger[192.168.31.56:53484/0/0/0]...
  INFO root [2018-06-27 22:51:10,941] - 
  INFO root [2018-06-27 22:51:10,947] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-27 22:51:10,949] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-27 22:51:10,950] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-27 22:51:10,950] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-27 22:51:10,986] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-27 22:51:10,986] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-27 22:51:10,993] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:53595 )
  INFO root [2018-06-27 22:51:10,993] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:53595, SOMAXCONN=128.
  INFO root [2018-06-27 22:51:10,994] - server-configs:
  INFO root [2018-06-27 22:51:10,994] - 	internalAddr : 192.168.31.56:53595
  INFO root [2018-06-27 22:51:10,994] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-27 22:51:10,995] - 	componentID : 9000
  INFO root [2018-06-27 22:51:13,264] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 4936. PID: 15704 ----
  INFO root [2018-06-27 22:51:13,267] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-27 22:51:13,269] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-27 22:51:13,270] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-27 22:51:13,485] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 22:51:13,487] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 22:51:13,488] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 22:51:13,496] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 22:51:13,497] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 22:51:13,497] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 22:51:13,499] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 22:51:13,644] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 22:51:13,747] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-27 22:51:13,748] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-27 22:51:13,785] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-27 22:51:13,787] - TelnetServer server is running on port 31000
  INFO root [2018-06-27 22:51:14,577] - ---- loginapp is running ----
 DEBUG root [2018-06-27 22:51:14,578] - Components::process(): Request for the process of identity...
  INFO root [2018-06-27 22:51:21,765] - Components::findComponents: find logger(1)...
  INFO root [2018-06-27 22:51:21,830] - Components::findComponents: found logger, addr:192.168.31.56:53593
  INFO root [2018-06-27 22:51:21,831] - Components::addComponent: reset orderLog, uid=4936!
  INFO root [2018-06-27 22:51:21,831] - Components::addComponent[logger], uid=4936, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 22:51:21,834] - Components::findComponents: find dbmgr(2)...
  WARN root [2018-06-27 22:51:22,941] - Forwarding logs to logger[192.168.31.56:53593/0/0/0]...
 ERROR root [2018-06-27 22:51:45,654] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 22:51:45,654] - The following logs sent to logger failed:
  WARN root [2018-06-27 22:51:45,654] - ==> [2018-06-27 22:51:45 651] TCPPacketReceiver::processPendingEvents(192.168.31.56:53593): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 22:51:45,654] - ==> [2018-06-27 22:51:45 655] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 22:53:10,317] - 
  INFO root [2018-06-27 22:53:10,329] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-27 22:53:10,331] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-27 22:53:10,332] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-27 22:53:10,332] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-27 22:53:10,413] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-27 22:53:10,414] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-27 22:53:10,421] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:53724 )
  INFO root [2018-06-27 22:53:10,421] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:53724, SOMAXCONN=128.
  INFO root [2018-06-27 22:53:10,421] - server-configs:
  INFO root [2018-06-27 22:53:10,422] - 	internalAddr : 192.168.31.56:53724
  INFO root [2018-06-27 22:53:10,422] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-27 22:53:10,422] - 	componentID : 9000
  INFO root [2018-06-27 22:53:12,654] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 5328. PID: 1984 ----
  INFO root [2018-06-27 22:53:12,654] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-27 22:53:12,654] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-27 22:53:12,654] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-27 22:53:12,654] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 22:53:12,654] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 22:53:12,654] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 22:53:12,654] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 22:53:12,654] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 22:53:12,654] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 22:53:12,654] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 22:53:13,151] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 22:53:13,151] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-27 22:53:13,151] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-27 22:53:13,151] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-27 22:53:13,151] - TelnetServer server is running on port 31000
  INFO root [2018-06-27 22:53:15,192] - ---- loginapp is running ----
 DEBUG root [2018-06-27 22:53:15,192] - Components::process(): Request for the process of identity...
  INFO root [2018-06-27 22:53:22,429] - Components::findComponents: find logger(1)...
  INFO root [2018-06-27 22:53:22,429] - Components::findComponents: found logger, addr:192.168.31.56:53726
  INFO root [2018-06-27 22:53:22,429] - Components::addComponent: reset orderLog, uid=5328!
  INFO root [2018-06-27 22:53:22,429] - Components::addComponent[logger], uid=5328, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 22:53:22,429] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-27 22:53:22,429] - Components::findComponents: found dbmgr, addr:192.168.31.56:53729
  INFO root [2018-06-27 22:53:22,429] - Components::addComponent: reset orderLog, uid=5328!
  INFO root [2018-06-27 22:53:22,429] - Components::addComponent[dbmgr], uid=5328, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 22:53:22,429] - Components::findComponents: found dbmgr, addr:192.168.31.56:53729
  WARN root [2018-06-27 22:53:23,554] - Forwarding logs to logger[192.168.31.56:53726/0/0/0]...
 ERROR root [2018-06-27 22:53:26,434] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 22:53:26,434] - The following logs sent to logger failed:
  WARN root [2018-06-27 22:53:26,434] - ==> [2018-06-27 22:53:26 430] TCPPacketReceiver::processPendingEvents(192.168.31.56:53726): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 22:53:26,434] - ==> [2018-06-27 22:53:26 434] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 22:53:26,434] - Components::findComponents: register self to dbmgr...
  INFO root [2018-06-27 22:53:31,840] - 
  INFO root [2018-06-27 22:53:31,842] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-27 22:53:31,846] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-27 22:53:31,847] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-27 22:53:31,847] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-27 22:53:31,876] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-27 22:53:31,876] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-27 22:53:31,889] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:53770 )
  INFO root [2018-06-27 22:53:31,890] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:53770, SOMAXCONN=128.
  INFO root [2018-06-27 22:53:31,890] - server-configs:
  INFO root [2018-06-27 22:53:31,890] - 	internalAddr : 192.168.31.56:53770
  INFO root [2018-06-27 22:53:31,891] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-27 22:53:31,891] - 	componentID : 9000
  INFO root [2018-06-27 22:53:34,145] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 5396. PID: 16108 ----
  INFO root [2018-06-27 22:53:34,146] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-27 22:53:34,147] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-27 22:53:34,148] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-27 22:53:34,433] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 22:53:34,435] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 22:53:34,436] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 22:53:34,443] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 22:53:34,444] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 22:53:34,444] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 22:53:34,445] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 22:53:34,705] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 22:53:34,875] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-27 22:53:34,876] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-27 22:53:34,882] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-27 22:53:34,921] - TelnetServer server is running on port 31000
  INFO root [2018-06-27 22:53:36,589] - ---- loginapp is running ----
 DEBUG root [2018-06-27 22:53:36,590] - Components::process(): Request for the process of identity...
  INFO root [2018-06-27 22:53:43,803] - Components::findComponents: find logger(1)...
  INFO root [2018-06-27 22:53:43,874] - Components::findComponents: found logger, addr:192.168.31.56:53764
  INFO root [2018-06-27 22:53:43,874] - Components::addComponent: reset orderLog, uid=5396!
  INFO root [2018-06-27 22:53:43,875] - Components::addComponent[logger], uid=5396, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 22:53:43,877] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-27 22:53:43,979] - Components::findComponents: found dbmgr, addr:192.168.31.56:53769
  INFO root [2018-06-27 22:53:43,979] - Components::addComponent: reset orderLog, uid=5396!
  INFO root [2018-06-27 22:53:43,979] - Components::addComponent[dbmgr], uid=5396, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 22:53:43,981] - Components::findComponents: found dbmgr, addr:192.168.31.56:53769
  WARN root [2018-06-27 22:53:44,981] - Forwarding logs to logger[192.168.31.56:53764/0/0/0]...
 ERROR root [2018-06-27 23:01:22,858] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 23:01:22,864] - The following logs sent to logger failed:
  WARN root [2018-06-27 23:01:22,865] - ==> [2018-06-27 23:01:22 857] TCPPacketReceiver::processPendingEvents(192.168.31.56:53764): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 23:01:22,866] - ==> [2018-06-27 23:01:22 859] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-27 23:01:22,978] - TCPPacketReceiver::processPendingEvents(192.168.31.56:53769): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 23:01:22,979] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 23:01:22,980] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-27 23:01:22,981] - onLoginAppShutDown()
  INFO root [2018-06-27 23:01:22,981] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-27 23:01:22,981] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-27 23:01:22,982] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 23:01:22,982] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 23:01:22,982] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 23:01:22,982] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 23:01:22,982] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 23:01:22,983] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 23:01:22,983] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 23:01:22,983] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 23:01:23,000] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-27 23:01:23,002] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-27 23:01:23,302] - ThreadPool::destroy(): waiting for thread(2)[0x47de00,0x47dd98,], try=1
  INFO root [2018-06-27 23:01:27,856] - 
  INFO root [2018-06-27 23:01:27,857] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-27 23:01:27,859] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-27 23:01:27,860] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-27 23:01:27,860] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-27 23:01:27,873] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-27 23:01:27,874] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-27 23:01:27,878] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:54187 )
  INFO root [2018-06-27 23:01:27,878] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:54187, SOMAXCONN=128.
  INFO root [2018-06-27 23:01:27,879] - server-configs:
  INFO root [2018-06-27 23:01:27,879] - 	internalAddr : 192.168.31.56:54187
  INFO root [2018-06-27 23:01:27,879] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-27 23:01:27,880] - 	componentID : 9000
  WARN root [2018-06-27 23:01:28,781] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20159, errorno=10048
  INFO root [2018-06-27 23:01:28,790] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 6950. PID: 9036 ----
  INFO root [2018-06-27 23:01:28,790] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-27 23:01:28,791] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-27 23:01:28,792] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-27 23:01:28,958] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 23:01:28,959] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 23:01:28,960] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 23:01:28,967] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 23:01:28,968] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 23:01:28,968] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 23:01:28,970] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 23:01:29,048] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 23:01:29,127] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-27 23:01:29,128] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-27 23:01:29,134] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-27 23:01:29,135] - TelnetServer server is running on port 31000
  INFO root [2018-06-27 23:01:30,372] - ---- loginapp is running ----
 DEBUG root [2018-06-27 23:01:30,373] - Components::process(): Request for the process of identity...
  INFO root [2018-06-27 23:01:38,038] - Components::findComponents: find logger(1)...
  INFO root [2018-06-27 23:01:38,045] - Components::findComponents: found logger, addr:192.168.31.56:54180
  INFO root [2018-06-27 23:01:38,045] - Components::addComponent: reset orderLog, uid=6950!
  INFO root [2018-06-27 23:01:38,046] - Components::addComponent[logger], uid=6950, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 23:01:38,048] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-27 23:01:38,151] - Components::findComponents: found dbmgr, addr:192.168.31.56:54182
  INFO root [2018-06-27 23:01:38,151] - Components::addComponent: reset orderLog, uid=6950!
  INFO root [2018-06-27 23:01:38,152] - Components::addComponent[dbmgr], uid=6950, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 23:01:38,156] - Components::findComponents: found dbmgr, addr:192.168.31.56:54182
  WARN root [2018-06-27 23:01:39,157] - Forwarding logs to logger[192.168.31.56:54180/0/0/0]...
 ERROR root [2018-06-27 23:04:48,645] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 23:04:48,653] - The following logs sent to logger failed:
  WARN root [2018-06-27 23:04:48,654] - ==> [2018-06-27 23:04:48 645] TCPPacketReceiver::processPendingEvents(192.168.31.56:54180): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 23:04:48,655] - ==> [2018-06-27 23:04:48 646] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-27 23:04:48,762] - TCPPacketReceiver::processPendingEvents(192.168.31.56:54182): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 23:04:48,767] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 23:04:48,769] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-27 23:04:48,769] - onLoginAppShutDown()
  INFO root [2018-06-27 23:04:48,770] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-27 23:04:48,770] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-27 23:04:48,771] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 23:04:48,771] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 23:04:48,772] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 23:04:48,772] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 23:04:48,772] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 23:04:48,773] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 23:04:48,773] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 23:04:48,774] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 23:04:48,793] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-27 23:04:48,794] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-27 23:04:49,094] - ThreadPool::destroy(): waiting for thread(2)[0x8cde68,0x8cde00,], try=1
  INFO root [2018-06-27 23:12:42,725] - 
  INFO root [2018-06-27 23:12:42,725] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-27 23:12:42,727] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-27 23:12:42,728] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-27 23:12:42,728] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-27 23:12:42,740] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-27 23:12:42,741] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-27 23:12:42,745] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:54714 )
  INFO root [2018-06-27 23:12:42,745] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:54714, SOMAXCONN=128.
  INFO root [2018-06-27 23:12:42,745] - server-configs:
  INFO root [2018-06-27 23:12:42,745] - 	internalAddr : 192.168.31.56:54714
  INFO root [2018-06-27 23:12:42,746] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-27 23:12:42,746] - 	componentID : 9000
  INFO root [2018-06-27 23:12:44,743] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 9155. PID: 16336 ----
  INFO root [2018-06-27 23:12:44,744] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-27 23:12:44,744] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-27 23:12:44,745] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-27 23:12:44,906] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 23:12:44,908] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 23:12:44,909] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 23:12:44,916] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 23:12:44,917] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 23:12:44,917] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 23:12:44,918] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 23:12:45,008] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 23:12:45,101] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-27 23:12:45,101] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-27 23:12:45,107] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-27 23:12:45,108] - TelnetServer server is running on port 31000
  INFO root [2018-06-27 23:12:46,616] - ---- loginapp is running ----
 DEBUG root [2018-06-27 23:12:46,619] - Components::process(): Request for the process of identity...
  INFO root [2018-06-27 23:12:53,826] - Components::findComponents: find logger(1)...
  INFO root [2018-06-27 23:12:53,861] - Components::findComponents: found logger, addr:192.168.31.56:54719
  INFO root [2018-06-27 23:12:53,861] - Components::addComponent: reset orderLog, uid=9155!
  INFO root [2018-06-27 23:12:53,861] - Components::addComponent[logger], uid=9155, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 23:12:53,863] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-27 23:12:53,965] - Components::findComponents: found dbmgr, addr:192.168.31.56:54717
  INFO root [2018-06-27 23:12:53,965] - Components::addComponent: reset orderLog, uid=9155!
  INFO root [2018-06-27 23:12:53,965] - Components::addComponent[dbmgr], uid=9155, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 23:12:53,966] - Components::findComponents: found dbmgr, addr:192.168.31.56:54717
  WARN root [2018-06-27 23:12:54,966] - Forwarding logs to logger[192.168.31.56:54719/0/0/0]...
 ERROR root [2018-06-27 23:13:05,886] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 23:13:05,908] - The following logs sent to logger failed:
  WARN root [2018-06-27 23:13:05,909] - ==> [2018-06-27 23:13:05 883] TCPPacketReceiver::processPendingEvents(192.168.31.56:54719): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 23:13:05,910] - ==> [2018-06-27 23:13:05 887] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-27 23:13:06,013] - TCPPacketReceiver::processPendingEvents(192.168.31.56:54717): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 23:13:06,016] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 23:13:06,019] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-27 23:13:06,022] - onLoginAppShutDown()
  INFO root [2018-06-27 23:13:06,023] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-27 23:13:06,023] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-27 23:13:06,024] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 23:13:06,024] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 23:13:06,025] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 23:13:06,025] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 23:13:06,026] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 23:13:06,026] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 23:13:06,027] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 23:13:06,027] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 23:13:06,046] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-27 23:13:06,046] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-27 23:13:06,346] - ThreadPool::destroy(): waiting for thread(2)[0x4cde00,0x4cdd98,], try=1
  INFO root [2018-06-27 23:13:07,858] - 
  INFO root [2018-06-27 23:13:07,860] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-27 23:13:07,861] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-27 23:13:07,862] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-27 23:13:07,863] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-27 23:13:07,880] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-27 23:13:07,881] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-27 23:13:07,888] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:54768 )
  INFO root [2018-06-27 23:13:07,888] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:54768, SOMAXCONN=128.
  INFO root [2018-06-27 23:13:07,889] - server-configs:
  INFO root [2018-06-27 23:13:07,889] - 	internalAddr : 192.168.31.56:54768
  INFO root [2018-06-27 23:13:07,889] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-27 23:13:07,891] - 	componentID : 9000
  INFO root [2018-06-27 23:13:10,163] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 9236. PID: 2960 ----
  INFO root [2018-06-27 23:13:10,165] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-27 23:13:10,165] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-27 23:13:10,166] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-27 23:13:10,350] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 23:13:10,352] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 23:13:10,353] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 23:13:10,362] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 23:13:10,363] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 23:13:10,363] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 23:13:10,365] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 23:13:10,480] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 23:13:10,625] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-27 23:13:10,626] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-27 23:13:10,631] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-27 23:13:10,632] - TelnetServer server is running on port 31000
  INFO root [2018-06-27 23:13:11,908] - ---- loginapp is running ----
 DEBUG root [2018-06-27 23:13:11,909] - Components::process(): Request for the process of identity...
  INFO root [2018-06-27 23:13:19,065] - Components::findComponents: find logger(1)...
  INFO root [2018-06-27 23:13:19,145] - Components::findComponents: found logger, addr:192.168.31.56:54765
  INFO root [2018-06-27 23:13:19,146] - Components::addComponent: reset orderLog, uid=9236!
  INFO root [2018-06-27 23:13:19,146] - Components::addComponent[logger], uid=9236, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 23:13:19,148] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-27 23:13:19,151] - Components::findComponents: found logger, addr:192.168.31.56:54765
  INFO root [2018-06-27 23:13:19,254] - Components::findComponents: found dbmgr, addr:192.168.31.56:54766
  INFO root [2018-06-27 23:13:19,254] - Components::addComponent: reset orderLog, uid=9236!
  INFO root [2018-06-27 23:13:19,255] - Components::addComponent[dbmgr], uid=9236, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 23:13:19,255] - Components::findComponents: found dbmgr, addr:192.168.31.56:54766
  WARN root [2018-06-27 23:13:20,255] - Forwarding logs to logger[192.168.31.56:54765/0/0/0]...
 ERROR root [2018-06-27 23:13:36,160] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 23:13:36,187] - The following logs sent to logger failed:
  WARN root [2018-06-27 23:13:36,188] - ==> [2018-06-27 23:13:36 157] TCPPacketReceiver::processPendingEvents(192.168.31.56:54765): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 23:13:36,189] - ==> [2018-06-27 23:13:36 161] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-27 23:13:36,301] - TCPPacketReceiver::processPendingEvents(192.168.31.56:54766): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 23:13:36,306] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 23:13:36,314] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-27 23:13:36,317] - onLoginAppShutDown()
  INFO root [2018-06-27 23:13:36,318] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-27 23:13:36,321] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-27 23:13:36,322] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 23:13:36,322] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 23:13:36,323] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 23:13:36,323] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 23:13:36,323] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 23:13:36,323] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 23:13:36,324] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 23:13:36,324] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 23:13:36,346] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-27 23:13:36,346] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-27 23:13:36,646] - ThreadPool::destroy(): waiting for thread(2)[0x53de08,0x53dda0,], try=1
  INFO root [2018-06-27 23:13:40,583] - 
  INFO root [2018-06-27 23:13:40,592] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-27 23:13:40,594] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-27 23:13:40,595] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-27 23:13:40,595] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-27 23:13:40,622] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-27 23:13:40,623] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-27 23:13:40,628] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:54823 )
  INFO root [2018-06-27 23:13:40,629] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:54823, SOMAXCONN=128.
  INFO root [2018-06-27 23:13:40,629] - server-configs:
  INFO root [2018-06-27 23:13:40,629] - 	internalAddr : 192.168.31.56:54823
  INFO root [2018-06-27 23:13:40,630] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-27 23:13:40,630] - 	componentID : 9000
  INFO root [2018-06-27 23:13:42,826] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 9344. PID: 2024 ----
  INFO root [2018-06-27 23:13:42,827] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-27 23:13:42,828] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-27 23:13:42,828] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-27 23:13:43,046] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 23:13:43,048] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 23:13:43,049] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 23:13:43,088] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 23:13:43,089] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 23:13:43,090] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 23:13:43,091] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 23:13:43,251] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 23:13:43,442] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-27 23:13:43,442] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-27 23:13:43,447] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-27 23:13:43,448] - TelnetServer server is running on port 31000
  INFO root [2018-06-27 23:13:44,861] - ---- loginapp is running ----
 DEBUG root [2018-06-27 23:13:44,862] - Components::process(): Request for the process of identity...
  INFO root [2018-06-27 23:13:52,008] - Components::findComponents: find logger(1)...
  INFO root [2018-06-27 23:13:52,064] - Components::findComponents: found logger, addr:192.168.31.56:54820
  INFO root [2018-06-27 23:13:52,064] - Components::addComponent: reset orderLog, uid=9344!
  INFO root [2018-06-27 23:13:52,064] - Components::addComponent[logger], uid=9344, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 23:13:52,066] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-27 23:13:52,169] - Components::findComponents: found dbmgr, addr:192.168.31.56:54822
  INFO root [2018-06-27 23:13:52,170] - Components::addComponent: reset orderLog, uid=9344!
  INFO root [2018-06-27 23:13:52,170] - Components::addComponent[dbmgr], uid=9344, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 23:13:52,170] - Components::findComponents: found dbmgr, addr:192.168.31.56:54822
  WARN root [2018-06-27 23:13:53,171] - Forwarding logs to logger[192.168.31.56:54820/0/0/0]...
 ERROR root [2018-06-27 23:14:09,420] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 23:14:09,430] - The following logs sent to logger failed:
  WARN root [2018-06-27 23:14:09,430] - ==> [2018-06-27 23:14:09 418] TCPPacketReceiver::processPendingEvents(192.168.31.56:54820): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 23:14:09,431] - ==> [2018-06-27 23:14:09 421] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-27 23:14:09,567] - TCPPacketReceiver::processPendingEvents(192.168.31.56:54822): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-27 23:14:09,569] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-27 23:14:09,583] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-27 23:14:09,596] - onLoginAppShutDown()
  INFO root [2018-06-27 23:14:09,596] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-27 23:14:09,596] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-27 23:14:09,597] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 23:14:09,597] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 23:14:09,598] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 23:14:09,598] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 23:14:09,598] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 23:14:09,599] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 23:14:09,599] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 23:14:09,599] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 23:14:09,617] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-27 23:14:09,617] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-27 23:14:09,917] - ThreadPool::destroy(): waiting for thread(2)[0x62de00,0x62dd98,], try=1
  INFO root [2018-06-27 23:14:14,164] - 
  INFO root [2018-06-27 23:14:14,166] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-27 23:14:14,167] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-27 23:14:14,168] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-27 23:14:14,169] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-27 23:14:14,245] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-27 23:14:14,246] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-27 23:14:14,263] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:54879 )
  INFO root [2018-06-27 23:14:14,263] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:54879, SOMAXCONN=128.
  INFO root [2018-06-27 23:14:14,264] - server-configs:
  INFO root [2018-06-27 23:14:14,264] - 	internalAddr : 192.168.31.56:54879
  INFO root [2018-06-27 23:14:14,264] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-27 23:14:14,264] - 	componentID : 9000
  INFO root [2018-06-27 23:14:16,360] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 9452. PID: 15112 ----
  INFO root [2018-06-27 23:14:16,361] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-27 23:14:16,362] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-27 23:14:16,362] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-27 23:14:16,662] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-27 23:14:16,663] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-27 23:14:16,664] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-27 23:14:16,671] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-27 23:14:16,672] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-27 23:14:16,673] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-27 23:14:16,674] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-27 23:14:16,881] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-27 23:14:17,058] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-27 23:14:17,059] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-27 23:14:17,074] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-27 23:14:17,075] - TelnetServer server is running on port 31000
  INFO root [2018-06-27 23:14:18,384] - ---- loginapp is running ----
 DEBUG root [2018-06-27 23:14:18,385] - Components::process(): Request for the process of identity...
  INFO root [2018-06-27 23:14:25,534] - Components::findComponents: find logger(1)...
  INFO root [2018-06-27 23:14:25,616] - Components::findComponents: found logger, addr:192.168.31.56:54877
  INFO root [2018-06-27 23:14:25,616] - Components::addComponent: reset orderLog, uid=9452!
  INFO root [2018-06-27 23:14:25,617] - Components::addComponent[logger], uid=9452, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 23:14:25,619] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-27 23:14:25,720] - Components::findComponents: found dbmgr, addr:192.168.31.56:54875
  INFO root [2018-06-27 23:14:25,720] - Components::addComponent: reset orderLog, uid=9452!
  INFO root [2018-06-27 23:14:25,720] - Components::addComponent[dbmgr], uid=9452, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-27 23:14:25,721] - Components::findComponents: found dbmgr, addr:192.168.31.56:54875
  WARN root [2018-06-27 23:14:26,721] - Forwarding logs to logger[192.168.31.56:54877/0/0/0]...
