  INFO root [2018-06-25 14:55:57,725] - 
  INFO root [2018-06-25 14:55:57,787] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-25 14:55:59,821] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-25 14:55:59,822] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-25 14:55:59,822] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-25 14:56:00,060] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-25 14:56:00,114] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-25 14:56:00,117] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:10557 )
  INFO root [2018-06-25 14:56:00,117] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:10557, SOMAXCONN=128.
  INFO root [2018-06-25 14:56:00,117] - server-configs:
  INFO root [2018-06-25 14:56:00,117] - 	internalAddr : 192.168.31.56:10557
  INFO root [2018-06-25 14:56:00,117] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-25 14:56:00,117] - 	componentID : 9000
  INFO root [2018-06-25 14:56:02,527] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 2843. PID: 7228 ----
  INFO root [2018-06-25 14:56:02,528] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-25 14:56:02,543] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-25 14:56:02,611] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-25 14:56:06,986] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-25 14:56:07,129] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-25 14:56:07,226] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-25 14:56:08,559] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-25 14:56:08,598] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-25 14:56:08,747] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-25 14:56:08,835] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-25 14:56:09,408] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-25 14:56:10,684] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-25 14:56:10,685] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-25 14:56:10,744] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-25 14:56:10,776] - TelnetServer server is running on port 31000
  INFO root [2018-06-25 14:56:12,248] - ---- loginapp is running ----
 DEBUG root [2018-06-25 14:56:12,248] - Components::process(): Request for the process of identity...
  INFO root [2018-06-25 14:56:19,505] - Components::findComponents: find logger(1)...
  INFO root [2018-06-25 14:56:19,582] - Components::findComponents: found logger, addr:192.168.31.56:10555
  INFO root [2018-06-25 14:56:19,583] - Components::addComponent: reset orderLog, uid=2843!
  INFO root [2018-06-25 14:56:19,583] - Components::addComponent[logger], uid=2843, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-25 14:56:19,592] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-25 14:56:19,685] - Components::findComponents: found dbmgr, addr:192.168.31.56:10556
  INFO root [2018-06-25 14:56:19,685] - Components::addComponent: reset orderLog, uid=2843!
  INFO root [2018-06-25 14:56:19,686] - Components::addComponent[dbmgr], uid=2843, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-25 14:56:19,686] - Components::findComponents: found dbmgr, addr:192.168.31.56:10556
  WARN root [2018-06-25 14:56:20,686] - Forwarding logs to logger[192.168.31.56:10555/0/0/0]...
 ERROR root [2018-06-25 18:42:59,812] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-25 18:42:59,827] - The following logs sent to logger failed:
  WARN root [2018-06-25 18:42:59,827] - ==> [2018-06-25 18:42:59 796] TCPPacketReceiver::processPendingEvents(192.168.31.56:10555): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-25 18:42:59,827] - ==> [2018-06-25 18:42:59 812] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-25 18:42:59,890] - TCPPacketReceiver::processPendingEvents(192.168.31.56:10556): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-25 18:42:59,890] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-25 18:42:59,905] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-25 18:42:59,921] - onLoginAppShutDown()
  INFO root [2018-06-25 18:42:59,921] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-25 18:42:59,921] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-25 18:42:59,968] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-25 18:42:59,968] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-25 18:42:59,968] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-25 18:42:59,968] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-25 18:42:59,968] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-25 18:42:59,968] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-25 18:42:59,968] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-25 18:42:59,968] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-25 18:42:59,983] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-25 18:42:59,983] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-06-25 21:02:14,042] - 
  INFO root [2018-06-25 21:02:14,043] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-25 21:02:14,045] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-25 21:02:14,045] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-25 21:02:14,046] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-25 21:02:14,057] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-25 21:02:14,057] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-25 21:02:14,065] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:15739 )
  INFO root [2018-06-25 21:02:14,065] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:15739, SOMAXCONN=128.
  INFO root [2018-06-25 21:02:14,066] - server-configs:
  INFO root [2018-06-25 21:02:14,066] - 	internalAddr : 192.168.31.56:15739
  INFO root [2018-06-25 21:02:14,066] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-25 21:02:14,067] - 	componentID : 9000
  INFO root [2018-06-25 21:02:16,060] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 9124. PID: 9264 ----
  INFO root [2018-06-25 21:02:16,061] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-25 21:02:16,061] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-25 21:02:16,062] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-25 21:02:16,236] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-25 21:02:16,237] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-25 21:02:16,238] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-25 21:02:16,278] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-25 21:02:16,279] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-25 21:02:16,279] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-25 21:02:16,280] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-25 21:02:16,425] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-25 21:02:16,605] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-25 21:02:16,606] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-25 21:02:16,611] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-25 21:02:16,612] - TelnetServer server is running on port 31000
  INFO root [2018-06-25 21:02:17,952] - ---- loginapp is running ----
 DEBUG root [2018-06-25 21:02:17,953] - Components::process(): Request for the process of identity...
  INFO root [2018-06-25 21:02:25,048] - Components::findComponents: find logger(1)...
  INFO root [2018-06-25 21:02:25,106] - Components::findComponents: found logger, addr:192.168.31.56:15744
  INFO root [2018-06-25 21:02:25,106] - Components::addComponent: reset orderLog, uid=9124!
  INFO root [2018-06-25 21:02:25,106] - Components::addComponent[logger], uid=9124, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-25 21:02:25,109] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-25 21:02:25,218] - Components::findComponents: found dbmgr, addr:192.168.31.56:15745
  INFO root [2018-06-25 21:02:25,218] - Components::addComponent: reset orderLog, uid=9124!
  INFO root [2018-06-25 21:02:25,219] - Components::addComponent[dbmgr], uid=9124, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-25 21:02:25,219] - Components::findComponents: found dbmgr, addr:192.168.31.56:15745
  WARN root [2018-06-25 21:02:26,219] - Forwarding logs to logger[192.168.31.56:15744/0/0/0]...
 ERROR root [2018-06-25 23:00:46,182] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-25 23:00:46,187] - The following logs sent to logger failed:
  WARN root [2018-06-25 23:00:46,188] - ==> [2018-06-25 23:00:46 172] TCPPacketReceiver::processPendingEvents(192.168.31.56:15744): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-25 23:00:46,188] - ==> [2018-06-25 23:00:46 183] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-25 23:00:46,294] - TCPPacketReceiver::processPendingEvents(192.168.31.56:15745): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-25 23:00:46,298] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-25 23:00:46,300] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-25 23:00:46,301] - onLoginAppShutDown()
  INFO root [2018-06-25 23:00:46,301] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-25 23:00:46,301] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-25 23:00:46,302] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-25 23:00:46,302] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-25 23:00:46,303] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-25 23:00:46,303] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-25 23:00:46,303] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-25 23:00:46,303] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-25 23:00:46,304] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-25 23:00:46,304] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-25 23:00:46,322] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-25 23:00:46,322] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-25 23:00:46,622] - ThreadPool::destroy(): waiting for thread(2)[0x186e1e0,0x186e178,], try=1
  INFO root [2018-06-25 23:01:00,668] - 
  INFO root [2018-06-25 23:01:00,669] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-25 23:01:00,671] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-25 23:01:00,672] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-25 23:01:00,673] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-25 23:01:00,686] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-25 23:01:00,687] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-25 23:01:00,702] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:16167 )
  INFO root [2018-06-25 23:01:00,703] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:16167, SOMAXCONN=128.
  INFO root [2018-06-25 23:01:00,703] - server-configs:
  INFO root [2018-06-25 23:01:00,704] - 	internalAddr : 192.168.31.56:16167
  INFO root [2018-06-25 23:01:00,704] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-25 23:01:00,704] - 	componentID : 9000
  INFO root [2018-06-25 23:01:02,806] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 32394. PID: 8684 ----
  INFO root [2018-06-25 23:01:02,807] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-25 23:01:02,807] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-25 23:01:02,808] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-25 23:01:02,998] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-25 23:01:03,000] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-25 23:01:03,001] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-25 23:01:03,009] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-25 23:01:03,010] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-25 23:01:03,011] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-25 23:01:03,013] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-25 23:01:03,121] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-25 23:01:03,235] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-25 23:01:03,236] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-25 23:01:03,242] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-25 23:01:03,245] - TelnetServer server is running on port 31000
  INFO root [2018-06-25 23:01:04,422] - ---- loginapp is running ----
 DEBUG root [2018-06-25 23:01:04,423] - Components::process(): Request for the process of identity...
  INFO root [2018-06-25 23:01:11,542] - Components::findComponents: find logger(1)...
  INFO root [2018-06-25 23:01:11,586] - Components::findComponents: found logger, addr:192.168.31.56:16169
  INFO root [2018-06-25 23:01:11,586] - Components::addComponent: reset orderLog, uid=32394!
  INFO root [2018-06-25 23:01:11,587] - Components::addComponent[logger], uid=32394, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-25 23:01:11,591] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-25 23:01:11,692] - Components::findComponents: found dbmgr, addr:192.168.31.56:16164
  INFO root [2018-06-25 23:01:11,694] - Components::addComponent: reset orderLog, uid=32394!
  INFO root [2018-06-25 23:01:11,694] - Components::addComponent[dbmgr], uid=32394, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-25 23:01:11,695] - Components::findComponents: found dbmgr, addr:192.168.31.56:16164
  WARN root [2018-06-25 23:01:12,695] - Forwarding logs to logger[192.168.31.56:16169/0/0/0]...
 ERROR root [2018-06-25 23:02:54,501] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-25 23:02:54,504] - The following logs sent to logger failed:
  WARN root [2018-06-25 23:02:54,505] - ==> [2018-06-25 23:02:54 499] TCPPacketReceiver::processPendingEvents(192.168.31.56:16169): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-25 23:02:54,506] - ==> [2018-06-25 23:02:54 501] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-25 23:02:54,594] - TCPPacketReceiver::processPendingEvents(192.168.31.56:16164): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-25 23:02:54,597] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-25 23:02:54,602] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-25 23:02:54,608] - onLoginAppShutDown()
  INFO root [2018-06-25 23:02:54,608] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-25 23:02:54,608] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-25 23:02:54,609] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-25 23:02:54,610] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-25 23:02:54,610] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-25 23:02:54,610] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-25 23:02:54,611] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-25 23:02:54,611] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-25 23:02:54,611] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-25 23:02:54,612] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-25 23:02:54,633] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-25 23:02:54,634] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-25 23:02:54,934] - ThreadPool::destroy(): waiting for thread(2)[0x20e2d0,0x20e268,], try=1
  INFO root [2018-06-25 23:04:56,325] - 
  INFO root [2018-06-25 23:04:56,326] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-25 23:04:56,328] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-25 23:04:56,328] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-25 23:04:56,329] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-25 23:04:56,369] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-25 23:04:56,369] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-25 23:04:56,374] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:16223 )
  INFO root [2018-06-25 23:04:56,374] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:16223, SOMAXCONN=128.
  INFO root [2018-06-25 23:04:56,375] - server-configs:
  INFO root [2018-06-25 23:04:56,376] - 	internalAddr : 192.168.31.56:16223
  INFO root [2018-06-25 23:04:56,376] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-25 23:04:56,377] - 	componentID : 9000
  INFO root [2018-06-25 23:04:58,472] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 397. PID: 10144 ----
  INFO root [2018-06-25 23:04:58,473] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-25 23:04:58,474] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-25 23:04:58,474] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-25 23:04:58,650] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-25 23:04:58,652] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-25 23:04:58,653] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-25 23:04:58,661] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-25 23:04:58,661] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-25 23:04:58,662] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-25 23:04:58,663] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-25 23:04:58,834] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-25 23:04:59,029] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-25 23:04:59,030] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-25 23:04:59,035] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-25 23:04:59,037] - TelnetServer server is running on port 31000
  INFO root [2018-06-25 23:05:00,122] - ---- loginapp is running ----
 DEBUG root [2018-06-25 23:05:00,123] - Components::process(): Request for the process of identity...
  INFO root [2018-06-25 23:05:07,252] - Components::findComponents: find logger(1)...
  INFO root [2018-06-25 23:05:07,350] - Components::findComponents: found logger, addr:192.168.31.56:16226
  INFO root [2018-06-25 23:05:07,351] - Components::addComponent: reset orderLog, uid=397!
  INFO root [2018-06-25 23:05:07,351] - Components::addComponent[logger], uid=397, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-25 23:05:07,352] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-25 23:05:07,454] - Components::findComponents: found dbmgr, addr:192.168.31.56:16221
  INFO root [2018-06-25 23:05:07,455] - Components::addComponent: reset orderLog, uid=397!
  INFO root [2018-06-25 23:05:07,455] - Components::addComponent[dbmgr], uid=397, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-25 23:05:07,455] - Components::findComponents: found dbmgr, addr:192.168.31.56:16221
  WARN root [2018-06-25 23:05:08,455] - Forwarding logs to logger[192.168.31.56:16226/0/0/0]...
 ERROR root [2018-06-25 23:06:29,267] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-25 23:06:29,270] - The following logs sent to logger failed:
  WARN root [2018-06-25 23:06:29,270] - ==> [2018-06-25 23:06:29 264] TCPPacketReceiver::processPendingEvents(192.168.31.56:16226): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-25 23:06:29,271] - ==> [2018-06-25 23:06:29 268] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-25 23:06:29,434] - TCPPacketReceiver::processPendingEvents(192.168.31.56:16221): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-25 23:06:29,437] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-25 23:06:29,455] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-25 23:06:29,464] - onLoginAppShutDown()
  INFO root [2018-06-25 23:06:29,465] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-25 23:06:29,465] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-25 23:06:29,465] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-25 23:06:29,466] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-25 23:06:29,466] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-25 23:06:29,466] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-25 23:06:29,467] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-25 23:06:29,467] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-25 23:06:29,467] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-25 23:06:29,467] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-25 23:06:29,484] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-25 23:06:29,484] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-25 23:06:29,784] - ThreadPool::destroy(): waiting for thread(2)[0x1a9e2b0,0x1a9e248,], try=1
  INFO root [2018-06-25 23:06:39,513] - 
  INFO root [2018-06-25 23:06:39,514] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-25 23:06:39,516] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-25 23:06:39,517] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-25 23:06:39,517] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-25 23:06:39,537] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-25 23:06:39,537] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-25 23:06:39,547] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:16287 )
  INFO root [2018-06-25 23:06:39,548] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:16287, SOMAXCONN=128.
  INFO root [2018-06-25 23:06:39,548] - server-configs:
  INFO root [2018-06-25 23:06:39,548] - 	internalAddr : 192.168.31.56:16287
  INFO root [2018-06-25 23:06:39,549] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-25 23:06:39,549] - 	componentID : 9000
  INFO root [2018-06-25 23:06:40,588] - Components::findLogger: found logger, addr:192.168.31.56:16283
  INFO root [2018-06-25 23:06:40,589] - Components::addComponent: reset orderLog, uid=733!
  INFO root [2018-06-25 23:06:40,589] - Components::addComponent[logger], uid=733, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-25 23:06:40,600] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 733. PID: 9284 ----
  INFO root [2018-06-25 23:06:40,601] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-25 23:06:40,601] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-25 23:06:40,602] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-25 23:06:40,761] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-25 23:06:40,762] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-25 23:06:40,763] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-25 23:06:40,768] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-25 23:06:40,769] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-25 23:06:40,769] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-25 23:06:40,771] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-25 23:06:40,833] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-25 23:06:40,896] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-25 23:06:40,896] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-25 23:06:40,899] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-25 23:06:40,901] - TelnetServer server is running on port 31000
  INFO root [2018-06-25 23:06:42,798] - ---- loginapp is running ----
 DEBUG root [2018-06-25 23:06:42,800] - Components::process(): Request for the process of identity...
  WARN root [2018-06-25 23:06:48,941] - Forwarding logs to logger[192.168.31.56:16283/0/0/0]...
