  INFO root [2018-06-30 19:02:10,290] - 
  INFO root [2018-06-30 19:02:10,291] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-30 19:02:10,292] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-30 19:02:10,293] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-30 19:02:10,294] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-30 19:02:10,307] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-30 19:02:10,307] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-30 19:02:10,312] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:18286 )
  INFO root [2018-06-30 19:02:10,312] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:18286, SOMAXCONN=128.
  INFO root [2018-06-30 19:02:10,313] - server-configs:
  INFO root [2018-06-30 19:02:10,313] - 	internalAddr : 192.168.31.56:18286
  INFO root [2018-06-30 19:02:10,313] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-30 19:02:10,313] - 	componentID : 9000
  INFO root [2018-06-30 19:02:12,428] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 20073. PID: 9808 ----
  INFO root [2018-06-30 19:02:12,429] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-30 19:02:12,430] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-30 19:02:12,431] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-30 19:02:12,606] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-30 19:02:12,608] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-30 19:02:12,609] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-30 19:02:12,616] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-30 19:02:12,617] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-30 19:02:12,617] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-30 19:02:12,619] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-30 19:02:12,710] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-30 19:02:12,807] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-30 19:02:12,807] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-30 19:02:12,813] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-30 19:02:12,814] - TelnetServer server is running on port 31000
  INFO root [2018-06-30 19:02:14,138] - ---- loginapp is running ----
 DEBUG root [2018-06-30 19:02:14,140] - Components::process(): Request for the process of identity...
  WARN root [2018-06-30 19:02:14,453] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20112, errorno=10048
  INFO root [2018-06-30 19:02:21,634] - Components::findComponents: find logger(1)...
  INFO root [2018-06-30 19:02:21,671] - Components::findComponents: found logger, addr:192.168.31.56:18291
  INFO root [2018-06-30 19:02:21,671] - Components::addComponent: reset orderLog, uid=20073!
  INFO root [2018-06-30 19:02:21,671] - Components::addComponent[logger], uid=20073, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-30 19:02:21,673] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-30 19:02:21,773] - Components::findComponents: found dbmgr, addr:192.168.31.56:18293
  INFO root [2018-06-30 19:02:21,774] - Components::addComponent: reset orderLog, uid=20073!
  INFO root [2018-06-30 19:02:21,774] - Components::addComponent[dbmgr], uid=20073, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-30 19:02:21,774] - Components::findComponents: found dbmgr, addr:192.168.31.56:18293
  WARN root [2018-06-30 19:02:22,774] - Forwarding logs to logger[192.168.31.56:18291/0/0/0]...
 ERROR root [2018-06-30 20:18:17,574] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-30 20:18:17,577] - The following logs sent to logger failed:
  WARN root [2018-06-30 20:18:17,579] - ==> [2018-06-30 20:18:17 573] TCPPacketReceiver::processPendingEvents(192.168.31.56:18291): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-30 20:18:17,580] - ==> [2018-06-30 20:18:17 575] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-30 20:18:17,683] - TCPPacketReceiver::processPendingEvents(192.168.31.56:18293): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-30 20:18:17,687] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-30 20:18:17,691] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-30 20:18:17,694] - onLoginAppShutDown()
  INFO root [2018-06-30 20:18:17,694] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-30 20:18:17,695] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-30 20:18:17,695] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-30 20:18:17,696] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-30 20:18:17,696] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-30 20:18:17,697] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-30 20:18:17,697] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-30 20:18:17,698] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-30 20:18:17,698] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-30 20:18:17,698] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-30 20:18:17,719] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-30 20:18:17,719] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-30 20:18:18,020] - ThreadPool::destroy(): waiting for thread(2)[0x4f02f0,0x4f0288,], try=1
  INFO root [2018-06-30 20:18:50,070] - 
  INFO root [2018-06-30 20:18:50,071] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-30 20:18:50,072] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-30 20:18:50,073] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-30 20:18:50,073] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-30 20:18:50,081] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-30 20:18:50,082] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-30 20:18:50,084] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20613 )
  INFO root [2018-06-30 20:18:50,084] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:20613, SOMAXCONN=128.
  INFO root [2018-06-30 20:18:50,085] - server-configs:
  INFO root [2018-06-30 20:18:50,085] - 	internalAddr : 192.168.31.56:20613
  INFO root [2018-06-30 20:18:50,085] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-30 20:18:50,085] - 	componentID : 9000
  INFO root [2018-06-30 20:18:51,995] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 2326. PID: 12264 ----
  INFO root [2018-06-30 20:18:52,009] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-30 20:18:52,010] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-30 20:18:52,011] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-30 20:18:52,223] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-30 20:18:52,225] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-30 20:18:52,226] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-30 20:18:52,233] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-30 20:18:52,234] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-30 20:18:52,235] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-30 20:18:52,236] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-30 20:18:52,398] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-30 20:18:52,487] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-30 20:18:52,488] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-30 20:18:52,493] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-30 20:18:52,495] - TelnetServer server is running on port 31000
  INFO root [2018-06-30 20:18:54,205] - ---- loginapp is running ----
 DEBUG root [2018-06-30 20:18:54,205] - Components::process(): Request for the process of identity...
  INFO root [2018-06-30 20:19:01,334] - Components::findComponents: find logger(1)...
  INFO root [2018-06-30 20:19:01,397] - Components::findComponents: found logger, addr:192.168.31.56:20616
  INFO root [2018-06-30 20:19:01,397] - Components::addComponent: reset orderLog, uid=2326!
  INFO root [2018-06-30 20:19:01,397] - Components::addComponent[logger], uid=2326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-30 20:19:01,399] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-30 20:19:01,509] - Components::findComponents: found dbmgr, addr:192.168.31.56:20619
  INFO root [2018-06-30 20:19:01,509] - Components::addComponent: reset orderLog, uid=2326!
  INFO root [2018-06-30 20:19:01,509] - Components::addComponent[dbmgr], uid=2326, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-30 20:19:01,511] - Components::findComponents: found dbmgr, addr:192.168.31.56:20619
  WARN root [2018-06-30 20:19:02,511] - Forwarding logs to logger[192.168.31.56:20616/0/0/0]...
 ERROR root [2018-06-30 20:21:55,194] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-30 20:21:55,209] - The following logs sent to logger failed:
  WARN root [2018-06-30 20:21:55,210] - ==> [2018-06-30 20:21:55 194] TCPPacketReceiver::processPendingEvents(192.168.31.56:20616): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-30 20:21:55,210] - ==> [2018-06-30 20:21:55 195] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-30 20:21:55,314] - TCPPacketReceiver::processPendingEvents(192.168.31.56:20619): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-30 20:21:55,318] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-30 20:21:55,319] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-30 20:21:55,321] - onLoginAppShutDown()
  INFO root [2018-06-30 20:21:55,321] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-30 20:21:55,322] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-30 20:21:55,325] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-30 20:21:55,325] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-30 20:21:55,325] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-30 20:21:55,325] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-30 20:21:55,326] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-30 20:21:55,326] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-30 20:21:55,326] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-30 20:21:55,328] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-30 20:21:55,349] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-30 20:21:55,349] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-30 20:21:55,649] - ThreadPool::destroy(): waiting for thread(2)[0x52de00,0x52dd98,], try=1
  INFO root [2018-06-30 20:22:13,231] - 
  INFO root [2018-06-30 20:22:13,237] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-30 20:22:13,239] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-30 20:22:13,239] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-30 20:22:13,240] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-30 20:22:13,257] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-30 20:22:13,257] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-30 20:22:13,262] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20799 )
  INFO root [2018-06-30 20:22:13,263] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:20799, SOMAXCONN=128.
  INFO root [2018-06-30 20:22:13,263] - server-configs:
  INFO root [2018-06-30 20:22:13,263] - 	internalAddr : 192.168.31.56:20799
  INFO root [2018-06-30 20:22:13,263] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-30 20:22:13,264] - 	componentID : 9000
  INFO root [2018-06-30 20:22:14,424] - Components::findLogger: found logger, addr:192.168.31.56:20794
  INFO root [2018-06-30 20:22:14,425] - Components::addComponent: reset orderLog, uid=2989!
  INFO root [2018-06-30 20:22:14,425] - Components::addComponent[logger], uid=2989, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-30 20:22:14,433] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 2989. PID: 4612 ----
  INFO root [2018-06-30 20:22:14,433] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-30 20:22:14,434] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-30 20:22:14,434] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-30 20:22:14,578] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-30 20:22:14,578] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-30 20:22:14,579] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-30 20:22:14,584] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-30 20:22:14,584] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-30 20:22:14,584] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-30 20:22:14,585] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-30 20:22:14,635] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-30 20:22:14,687] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-30 20:22:14,687] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-30 20:22:14,691] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-30 20:22:14,692] - TelnetServer server is running on port 31000
  INFO root [2018-06-30 20:22:15,719] - ---- loginapp is running ----
 DEBUG root [2018-06-30 20:22:15,720] - Components::process(): Request for the process of identity...
  INFO root [2018-06-30 20:22:21,779] - 
  INFO root [2018-06-30 20:22:21,784] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-30 20:22:21,785] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-30 20:22:21,786] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-30 20:22:21,787] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-30 20:22:21,823] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-30 20:22:21,823] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-30 20:22:21,829] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20816 )
  INFO root [2018-06-30 20:22:21,829] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:20816, SOMAXCONN=128.
  INFO root [2018-06-30 20:22:21,830] - server-configs:
  INFO root [2018-06-30 20:22:21,830] - 	internalAddr : 192.168.31.56:20816
  INFO root [2018-06-30 20:22:21,830] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-30 20:22:21,830] - 	componentID : 9000
  INFO root [2018-06-30 20:22:22,789] - Components::findLogger: found logger, addr:192.168.31.56:20813
  INFO root [2018-06-30 20:22:22,790] - Components::addComponent: reset orderLog, uid=3015!
  INFO root [2018-06-30 20:22:22,790] - Components::addComponent[logger], uid=3015, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-30 20:22:22,798] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 3015. PID: 8764 ----
  INFO root [2018-06-30 20:22:22,798] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-30 20:22:22,798] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-30 20:22:22,799] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-30 20:22:22,945] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-30 20:22:22,945] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-30 20:22:22,946] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-30 20:22:22,952] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-30 20:22:22,952] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-30 20:22:22,952] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-30 20:22:22,953] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-30 20:22:23,013] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-30 20:22:23,075] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-30 20:22:23,076] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-30 20:22:23,079] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-30 20:22:23,080] - TelnetServer server is running on port 31000
  INFO root [2018-06-30 20:22:23,931] - ---- loginapp is running ----
 DEBUG root [2018-06-30 20:22:23,931] - Components::process(): Request for the process of identity...
  WARN root [2018-06-30 20:22:30,162] - Forwarding logs to logger[192.168.31.56:20813/0/0/0]...
 ERROR root [2018-06-30 22:12:12,032] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-30 22:12:12,043] - The following logs sent to logger failed:
  WARN root [2018-06-30 22:12:12,044] - ==> [2018-06-30 22:12:12 030] TCPPacketReceiver::processPendingEvents(192.168.31.56:20813): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-30 22:12:12,044] - ==> [2018-06-30 22:12:12 033] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-30 22:12:12,144] - TCPPacketReceiver::processPendingEvents(192.168.31.56:20817): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-30 22:12:12,146] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-30 22:12:12,153] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-30 22:12:12,154] - onLoginAppShutDown()
  INFO root [2018-06-30 22:12:12,154] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-30 22:12:12,154] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-30 22:12:12,155] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-30 22:12:12,155] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-30 22:12:12,156] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-30 22:12:12,156] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-30 22:12:12,156] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-30 22:12:12,156] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-30 22:12:12,157] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-30 22:12:12,157] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-30 22:12:12,176] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-30 22:12:12,176] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-30 22:12:12,477] - ThreadPool::destroy(): waiting for thread(2)[0x2ede00,0x2edd98,], try=1
  INFO root [2018-06-30 22:12:13,722] - 
  INFO root [2018-06-30 22:12:13,723] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-30 22:12:13,724] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-30 22:12:13,724] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-30 22:12:13,725] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-30 22:12:13,733] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-30 22:12:13,734] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-30 22:12:13,756] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:24230 )
  INFO root [2018-06-30 22:12:13,756] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:24230, SOMAXCONN=128.
  INFO root [2018-06-30 22:12:13,756] - server-configs:
  INFO root [2018-06-30 22:12:13,756] - 	internalAddr : 192.168.31.56:24230
  INFO root [2018-06-30 22:12:13,757] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-30 22:12:13,757] - 	componentID : 9000
  INFO root [2018-06-30 22:12:15,677] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 24542. PID: 4944 ----
  INFO root [2018-06-30 22:12:15,679] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-30 22:12:15,680] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-30 22:12:15,680] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-30 22:12:15,870] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-30 22:12:15,871] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-30 22:12:15,874] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-30 22:12:15,881] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-30 22:12:15,882] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-30 22:12:15,882] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-30 22:12:15,884] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-30 22:12:16,043] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-30 22:12:16,137] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-30 22:12:16,137] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-30 22:12:16,143] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-30 22:12:16,144] - TelnetServer server is running on port 31000
  INFO root [2018-06-30 22:12:17,487] - ---- loginapp is running ----
 DEBUG root [2018-06-30 22:12:17,488] - Components::process(): Request for the process of identity...
  INFO root [2018-06-30 22:12:24,664] - Components::findComponents: find logger(1)...
  INFO root [2018-06-30 22:12:24,717] - Components::findComponents: found logger, addr:192.168.31.56:24235
  INFO root [2018-06-30 22:12:24,718] - Components::addComponent: reset orderLog, uid=24542!
  INFO root [2018-06-30 22:12:24,718] - Components::addComponent[logger], uid=24542, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-30 22:12:24,720] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-30 22:12:24,829] - Components::findComponents: found dbmgr, addr:192.168.31.56:24236
  INFO root [2018-06-30 22:12:24,829] - Components::addComponent: reset orderLog, uid=24542!
  INFO root [2018-06-30 22:12:24,829] - Components::addComponent[dbmgr], uid=24542, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-30 22:12:24,830] - Components::findComponents: found dbmgr, addr:192.168.31.56:24236
  WARN root [2018-06-30 22:12:25,830] - Forwarding logs to logger[192.168.31.56:24235/0/0/0]...
 ERROR root [2018-06-30 23:19:22,711] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-30 23:19:22,713] - The following logs sent to logger failed:
  WARN root [2018-06-30 23:19:22,714] - ==> [2018-06-30 23:19:22 711] TCPPacketReceiver::processPendingEvents(192.168.31.56:24235): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-30 23:19:22,714] - ==> [2018-06-30 23:19:22 711] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-30 23:19:22,825] - TCPPacketReceiver::processPendingEvents(192.168.31.56:24236): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-30 23:19:22,826] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-30 23:19:22,828] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-30 23:19:22,833] - onLoginAppShutDown()
  INFO root [2018-06-30 23:19:22,833] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-30 23:19:22,834] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-30 23:19:22,835] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-30 23:19:22,835] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-30 23:19:22,835] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-30 23:19:22,836] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-30 23:19:22,836] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-30 23:19:22,836] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-30 23:19:22,837] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-30 23:19:22,837] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-30 23:19:22,857] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-30 23:19:22,858] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-06-30 23:19:23,158] - ThreadPool::destroy(): waiting for thread(2)[0x69e2d0,0x69e268,], try=1
  INFO root [2018-06-30 23:19:24,394] - 
  INFO root [2018-06-30 23:19:24,395] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-30 23:19:24,396] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-06-30 23:19:24,396] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-06-30 23:19:24,396] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-06-30 23:19:24,405] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-06-30 23:19:24,405] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-06-30 23:19:24,408] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:25025 )
  INFO root [2018-06-30 23:19:24,409] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:25025, SOMAXCONN=128.
  INFO root [2018-06-30 23:19:24,409] - server-configs:
  INFO root [2018-06-30 23:19:24,409] - 	internalAddr : 192.168.31.56:25025
  INFO root [2018-06-30 23:19:24,409] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-06-30 23:19:24,409] - 	componentID : 9000
  INFO root [2018-06-30 23:19:26,358] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 4938. PID: 4340 ----
  INFO root [2018-06-30 23:19:26,361] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-06-30 23:19:26,362] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-30 23:19:26,363] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-30 23:19:26,526] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-30 23:19:26,528] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-30 23:19:26,529] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-30 23:19:26,536] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-30 23:19:26,536] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-30 23:19:26,537] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-30 23:19:26,538] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-30 23:19:26,602] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-30 23:19:26,691] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-30 23:19:26,691] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-30 23:19:26,696] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-30 23:19:26,698] - TelnetServer server is running on port 31000
  INFO root [2018-06-30 23:19:29,203] - ---- loginapp is running ----
 DEBUG root [2018-06-30 23:19:29,205] - Components::process(): Request for the process of identity...
  INFO root [2018-06-30 23:19:36,496] - Components::findComponents: find logger(1)...
  INFO root [2018-06-30 23:19:36,512] - Components::findComponents: found logger, addr:192.168.31.56:25033
  INFO root [2018-06-30 23:19:36,513] - Components::addComponent: reset orderLog, uid=4938!
  INFO root [2018-06-30 23:19:36,513] - Components::addComponent[logger], uid=4938, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-30 23:19:36,517] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-30 23:19:36,620] - Components::findComponents: found dbmgr, addr:192.168.31.56:25030
  INFO root [2018-06-30 23:19:36,620] - Components::addComponent: reset orderLog, uid=4938!
  INFO root [2018-06-30 23:19:36,621] - Components::addComponent[dbmgr], uid=4938, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-30 23:19:36,621] - Components::findComponents: found dbmgr, addr:192.168.31.56:25030
  WARN root [2018-06-30 23:19:37,623] - Forwarding logs to logger[192.168.31.56:25033/0/0/0]...
