  INFO root [2018-07-02 15:14:26,105] - 
  INFO root [2018-07-02 15:14:26,106] - -----------------------------------------------------------------------------------------


  INFO root [2018-07-02 15:14:28,710] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-07-02 15:14:28,711] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-07-02 15:14:28,711] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-07-02 15:14:28,993] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-07-02 15:14:28,994] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-07-02 15:14:28,996] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:10995 )
  INFO root [2018-07-02 15:14:28,997] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:10995, SOMAXCONN=128.
  INFO root [2018-07-02 15:14:28,997] - server-configs:
  INFO root [2018-07-02 15:14:28,997] - 	internalAddr : 192.168.31.56:10995
  INFO root [2018-07-02 15:14:28,997] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-07-02 15:14:28,997] - 	componentID : 9000
  INFO root [2018-07-02 15:14:31,427] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 15410. PID: 1996 ----
  INFO root [2018-07-02 15:14:31,428] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-07-02 15:14:31,487] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-07-02 15:14:31,487] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-07-02 15:14:35,773] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-02 15:14:35,921] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-07-02 15:14:36,231] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-02 15:14:37,751] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-02 15:14:37,821] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-07-02 15:14:37,877] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-02 15:14:38,092] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-02 15:14:38,771] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-02 15:14:40,855] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-07-02 15:14:40,856] - Script::install(): KBExtra is successfully!
S_INFO root [2018-07-02 15:14:41,104] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-07-02 15:14:41,155] - TelnetServer server is running on port 31000
  INFO root [2018-07-02 15:14:42,142] - ---- loginapp is running ----
 DEBUG root [2018-07-02 15:14:42,182] - Components::process(): Request for the process of identity...
  INFO root [2018-07-02 15:14:49,505] - Components::findComponents: find logger(1)...
  INFO root [2018-07-02 15:14:49,510] - Components::findComponents: found logger, addr:192.168.31.56:10989
  INFO root [2018-07-02 15:14:49,511] - Components::addComponent: reset orderLog, uid=15410!
  INFO root [2018-07-02 15:14:49,511] - Components::addComponent[logger], uid=15410, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-07-02 15:14:49,512] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-07-02 15:14:49,614] - Components::findComponents: found dbmgr, addr:192.168.31.56:10993
  INFO root [2018-07-02 15:14:49,615] - Components::addComponent: reset orderLog, uid=15410!
  INFO root [2018-07-02 15:14:49,615] - Components::addComponent[dbmgr], uid=15410, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-07-02 15:14:49,616] - Components::findComponents: found dbmgr, addr:192.168.31.56:10993
  WARN root [2018-07-02 15:14:50,616] - Forwarding logs to logger[192.168.31.56:10989/0/0/0]...
  INFO root [2018-07-02 16:30:53,941] - 
  INFO root [2018-07-02 16:30:53,941] - -----------------------------------------------------------------------------------------


  INFO root [2018-07-02 16:30:53,943] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-07-02 16:30:53,943] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-07-02 16:30:53,944] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-07-02 16:30:53,955] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-07-02 16:30:53,956] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-07-02 16:30:53,960] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:12247 )
  INFO root [2018-07-02 16:30:53,961] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:12247, SOMAXCONN=128.
  INFO root [2018-07-02 16:30:53,961] - server-configs:
  INFO root [2018-07-02 16:30:53,961] - 	internalAddr : 192.168.31.56:12247
  INFO root [2018-07-02 16:30:53,961] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-07-02 16:30:53,962] - 	componentID : 9000
  INFO root [2018-07-02 16:30:56,069] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 30435. PID: 10492 ----
  INFO root [2018-07-02 16:30:56,070] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-07-02 16:30:56,071] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-07-02 16:30:56,071] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-07-02 16:30:56,269] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-02 16:30:56,271] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-07-02 16:30:56,304] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-02 16:30:56,311] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-02 16:30:56,312] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-07-02 16:30:56,312] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-02 16:30:56,313] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-02 16:30:56,455] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-02 16:30:56,630] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-07-02 16:30:56,630] - Script::install(): KBExtra is successfully!
S_INFO root [2018-07-02 16:30:56,635] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-07-02 16:30:56,636] - TelnetServer server is running on port 31001
  INFO root [2018-07-02 16:30:58,016] - ---- loginapp is running ----
 DEBUG root [2018-07-02 16:30:58,017] - Components::process(): Request for the process of identity...
 ERROR root [2018-07-02 16:30:58,164] - Components::process: found loginapp, addr:192.168.31.56:10995
 ERROR root [2018-07-02 16:30:58,165] - ServerApp::onIdentityillegal: The current process and loginapp(componentID=9000 ->conflicted???, pid=1996, addr=192.168.31.56) conflict, the process will exit!
Can modify the components-CID and UID to avoid conflict.
  INFO root [2018-07-02 16:30:58,166] - Shutdowner::onShutdownBegin: shutting down(period=1, tickPeriod=1)
S_INFO root [2018-07-02 16:30:58,167] - onLoginAppShutDown()
  INFO root [2018-07-02 16:30:59,186] - Shutdowner::onShutdown: shutting down
  INFO root [2018-07-02 16:31:00,188] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-07-02 16:31:00,188] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-02 16:31:00,189] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-07-02 16:31:00,189] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-02 16:31:00,189] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-02 16:31:00,189] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-07-02 16:31:00,189] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-02 16:31:00,189] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-02 16:31:00,189] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-02 16:31:00,201] - Script::uninstall(): is successfully!
 DEBUG root [2018-07-02 16:31:00,201] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-07-02 16:31:00,501] - ThreadPool::destroy(): waiting for thread(2)[0x154ae08,0x154ada0,], try=1
 DEBUG root [2018-07-02 16:31:00,901] - TPThread::~TPThread(): 0x154ae08
 DEBUG root [2018-07-02 16:31:00,901] - TPThread::~TPThread(): 0x154ada0
 DEBUG root [2018-07-02 16:31:00,901] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-07-02 16:31:00,965] - Bundle::destroyObjPool(): size 14.
 DEBUG root [2018-07-02 16:31:00,965] - Channel::destroyObjPool(): size 0.
 DEBUG root [2018-07-02 16:31:00,976] - TCPPacket::destroyObjPool(): size 0.
 DEBUG root [2018-07-02 16:31:00,976] - UDPPacket::destroyObjPool(): size 12.
 DEBUG root [2018-07-02 16:31:00,976] - EndPoint::destroyObjPool(): size 0.
 DEBUG root [2018-07-02 16:31:00,976] - Address::destroyObjPool(): size 0.
 DEBUG root [2018-07-02 16:31:00,976] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2018-07-02 16:31:00,976] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2018-07-02 16:31:00,977] - loginapp(9000) has shut down.
  INFO root [2018-07-02 16:31:01,988] - EventDispatcher()::~EventDispatcher: Num timers = 2
  INFO root [2018-07-02 16:31:07,087] - 
  INFO root [2018-07-02 16:31:07,088] - -----------------------------------------------------------------------------------------


  INFO root [2018-07-02 16:31:07,090] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-07-02 16:31:07,091] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-07-02 16:31:07,091] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-07-02 16:31:07,105] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-07-02 16:31:07,105] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-07-02 16:31:07,108] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:12266 )
  INFO root [2018-07-02 16:31:07,108] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:12266, SOMAXCONN=128.
  INFO root [2018-07-02 16:31:07,109] - server-configs:
  INFO root [2018-07-02 16:31:07,109] - 	internalAddr : 192.168.31.56:12266
  INFO root [2018-07-02 16:31:07,109] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-07-02 16:31:07,109] - 	componentID : 9000
  INFO root [2018-07-02 16:31:09,113] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 30481. PID: 9284 ----
  INFO root [2018-07-02 16:31:09,114] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-07-02 16:31:09,115] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-07-02 16:31:09,116] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-07-02 16:31:09,343] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-02 16:31:09,345] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-07-02 16:31:09,345] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-02 16:31:09,353] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-02 16:31:09,354] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-07-02 16:31:09,354] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-02 16:31:09,356] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-02 16:31:09,558] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-02 16:31:09,814] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-07-02 16:31:09,814] - Script::install(): KBExtra is successfully!
S_INFO root [2018-07-02 16:31:09,820] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-07-02 16:31:09,856] - TelnetServer server is running on port 31001
  INFO root [2018-07-02 16:31:11,627] - ---- loginapp is running ----
 DEBUG root [2018-07-02 16:31:11,628] - Components::process(): Request for the process of identity...
 ERROR root [2018-07-02 16:31:11,757] - Components::process: found loginapp, addr:192.168.31.56:10995
 ERROR root [2018-07-02 16:31:11,759] - ServerApp::onIdentityillegal: The current process and loginapp(componentID=9000 ->conflicted???, pid=1996, addr=192.168.31.56) conflict, the process will exit!
Can modify the components-CID and UID to avoid conflict.
  INFO root [2018-07-02 16:31:11,761] - Shutdowner::onShutdownBegin: shutting down(period=1, tickPeriod=1)
S_INFO root [2018-07-02 16:31:11,762] - onLoginAppShutDown()
  INFO root [2018-07-02 16:31:12,762] - Shutdowner::onShutdown: shutting down
  INFO root [2018-07-02 16:31:13,763] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-07-02 16:31:13,763] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-02 16:31:13,763] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-07-02 16:31:13,764] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-02 16:31:13,764] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-02 16:31:13,764] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-07-02 16:31:13,764] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-02 16:31:13,764] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-02 16:31:13,764] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-02 16:31:13,775] - Script::uninstall(): is successfully!
 DEBUG root [2018-07-02 16:31:13,776] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-07-02 16:31:14,076] - ThreadPool::destroy(): waiting for thread(2)[0x185bdf0,0x185bd88,], try=1
 DEBUG root [2018-07-02 16:31:14,476] - TPThread::~TPThread(): 0x185bdf0
 DEBUG root [2018-07-02 16:31:14,476] - TPThread::~TPThread(): 0x185bd88
 DEBUG root [2018-07-02 16:31:14,476] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-07-02 16:31:14,488] - Bundle::destroyObjPool(): size 14.
 DEBUG root [2018-07-02 16:31:14,488] - Channel::destroyObjPool(): size 0.
 DEBUG root [2018-07-02 16:31:14,488] - TCPPacket::destroyObjPool(): size 0.
 DEBUG root [2018-07-02 16:31:14,488] - UDPPacket::destroyObjPool(): size 12.
 DEBUG root [2018-07-02 16:31:14,488] - EndPoint::destroyObjPool(): size 0.
 DEBUG root [2018-07-02 16:31:14,489] - Address::destroyObjPool(): size 0.
 DEBUG root [2018-07-02 16:31:14,489] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2018-07-02 16:31:14,489] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2018-07-02 16:31:14,489] - loginapp(9000) has shut down.
  INFO root [2018-07-02 16:31:15,489] - EventDispatcher()::~EventDispatcher: Num timers = 2
  INFO root [2018-07-02 16:32:44,027] - 
  INFO root [2018-07-02 16:32:44,030] - -----------------------------------------------------------------------------------------


  INFO root [2018-07-02 16:32:44,031] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-07-02 16:32:44,031] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-07-02 16:32:44,031] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-07-02 16:32:44,121] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-07-02 16:32:44,122] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-07-02 16:32:44,126] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:12318 )
  INFO root [2018-07-02 16:32:44,127] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:12318, SOMAXCONN=128.
  INFO root [2018-07-02 16:32:44,127] - server-configs:
  INFO root [2018-07-02 16:32:44,127] - 	internalAddr : 192.168.31.56:12318
  INFO root [2018-07-02 16:32:44,127] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-07-02 16:32:44,128] - 	componentID : 9000
  WARN root [2018-07-02 16:32:44,950] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20936, errorno=10048
  INFO root [2018-07-02 16:32:44,957] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 30794. PID: 7540 ----
  INFO root [2018-07-02 16:32:44,957] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-07-02 16:32:44,958] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-07-02 16:32:44,958] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-07-02 16:32:45,103] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-02 16:32:45,104] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-07-02 16:32:45,105] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-02 16:32:45,109] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-02 16:32:45,110] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-07-02 16:32:45,110] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-02 16:32:45,111] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-02 16:32:45,171] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-02 16:32:45,229] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-07-02 16:32:45,229] - Script::install(): KBExtra is successfully!
S_INFO root [2018-07-02 16:32:45,232] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-07-02 16:32:45,233] - TelnetServer server is running on port 31001
  INFO root [2018-07-02 16:32:45,769] - ---- loginapp is running ----
 DEBUG root [2018-07-02 16:32:45,769] - Components::process(): Request for the process of identity...
 ERROR root [2018-07-02 16:32:45,904] - Components::process: found loginapp, addr:192.168.31.56:10995
 ERROR root [2018-07-02 16:32:45,905] - ServerApp::onIdentityillegal: The current process and loginapp(componentID=9000 ->conflicted???, pid=1996, addr=192.168.31.56) conflict, the process will exit!
Can modify the components-CID and UID to avoid conflict.
  INFO root [2018-07-02 16:32:45,908] - Shutdowner::onShutdownBegin: shutting down(period=1, tickPeriod=1)
S_INFO root [2018-07-02 16:32:45,909] - onLoginAppShutDown()
  INFO root [2018-07-02 16:32:46,909] - Shutdowner::onShutdown: shutting down
  INFO root [2018-07-02 16:32:47,910] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-07-02 16:32:47,911] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-02 16:32:47,911] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-07-02 16:32:47,912] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-02 16:32:47,912] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-02 16:32:47,912] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-07-02 16:32:47,912] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-02 16:32:47,913] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-02 16:32:47,913] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-02 16:32:47,931] - Script::uninstall(): is successfully!
 DEBUG root [2018-07-02 16:32:47,931] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-07-02 16:32:48,231] - ThreadPool::destroy(): waiting for thread(2)[0x198be58,0x198bdf0,], try=1
 DEBUG root [2018-07-02 16:32:48,632] - TPThread::~TPThread(): 0x198be58
 DEBUG root [2018-07-02 16:32:48,632] - TPThread::~TPThread(): 0x198bdf0
 DEBUG root [2018-07-02 16:32:48,632] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-07-02 16:32:48,644] - Bundle::destroyObjPool(): size 13.
 DEBUG root [2018-07-02 16:32:48,644] - Channel::destroyObjPool(): size 0.
 DEBUG root [2018-07-02 16:32:48,645] - TCPPacket::destroyObjPool(): size 0.
 DEBUG root [2018-07-02 16:32:48,645] - UDPPacket::destroyObjPool(): size 13.
 DEBUG root [2018-07-02 16:32:48,645] - EndPoint::destroyObjPool(): size 0.
 DEBUG root [2018-07-02 16:32:48,645] - Address::destroyObjPool(): size 0.
 DEBUG root [2018-07-02 16:32:48,645] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2018-07-02 16:32:48,645] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2018-07-02 16:32:48,645] - loginapp(9000) has shut down.
  INFO root [2018-07-02 16:32:49,646] - EventDispatcher()::~EventDispatcher: Num timers = 2
  INFO root [2018-07-02 18:03:14,582] - 
  INFO root [2018-07-02 18:03:14,597] - -----------------------------------------------------------------------------------------


  INFO root [2018-07-02 18:03:14,628] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-07-02 18:03:14,628] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-07-02 18:03:14,628] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-07-02 18:03:14,660] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-07-02 18:03:14,660] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-07-02 18:03:14,660] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:1339 )
  INFO root [2018-07-02 18:03:14,660] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:1339, SOMAXCONN=128.
  INFO root [2018-07-02 18:03:14,660] - server-configs:
  INFO root [2018-07-02 18:03:14,660] - 	internalAddr : 192.168.31.56:1339
  INFO root [2018-07-02 18:03:14,660] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-07-02 18:03:14,660] - 	componentID : 9000
  INFO root [2018-07-02 18:03:16,688] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 15762. PID: 4736 ----
  INFO root [2018-07-02 18:03:16,688] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-07-02 18:03:16,688] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-07-02 18:03:16,688] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-07-02 18:03:16,859] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-02 18:03:16,875] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-07-02 18:03:16,875] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-02 18:03:16,875] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-02 18:03:16,875] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-07-02 18:03:16,875] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-02 18:03:16,875] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-02 18:03:17,000] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-02 18:03:17,124] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-07-02 18:03:17,124] - Script::install(): KBExtra is successfully!
S_INFO root [2018-07-02 18:03:17,124] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-07-02 18:03:17,124] - TelnetServer server is running on port 31000
  INFO root [2018-07-02 18:03:18,232] - ---- loginapp is running ----
 DEBUG root [2018-07-02 18:03:18,232] - Components::process(): Request for the process of identity...
  INFO root [2018-07-02 18:03:25,595] - Components::findComponents: find logger(1)...
  INFO root [2018-07-02 18:03:25,627] - Components::findComponents: found logger, addr:192.168.31.56:1345
  INFO root [2018-07-02 18:03:25,627] - Components::addComponent: reset orderLog, uid=15762!
  INFO root [2018-07-02 18:03:25,627] - Components::addComponent[logger], uid=15762, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-07-02 18:03:25,627] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-07-02 18:03:25,736] - Components::findComponents: found dbmgr, addr:192.168.31.56:1343
  INFO root [2018-07-02 18:03:25,736] - Components::addComponent: reset orderLog, uid=15762!
  INFO root [2018-07-02 18:03:25,736] - Components::addComponent[dbmgr], uid=15762, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-07-02 18:03:25,736] - Components::findComponents: found dbmgr, addr:192.168.31.56:1343
  WARN root [2018-07-02 18:03:26,750] - Forwarding logs to logger[192.168.31.56:1345/0/0/0]...
 ERROR root [2018-07-02 18:27:30,887] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-07-02 18:27:30,891] - The following logs sent to logger failed:
  WARN root [2018-07-02 18:27:30,891] - ==> [2018-07-02 18:27:30 883] TCPPacketReceiver::processPendingEvents(192.168.31.56:1345): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-07-02 18:27:30,892] - ==> [2018-07-02 18:27:30 888] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-07-02 18:27:30,986] - TCPPacketReceiver::processPendingEvents(192.168.31.56:1343): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-07-02 18:27:30,987] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-07-02 18:27:30,994] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-07-02 18:27:30,999] - onLoginAppShutDown()
  INFO root [2018-07-02 18:27:30,999] - Shutdowner::onShutdown: shutting down
  INFO root [2018-07-02 18:27:31,000] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-07-02 18:27:31,000] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-02 18:27:31,001] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-07-02 18:27:31,001] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-02 18:27:31,001] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-02 18:27:31,002] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-07-02 18:27:31,002] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-02 18:27:31,002] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-02 18:27:31,003] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-02 18:27:31,022] - Script::uninstall(): is successfully!
 DEBUG root [2018-07-02 18:27:31,023] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-07-02 18:27:31,323] - ThreadPool::destroy(): waiting for thread(2)[0x17ddd98,0x17ddd30,], try=1
  INFO root [2018-07-02 18:27:36,932] - 
  INFO root [2018-07-02 18:27:36,933] - -----------------------------------------------------------------------------------------


  INFO root [2018-07-02 18:27:36,935] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-07-02 18:27:36,935] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-07-02 18:27:36,936] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-07-02 18:27:36,990] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-07-02 18:27:36,990] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-07-02 18:27:37,007] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:1971 )
  INFO root [2018-07-02 18:27:37,008] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:1971, SOMAXCONN=128.
  INFO root [2018-07-02 18:27:37,008] - server-configs:
  INFO root [2018-07-02 18:27:37,008] - 	internalAddr : 192.168.31.56:1971
  INFO root [2018-07-02 18:27:37,009] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-07-02 18:27:37,009] - 	componentID : 9000
  INFO root [2018-07-02 18:27:37,880] - Components::findLogger: found logger, addr:192.168.31.56:1968
  INFO root [2018-07-02 18:27:37,880] - Components::addComponent: reset orderLog, uid=20536!
  INFO root [2018-07-02 18:27:37,881] - Components::addComponent[logger], uid=20536, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-07-02 18:27:37,892] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 20536. PID: 5616 ----
  INFO root [2018-07-02 18:27:37,893] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-07-02 18:27:37,894] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-07-02 18:27:37,895] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-07-02 18:27:38,098] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-02 18:27:38,100] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-07-02 18:27:38,101] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-02 18:27:38,131] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-02 18:27:38,132] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-07-02 18:27:38,132] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-02 18:27:38,134] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-02 18:27:38,220] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-02 18:27:38,314] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-07-02 18:27:38,314] - Script::install(): KBExtra is successfully!
S_INFO root [2018-07-02 18:27:38,319] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-07-02 18:27:38,332] - TelnetServer server is running on port 31000
  INFO root [2018-07-02 18:27:39,767] - ---- loginapp is running ----
 DEBUG root [2018-07-02 18:27:39,770] - Components::process(): Request for the process of identity...
  WARN root [2018-07-02 18:27:46,051] - Forwarding logs to logger[192.168.31.56:1968/0/0/0]...
 ERROR root [2018-07-02 18:39:17,152] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-07-02 18:39:17,162] - The following logs sent to logger failed:
  WARN root [2018-07-02 18:39:17,162] - ==> [2018-07-02 18:39:17 142] TCPPacketReceiver::processPendingEvents(192.168.31.56:1968): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-07-02 18:39:17,162] - ==> [2018-07-02 18:39:17 152] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-07-02 18:39:17,262] - TCPPacketReceiver::processPendingEvents(192.168.31.56:1969): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-07-02 18:39:17,272] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-07-02 18:39:17,282] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-07-02 18:39:17,282] - onLoginAppShutDown()
  INFO root [2018-07-02 18:39:17,282] - Shutdowner::onShutdown: shutting down
  INFO root [2018-07-02 18:39:17,282] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-07-02 18:39:17,282] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-02 18:39:17,282] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-07-02 18:39:17,282] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-02 18:39:17,282] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-02 18:39:17,282] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-07-02 18:39:17,282] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-02 18:39:17,282] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-02 18:39:17,282] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-02 18:39:17,302] - Script::uninstall(): is successfully!
 DEBUG root [2018-07-02 18:39:17,302] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-07-02 18:39:17,602] - ThreadPool::destroy(): waiting for thread(2)[0x51dd98,0x51dd30,], try=1
  INFO root [2018-07-02 19:11:16,471] - 
  INFO root [2018-07-02 19:11:16,472] - -----------------------------------------------------------------------------------------


  INFO root [2018-07-02 19:11:16,473] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-07-02 19:11:16,474] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-07-02 19:11:16,474] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-07-02 19:11:16,483] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-07-02 19:11:16,484] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-07-02 19:11:16,487] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:2518 )
  INFO root [2018-07-02 19:11:16,487] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:2518, SOMAXCONN=128.
  INFO root [2018-07-02 19:11:16,487] - server-configs:
  INFO root [2018-07-02 19:11:16,488] - 	internalAddr : 192.168.31.56:2518
  INFO root [2018-07-02 19:11:16,488] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-07-02 19:11:16,488] - 	componentID : 9000
  INFO root [2018-07-02 19:11:18,482] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 29092. PID: 608 ----
  INFO root [2018-07-02 19:11:18,484] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-07-02 19:11:18,484] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-07-02 19:11:18,485] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-07-02 19:11:18,877] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-02 19:11:18,878] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-07-02 19:11:18,879] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-02 19:11:18,886] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-02 19:11:18,887] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-07-02 19:11:18,887] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-02 19:11:18,888] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-02 19:11:19,081] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-02 19:11:19,296] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-07-02 19:11:19,296] - Script::install(): KBExtra is successfully!
S_INFO root [2018-07-02 19:11:19,335] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-07-02 19:11:19,336] - TelnetServer server is running on port 31000
  INFO root [2018-07-02 19:11:20,655] - ---- loginapp is running ----
 DEBUG root [2018-07-02 19:11:20,656] - Components::process(): Request for the process of identity...
  INFO root [2018-07-02 19:11:27,776] - Components::findComponents: find logger(1)...
  INFO root [2018-07-02 19:11:27,798] - Components::findComponents: found logger, addr:192.168.31.56:2525
  INFO root [2018-07-02 19:11:27,799] - Components::addComponent: reset orderLog, uid=29092!
  INFO root [2018-07-02 19:11:27,799] - Components::addComponent[logger], uid=29092, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-07-02 19:11:27,801] - Components::findComponents: find dbmgr(2)...
  WARN root [2018-07-02 19:11:28,903] - Forwarding logs to logger[192.168.31.56:2525/0/0/0]...
 ERROR root [2018-07-02 19:11:31,737] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-07-02 19:11:31,742] - The following logs sent to logger failed:
  WARN root [2018-07-02 19:11:31,742] - ==> [2018-07-02 19:11:31 736] TCPPacketReceiver::processPendingEvents(192.168.31.56:2525): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-07-02 19:11:31,743] - ==> [2018-07-02 19:11:31 739] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-07-02 19:11:31,936] - Components::findComponents: find dbmgr(4)...
  INFO root [2018-07-02 19:11:53,342] - 
  INFO root [2018-07-02 19:11:53,343] - -----------------------------------------------------------------------------------------


  INFO root [2018-07-02 19:11:53,344] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-07-02 19:11:53,344] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-07-02 19:11:53,345] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-07-02 19:11:53,355] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-07-02 19:11:53,356] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-07-02 19:11:53,360] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:2556 )
  INFO root [2018-07-02 19:11:53,360] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:2556, SOMAXCONN=128.
  INFO root [2018-07-02 19:11:53,360] - server-configs:
  INFO root [2018-07-02 19:11:53,361] - 	internalAddr : 192.168.31.56:2556
  INFO root [2018-07-02 19:11:53,361] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-07-02 19:11:53,361] - 	componentID : 9000
  INFO root [2018-07-02 19:11:55,375] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 29213. PID: 9076 ----
  INFO root [2018-07-02 19:11:55,376] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-07-02 19:11:55,376] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-07-02 19:11:55,377] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-07-02 19:11:55,628] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-02 19:11:55,632] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-07-02 19:11:55,633] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-02 19:11:55,640] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-02 19:11:55,641] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-07-02 19:11:55,642] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-02 19:11:55,643] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-02 19:11:55,840] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-02 19:11:55,930] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-07-02 19:11:55,931] - Script::install(): KBExtra is successfully!
S_INFO root [2018-07-02 19:11:55,937] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-07-02 19:11:55,938] - TelnetServer server is running on port 31000
  INFO root [2018-07-02 19:11:57,263] - ---- loginapp is running ----
 DEBUG root [2018-07-02 19:11:57,264] - Components::process(): Request for the process of identity...
  INFO root [2018-07-02 19:12:04,398] - Components::findComponents: find logger(1)...
  INFO root [2018-07-02 19:12:04,470] - Components::findComponents: found logger, addr:192.168.31.56:2562
  INFO root [2018-07-02 19:12:04,470] - Components::addComponent: reset orderLog, uid=29213!
  INFO root [2018-07-02 19:12:04,471] - Components::addComponent[logger], uid=29213, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-07-02 19:12:04,472] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-07-02 19:12:04,575] - Components::findComponents: found dbmgr, addr:192.168.31.56:2554
  INFO root [2018-07-02 19:12:04,576] - Components::addComponent: reset orderLog, uid=29213!
  INFO root [2018-07-02 19:12:04,576] - Components::addComponent[dbmgr], uid=29213, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-07-02 19:12:04,576] - Components::findComponents: found dbmgr, addr:192.168.31.56:2554
  WARN root [2018-07-02 19:12:05,576] - Forwarding logs to logger[192.168.31.56:2562/0/0/0]...
 ERROR root [2018-07-02 19:15:51,908] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-07-02 19:15:51,911] - The following logs sent to logger failed:
  WARN root [2018-07-02 19:15:51,911] - ==> [2018-07-02 19:15:51 907] TCPPacketReceiver::processPendingEvents(192.168.31.56:2562): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-07-02 19:15:51,912] - ==> [2018-07-02 19:15:51 909] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-07-02 19:15:52,021] - TCPPacketReceiver::processPendingEvents(192.168.31.56:2554): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-07-02 19:15:52,028] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-07-02 19:15:52,029] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-07-02 19:15:52,030] - onLoginAppShutDown()
  INFO root [2018-07-02 19:15:52,030] - Shutdowner::onShutdown: shutting down
  INFO root [2018-07-02 19:15:52,031] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-07-02 19:15:52,032] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-02 19:15:52,032] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-07-02 19:15:52,033] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-02 19:15:52,033] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-02 19:15:52,033] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-07-02 19:15:52,034] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-02 19:15:52,034] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-02 19:15:52,034] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-02 19:15:52,054] - Script::uninstall(): is successfully!
 DEBUG root [2018-07-02 19:15:52,054] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-07-02 19:15:52,354] - ThreadPool::destroy(): waiting for thread(2)[0x1e02f0,0x1e0288,], try=1
  INFO root [2018-07-02 19:15:57,097] - 
  INFO root [2018-07-02 19:15:57,098] - -----------------------------------------------------------------------------------------


  INFO root [2018-07-02 19:15:57,100] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-07-02 19:15:57,100] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-07-02 19:15:57,101] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-07-02 19:15:57,115] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-07-02 19:15:57,116] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-07-02 19:15:57,120] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:2702 )
  INFO root [2018-07-02 19:15:57,121] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:2702, SOMAXCONN=128.
  INFO root [2018-07-02 19:15:57,121] - server-configs:
  INFO root [2018-07-02 19:15:57,121] - 	internalAddr : 192.168.31.56:2702
  INFO root [2018-07-02 19:15:57,121] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-07-02 19:15:57,122] - 	componentID : 9000
  INFO root [2018-07-02 19:15:59,138] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 30009. PID: 5992 ----
  INFO root [2018-07-02 19:15:59,139] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-07-02 19:15:59,140] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-07-02 19:15:59,140] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-07-02 19:15:59,309] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-02 19:15:59,310] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-07-02 19:15:59,312] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-02 19:15:59,324] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-02 19:15:59,325] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-07-02 19:15:59,325] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-02 19:15:59,327] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-02 19:15:59,416] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-02 19:15:59,499] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-07-02 19:15:59,499] - Script::install(): KBExtra is successfully!
S_INFO root [2018-07-02 19:15:59,504] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-07-02 19:15:59,506] - TelnetServer server is running on port 31000
  INFO root [2018-07-02 19:16:00,691] - ---- loginapp is running ----
 DEBUG root [2018-07-02 19:16:00,692] - Components::process(): Request for the process of identity...
  INFO root [2018-07-02 19:16:07,825] - Components::findComponents: find logger(1)...
  INFO root [2018-07-02 19:16:07,833] - Components::findComponents: found logger, addr:192.168.31.56:2704
  INFO root [2018-07-02 19:16:07,834] - Components::addComponent: reset orderLog, uid=30009!
  INFO root [2018-07-02 19:16:07,834] - Components::addComponent[logger], uid=30009, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-07-02 19:16:07,836] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-07-02 19:16:07,936] - Components::findComponents: found dbmgr, addr:192.168.31.56:2708
  INFO root [2018-07-02 19:16:07,937] - Components::addComponent: reset orderLog, uid=30009!
  INFO root [2018-07-02 19:16:07,937] - Components::addComponent[dbmgr], uid=30009, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-07-02 19:16:07,937] - Components::findComponents: found dbmgr, addr:192.168.31.56:2708
  WARN root [2018-07-02 19:16:08,938] - Forwarding logs to logger[192.168.31.56:2704/0/0/0]...
 ERROR root [2018-07-02 19:20:02,132] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-07-02 19:20:02,140] - The following logs sent to logger failed:
  WARN root [2018-07-02 19:20:02,141] - ==> [2018-07-02 19:20:02 131] TCPPacketReceiver::processPendingEvents(192.168.31.56:2704): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-07-02 19:20:02,141] - ==> [2018-07-02 19:20:02 133] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-07-02 19:20:02,237] - TCPPacketReceiver::processPendingEvents(192.168.31.56:2708): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-07-02 19:20:02,241] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-07-02 19:20:02,258] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-07-02 19:20:02,259] - onLoginAppShutDown()
  INFO root [2018-07-02 19:20:02,261] - Shutdowner::onShutdown: shutting down
  INFO root [2018-07-02 19:20:02,261] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-07-02 19:20:02,262] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-02 19:20:02,262] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-07-02 19:20:02,262] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-02 19:20:02,263] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-02 19:20:02,263] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-07-02 19:20:02,263] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-02 19:20:02,264] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-02 19:20:02,264] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-02 19:20:02,283] - Script::uninstall(): is successfully!
 DEBUG root [2018-07-02 19:20:02,283] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-07-02 19:20:02,583] - ThreadPool::destroy(): waiting for thread(2)[0x7902f0,0x790288,], try=1
  INFO root [2018-07-02 19:21:09,139] - 
  INFO root [2018-07-02 19:21:09,141] - -----------------------------------------------------------------------------------------


  INFO root [2018-07-02 19:21:09,145] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-07-02 19:21:09,146] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-07-02 19:21:09,146] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-07-02 19:21:09,188] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-07-02 19:21:09,188] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-07-02 19:21:09,195] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:2846 )
  INFO root [2018-07-02 19:21:09,196] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:2846, SOMAXCONN=128.
  INFO root [2018-07-02 19:21:09,196] - server-configs:
  INFO root [2018-07-02 19:21:09,196] - 	internalAddr : 192.168.31.56:2846
  INFO root [2018-07-02 19:21:09,196] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-07-02 19:21:09,197] - 	componentID : 9000
  INFO root [2018-07-02 19:21:10,033] - Components::findLogger: found logger, addr:192.168.31.56:2843
  INFO root [2018-07-02 19:21:10,034] - Components::addComponent: reset orderLog, uid=31028!
  INFO root [2018-07-02 19:21:10,034] - Components::addComponent[logger], uid=31028, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-07-02 19:21:10,044] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 31028. PID: 4716 ----
  INFO root [2018-07-02 19:21:10,045] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-07-02 19:21:10,046] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-07-02 19:21:10,047] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-07-02 19:21:10,204] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-02 19:21:10,205] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-07-02 19:21:10,206] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-02 19:21:10,213] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-02 19:21:10,214] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-07-02 19:21:10,214] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-02 19:21:10,216] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-02 19:21:10,282] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-02 19:21:10,356] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-07-02 19:21:10,357] - Script::install(): KBExtra is successfully!
S_INFO root [2018-07-02 19:21:10,360] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-07-02 19:21:10,361] - TelnetServer server is running on port 31000
  INFO root [2018-07-02 19:21:11,503] - ---- loginapp is running ----
 DEBUG root [2018-07-02 19:21:11,506] - Components::process(): Request for the process of identity...
  WARN root [2018-07-02 19:21:11,848] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20235, errorno=10048
  WARN root [2018-07-02 19:21:18,044] - Forwarding logs to logger[192.168.31.56:2843/0/0/0]...
 ERROR root [2018-07-02 20:16:29,604] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-07-02 20:16:29,630] - The following logs sent to logger failed:
  WARN root [2018-07-02 20:16:29,630] - ==> [2018-07-02 20:16:29 600] TCPPacketReceiver::processPendingEvents(192.168.31.56:2843): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-07-02 20:16:29,631] - ==> [2018-07-02 20:16:29 605] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-07-02 20:16:29,730] - TCPPacketReceiver::processPendingEvents(192.168.31.56:2842): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-07-02 20:16:29,734] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-07-02 20:16:29,743] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-07-02 20:16:29,755] - onLoginAppShutDown()
  INFO root [2018-07-02 20:16:29,755] - Shutdowner::onShutdown: shutting down
  INFO root [2018-07-02 20:16:29,755] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-07-02 20:16:29,756] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-02 20:16:29,756] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-07-02 20:16:29,757] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-02 20:16:29,757] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-02 20:16:29,757] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-07-02 20:16:29,757] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-02 20:16:29,758] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-02 20:16:29,758] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-02 20:16:29,776] - Script::uninstall(): is successfully!
 DEBUG root [2018-07-02 20:16:29,776] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-07-02 20:16:30,076] - ThreadPool::destroy(): waiting for thread(2)[0x17002f0,0x1700288,], try=1
  INFO root [2018-07-02 21:20:34,075] - 
  INFO root [2018-07-02 21:20:34,077] - -----------------------------------------------------------------------------------------


  INFO root [2018-07-02 21:20:34,079] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-07-02 21:20:34,079] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-07-02 21:20:34,080] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-07-02 21:20:34,103] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-07-02 21:20:34,104] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-07-02 21:20:34,120] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:3853 )
  INFO root [2018-07-02 21:20:34,120] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:3853, SOMAXCONN=128.
  INFO root [2018-07-02 21:20:34,121] - server-configs:
  INFO root [2018-07-02 21:20:34,121] - 	internalAddr : 192.168.31.56:3853
  INFO root [2018-07-02 21:20:34,121] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-07-02 21:20:34,121] - 	componentID : 9000
  INFO root [2018-07-02 21:20:35,016] - Components::findLogger: found logger, addr:192.168.31.56:3851
  INFO root [2018-07-02 21:20:35,017] - Components::addComponent: reset orderLog, uid=21655!
  INFO root [2018-07-02 21:20:35,017] - Components::addComponent[logger], uid=21655, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-07-02 21:20:35,025] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 21655. PID: 9808 ----
  INFO root [2018-07-02 21:20:35,025] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-07-02 21:20:35,026] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-07-02 21:20:35,027] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-07-02 21:20:35,186] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-02 21:20:35,187] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-07-02 21:20:35,188] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-02 21:20:35,195] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-02 21:20:35,195] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-07-02 21:20:35,195] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-02 21:20:35,196] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-02 21:20:35,283] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-02 21:20:35,370] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-07-02 21:20:35,370] - Script::install(): KBExtra is successfully!
S_INFO root [2018-07-02 21:20:35,375] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-07-02 21:20:35,378] - TelnetServer server is running on port 31000
  INFO root [2018-07-02 21:20:36,951] - ---- loginapp is running ----
 DEBUG root [2018-07-02 21:20:36,953] - Components::process(): Request for the process of identity...
  INFO root [2018-07-02 21:20:42,284] - 
  INFO root [2018-07-02 21:20:42,284] - -----------------------------------------------------------------------------------------


  INFO root [2018-07-02 21:20:42,285] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-07-02 21:20:42,286] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-07-02 21:20:42,286] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-07-02 21:20:42,295] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-07-02 21:20:42,295] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-07-02 21:20:42,298] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:3861 )
  INFO root [2018-07-02 21:20:42,299] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:3861, SOMAXCONN=128.
  INFO root [2018-07-02 21:20:42,299] - server-configs:
  INFO root [2018-07-02 21:20:42,299] - 	internalAddr : 192.168.31.56:3861
  INFO root [2018-07-02 21:20:42,299] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-07-02 21:20:42,299] - 	componentID : 9000
  INFO root [2018-07-02 21:20:44,361] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 21684. PID: 9776 ----
  INFO root [2018-07-02 21:20:44,363] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-07-02 21:20:44,364] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-07-02 21:20:44,364] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-07-02 21:20:44,659] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-02 21:20:44,661] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-07-02 21:20:44,662] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-02 21:20:44,671] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-02 21:20:44,672] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-07-02 21:20:44,672] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-02 21:20:44,674] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-02 21:20:44,796] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-02 21:20:44,892] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-07-02 21:20:44,893] - Script::install(): KBExtra is successfully!
S_INFO root [2018-07-02 21:20:44,898] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-07-02 21:20:44,900] - TelnetServer server is running on port 31000
  INFO root [2018-07-02 21:20:46,378] - ---- loginapp is running ----
 DEBUG root [2018-07-02 21:20:46,380] - Components::process(): Request for the process of identity...
  INFO root [2018-07-02 21:20:53,539] - Components::findComponents: find logger(1)...
  INFO root [2018-07-02 21:20:53,634] - Components::findComponents: found logger, addr:192.168.31.56:3868
  INFO root [2018-07-02 21:20:53,635] - Components::addComponent: reset orderLog, uid=21684!
  INFO root [2018-07-02 21:20:53,636] - Components::addComponent[logger], uid=21684, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-07-02 21:20:53,638] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-07-02 21:20:53,739] - Components::findComponents: found dbmgr, addr:192.168.31.56:3866
  INFO root [2018-07-02 21:20:53,740] - Components::addComponent: reset orderLog, uid=21684!
  INFO root [2018-07-02 21:20:53,740] - Components::addComponent[dbmgr], uid=21684, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-07-02 21:20:53,740] - Components::findComponents: found dbmgr, addr:192.168.31.56:3866
  WARN root [2018-07-02 21:20:54,740] - Forwarding logs to logger[192.168.31.56:3868/0/0/0]...
 ERROR root [2018-07-02 21:27:18,588] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-07-02 21:27:18,614] - The following logs sent to logger failed:
  WARN root [2018-07-02 21:27:18,615] - ==> [2018-07-02 21:27:18 587] TCPPacketReceiver::processPendingEvents(192.168.31.56:3868): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-07-02 21:27:18,615] - ==> [2018-07-02 21:27:18 589] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-07-02 21:27:18,715] - TCPPacketReceiver::processPendingEvents(192.168.31.56:3866): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-07-02 21:27:18,720] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-07-02 21:27:18,731] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-07-02 21:27:18,737] - onLoginAppShutDown()
  INFO root [2018-07-02 21:27:18,738] - Shutdowner::onShutdown: shutting down
  INFO root [2018-07-02 21:27:18,738] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-07-02 21:27:18,738] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-02 21:27:18,739] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-07-02 21:27:18,739] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-02 21:27:18,739] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-02 21:27:18,740] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-07-02 21:27:18,740] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-02 21:27:18,740] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-02 21:27:18,740] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-02 21:27:18,759] - Script::uninstall(): is successfully!
 DEBUG root [2018-07-02 21:27:18,760] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-07-02 21:27:19,060] - ThreadPool::destroy(): waiting for thread(2)[0x58de08,0x58dda0,], try=1
  INFO root [2018-07-02 21:27:26,301] - 
  INFO root [2018-07-02 21:27:26,302] - -----------------------------------------------------------------------------------------


  INFO root [2018-07-02 21:27:26,303] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-07-02 21:27:26,303] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-07-02 21:27:26,303] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-07-02 21:27:26,313] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-07-02 21:27:26,314] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-07-02 21:27:26,317] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:4036 )
  INFO root [2018-07-02 21:27:26,317] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:4036, SOMAXCONN=128.
  INFO root [2018-07-02 21:27:26,318] - server-configs:
  INFO root [2018-07-02 21:27:26,318] - 	internalAddr : 192.168.31.56:4036
  INFO root [2018-07-02 21:27:26,318] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-07-02 21:27:26,318] - 	componentID : 9000
  INFO root [2018-07-02 21:27:28,374] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 23004. PID: 4972 ----
  INFO root [2018-07-02 21:27:28,375] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-07-02 21:27:28,377] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-07-02 21:27:28,378] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-07-02 21:27:28,621] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-02 21:27:28,622] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-07-02 21:27:28,623] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-02 21:27:28,630] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-02 21:27:28,631] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-07-02 21:27:28,631] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-02 21:27:28,633] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-02 21:27:28,732] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-02 21:27:28,832] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-07-02 21:27:28,832] - Script::install(): KBExtra is successfully!
S_INFO root [2018-07-02 21:27:28,839] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-07-02 21:27:28,840] - TelnetServer server is running on port 31000
  INFO root [2018-07-02 21:27:30,391] - ---- loginapp is running ----
 DEBUG root [2018-07-02 21:27:30,393] - Components::process(): Request for the process of identity...
  INFO root [2018-07-02 21:27:37,599] - Components::findComponents: find logger(1)...
  INFO root [2018-07-02 21:27:37,705] - Components::findComponents: found logger, addr:192.168.31.56:4043
  INFO root [2018-07-02 21:27:37,706] - Components::addComponent: reset orderLog, uid=23004!
  INFO root [2018-07-02 21:27:37,706] - Components::addComponent[logger], uid=23004, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-07-02 21:27:37,708] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-07-02 21:27:37,812] - Components::findComponents: found dbmgr, addr:192.168.31.56:4041
  INFO root [2018-07-02 21:27:37,813] - Components::addComponent: reset orderLog, uid=23004!
  INFO root [2018-07-02 21:27:37,813] - Components::addComponent[dbmgr], uid=23004, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-07-02 21:27:37,813] - Components::findComponents: found dbmgr, addr:192.168.31.56:4041
  WARN root [2018-07-02 21:27:38,813] - Forwarding logs to logger[192.168.31.56:4043/0/0/0]...
 ERROR root [2018-07-02 22:40:17,459] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-07-02 22:40:17,475] - The following logs sent to logger failed:
  WARN root [2018-07-02 22:40:17,476] - ==> [2018-07-02 22:40:17 459] TCPPacketReceiver::processPendingEvents(192.168.31.56:4043): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-07-02 22:40:17,476] - ==> [2018-07-02 22:40:17 460] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-07-02 22:40:17,587] - TCPPacketReceiver::processPendingEvents(192.168.31.56:4041): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-07-02 22:40:17,592] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-07-02 22:40:17,629] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-07-02 22:40:17,631] - onLoginAppShutDown()
  INFO root [2018-07-02 22:40:17,632] - Shutdowner::onShutdown: shutting down
  INFO root [2018-07-02 22:40:17,632] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-07-02 22:40:17,633] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-02 22:40:17,633] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-07-02 22:40:17,633] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-02 22:40:17,634] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-02 22:40:17,634] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-07-02 22:40:17,635] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-02 22:40:17,635] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-02 22:40:17,635] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-02 22:40:17,658] - Script::uninstall(): is successfully!
 DEBUG root [2018-07-02 22:40:17,658] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-07-02 22:40:17,960] - ThreadPool::destroy(): waiting for thread(2)[0x48de08,0x48dda0,], try=1
  INFO root [2018-07-02 22:48:37,357] - 
  INFO root [2018-07-02 22:48:37,358] - -----------------------------------------------------------------------------------------


  INFO root [2018-07-02 22:48:37,359] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-07-02 22:48:37,359] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-07-02 22:48:37,360] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-07-02 22:48:37,380] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-07-02 22:48:37,380] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-07-02 22:48:37,384] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:4460 )
  INFO root [2018-07-02 22:48:37,385] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:4460, SOMAXCONN=128.
  INFO root [2018-07-02 22:48:37,385] - server-configs:
  INFO root [2018-07-02 22:48:37,385] - 	internalAddr : 192.168.31.56:4460
  INFO root [2018-07-02 22:48:37,385] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-07-02 22:48:37,385] - 	componentID : 9000
  INFO root [2018-07-02 22:48:39,523] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 6142. PID: 10344 ----
  INFO root [2018-07-02 22:48:39,524] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-07-02 22:48:39,527] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-07-02 22:48:39,528] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-07-02 22:48:39,703] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-02 22:48:39,705] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-07-02 22:48:39,706] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-02 22:48:39,713] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-02 22:48:39,714] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-07-02 22:48:39,715] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-02 22:48:39,716] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-02 22:48:39,805] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-02 22:48:39,902] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-07-02 22:48:39,903] - Script::install(): KBExtra is successfully!
S_INFO root [2018-07-02 22:48:39,909] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-07-02 22:48:39,910] - TelnetServer server is running on port 31000
  INFO root [2018-07-02 22:48:41,147] - ---- loginapp is running ----
 DEBUG root [2018-07-02 22:48:41,148] - Components::process(): Request for the process of identity...
  INFO root [2018-07-02 22:48:48,290] - Components::findComponents: find logger(1)...
  INFO root [2018-07-02 22:48:48,389] - Components::findComponents: found logger, addr:192.168.31.56:4465
  INFO root [2018-07-02 22:48:48,390] - Components::addComponent: reset orderLog, uid=6142!
  INFO root [2018-07-02 22:48:48,390] - Components::addComponent[logger], uid=6142, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-07-02 22:48:48,392] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-07-02 22:48:48,494] - Components::findComponents: found dbmgr, addr:192.168.31.56:4467
  INFO root [2018-07-02 22:48:48,494] - Components::addComponent: reset orderLog, uid=6142!
  INFO root [2018-07-02 22:48:48,495] - Components::addComponent[dbmgr], uid=6142, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-07-02 22:48:48,495] - Components::findComponents: found dbmgr, addr:192.168.31.56:4467
  WARN root [2018-07-02 22:48:49,495] - Forwarding logs to logger[192.168.31.56:4465/0/0/0]...
  INFO root [2018-07-02 23:08:04,992] - 
  INFO root [2018-07-02 23:08:04,993] - -----------------------------------------------------------------------------------------


  INFO root [2018-07-02 23:08:04,994] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-07-02 23:08:04,995] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-07-02 23:08:04,995] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-07-02 23:08:05,006] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-07-02 23:08:05,007] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-07-02 23:08:05,010] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:5162 )
  INFO root [2018-07-02 23:08:05,010] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:5162, SOMAXCONN=128.
  INFO root [2018-07-02 23:08:05,010] - server-configs:
  INFO root [2018-07-02 23:08:05,010] - 	internalAddr : 192.168.31.56:5162
  INFO root [2018-07-02 23:08:05,010] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-07-02 23:08:05,010] - 	componentID : 9000
  INFO root [2018-07-02 23:08:07,143] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 9956. PID: 9140 ----
  INFO root [2018-07-02 23:08:07,145] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-07-02 23:08:07,146] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-07-02 23:08:07,146] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-07-02 23:08:07,322] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-02 23:08:07,323] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-07-02 23:08:07,324] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-02 23:08:07,332] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-02 23:08:07,333] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-07-02 23:08:07,333] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-02 23:08:07,335] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-02 23:08:07,424] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-02 23:08:07,517] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-07-02 23:08:07,517] - Script::install(): KBExtra is successfully!
S_INFO root [2018-07-02 23:08:07,523] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-07-02 23:08:07,524] - TelnetServer server is running on port 31001
  INFO root [2018-07-02 23:08:08,766] - ---- loginapp is running ----
 DEBUG root [2018-07-02 23:08:08,768] - Components::process(): Request for the process of identity...
 ERROR root [2018-07-02 23:08:08,944] - Components::process: found loginapp, addr:192.168.31.56:4460
 ERROR root [2018-07-02 23:08:08,946] - ServerApp::onIdentityillegal: The current process and loginapp(componentID=9000 ->conflicted???, pid=10344, addr=192.168.31.56) conflict, the process will exit!
Can modify the components-CID and UID to avoid conflict.
  INFO root [2018-07-02 23:08:08,948] - Shutdowner::onShutdownBegin: shutting down(period=1, tickPeriod=1)
S_INFO root [2018-07-02 23:08:08,949] - onLoginAppShutDown()
  INFO root [2018-07-02 23:08:09,960] - Shutdowner::onShutdown: shutting down
  INFO root [2018-07-02 23:08:10,962] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-07-02 23:08:10,963] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-02 23:08:10,963] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-07-02 23:08:10,963] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-02 23:08:10,963] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-02 23:08:10,963] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-07-02 23:08:10,963] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-02 23:08:10,963] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-02 23:08:10,964] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-02 23:08:10,974] - Script::uninstall(): is successfully!
 DEBUG root [2018-07-02 23:08:10,974] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-07-02 23:08:11,275] - ThreadPool::destroy(): waiting for thread(2)[0x15dde08,0x15ddda0,], try=1
 DEBUG root [2018-07-02 23:08:11,677] - TPThread::~TPThread(): 0x15dde08
 DEBUG root [2018-07-02 23:08:11,677] - TPThread::~TPThread(): 0x15ddda0
 DEBUG root [2018-07-02 23:08:11,677] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-07-02 23:08:11,706] - Bundle::destroyObjPool(): size 14.
 DEBUG root [2018-07-02 23:08:11,706] - Channel::destroyObjPool(): size 0.
 DEBUG root [2018-07-02 23:08:11,716] - TCPPacket::destroyObjPool(): size 0.
 DEBUG root [2018-07-02 23:08:11,716] - UDPPacket::destroyObjPool(): size 12.
 DEBUG root [2018-07-02 23:08:11,716] - EndPoint::destroyObjPool(): size 0.
 DEBUG root [2018-07-02 23:08:11,716] - Address::destroyObjPool(): size 0.
 DEBUG root [2018-07-02 23:08:11,717] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2018-07-02 23:08:11,717] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2018-07-02 23:08:11,717] - loginapp(9000) has shut down.
  INFO root [2018-07-02 23:08:12,739] - EventDispatcher()::~EventDispatcher: Num timers = 2
  INFO root [2018-07-02 23:10:24,698] - 
  INFO root [2018-07-02 23:10:24,699] - -----------------------------------------------------------------------------------------


  INFO root [2018-07-02 23:10:24,701] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-07-02 23:10:24,702] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-07-02 23:10:24,703] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-07-02 23:10:24,724] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-07-02 23:10:24,725] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-07-02 23:10:24,731] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:5193 )
  INFO root [2018-07-02 23:10:24,732] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:5193, SOMAXCONN=128.
  INFO root [2018-07-02 23:10:24,732] - server-configs:
  INFO root [2018-07-02 23:10:24,732] - 	internalAddr : 192.168.31.56:5193
  INFO root [2018-07-02 23:10:24,732] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-07-02 23:10:24,733] - 	componentID : 9000
  INFO root [2018-07-02 23:10:26,954] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 10410. PID: 9984 ----
  INFO root [2018-07-02 23:10:26,956] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-07-02 23:10:26,957] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-07-02 23:10:26,958] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-07-02 23:10:27,197] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-02 23:10:27,199] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-07-02 23:10:27,200] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-02 23:10:27,207] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-02 23:10:27,208] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-07-02 23:10:27,209] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-02 23:10:27,213] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-02 23:10:27,423] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-02 23:10:27,590] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-07-02 23:10:27,590] - Script::install(): KBExtra is successfully!
S_INFO root [2018-07-02 23:10:27,595] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-07-02 23:10:27,597] - TelnetServer server is running on port 31001
  INFO root [2018-07-02 23:10:29,042] - ---- loginapp is running ----
 DEBUG root [2018-07-02 23:10:29,043] - Components::process(): Request for the process of identity...
 ERROR root [2018-07-02 23:10:29,207] - Components::process: found loginapp, addr:192.168.31.56:4460
 ERROR root [2018-07-02 23:10:29,209] - ServerApp::onIdentityillegal: The current process and loginapp(componentID=9000 ->conflicted???, pid=10344, addr=192.168.31.56) conflict, the process will exit!
Can modify the components-CID and UID to avoid conflict.
  INFO root [2018-07-02 23:10:29,211] - Shutdowner::onShutdownBegin: shutting down(period=1, tickPeriod=1)
S_INFO root [2018-07-02 23:10:29,213] - onLoginAppShutDown()
  INFO root [2018-07-02 23:10:30,213] - Shutdowner::onShutdown: shutting down
  INFO root [2018-07-02 23:10:31,214] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-07-02 23:10:31,214] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-02 23:10:31,214] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-07-02 23:10:31,215] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-02 23:10:31,215] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-02 23:10:31,215] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-07-02 23:10:31,215] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-02 23:10:31,215] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-02 23:10:31,215] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-02 23:10:31,226] - Script::uninstall(): is successfully!
 DEBUG root [2018-07-02 23:10:31,227] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-07-02 23:10:31,527] - ThreadPool::destroy(): waiting for thread(2)[0x16fde10,0x16fdda8,], try=1
 DEBUG root [2018-07-02 23:10:31,927] - TPThread::~TPThread(): 0x16fde10
 DEBUG root [2018-07-02 23:10:31,927] - TPThread::~TPThread(): 0x16fdda8
 DEBUG root [2018-07-02 23:10:31,927] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-07-02 23:10:31,939] - Bundle::destroyObjPool(): size 14.
 DEBUG root [2018-07-02 23:10:31,939] - Channel::destroyObjPool(): size 0.
 DEBUG root [2018-07-02 23:10:31,940] - TCPPacket::destroyObjPool(): size 0.
 DEBUG root [2018-07-02 23:10:31,940] - UDPPacket::destroyObjPool(): size 12.
 DEBUG root [2018-07-02 23:10:31,940] - EndPoint::destroyObjPool(): size 0.
 DEBUG root [2018-07-02 23:10:31,940] - Address::destroyObjPool(): size 0.
 DEBUG root [2018-07-02 23:10:31,940] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2018-07-02 23:10:31,940] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2018-07-02 23:10:31,941] - loginapp(9000) has shut down.
  INFO root [2018-07-02 23:10:32,941] - EventDispatcher()::~EventDispatcher: Num timers = 2
 ERROR root [2018-07-02 23:12:39,779] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=6
  INFO root [2018-07-02 23:12:39,780] - The following logs sent to logger failed:
  WARN root [2018-07-02 23:12:39,781] - ==> [2018-07-02 23:12:39 778] TCPPacketReceiver::processPendingEvents(192.168.31.56:4465): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-07-02 23:12:39,781] - ==> [2018-07-02 23:12:39 780] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=6
  WARN root [2018-07-02 23:12:43,533] - TCPPacketReceiver::processPendingEvents(192.168.31.56:4463): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-07-02 23:12:43,534] - Components::removeComponentByChannel: baseappmgr : 5000, Abnormal exit! errorno=6
  WARN root [2018-07-02 23:13:13,746] - TCPPacketReceiver::processPendingEvents(192.168.31.56:4467): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-07-02 23:13:13,747] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=6
  INFO root [2018-07-02 23:13:13,747] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-07-02 23:13:13,747] - onLoginAppShutDown()
  INFO root [2018-07-02 23:13:13,748] - Shutdowner::onShutdown: shutting down
  INFO root [2018-07-02 23:13:13,748] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-07-02 23:13:13,748] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-02 23:13:13,748] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-07-02 23:13:13,748] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-02 23:13:13,749] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-02 23:13:13,749] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-07-02 23:13:13,749] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-02 23:13:13,749] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-02 23:13:13,749] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-02 23:13:13,766] - Script::uninstall(): is successfully!
 DEBUG root [2018-07-02 23:13:13,767] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-07-02 23:13:14,067] - ThreadPool::destroy(): waiting for thread(2)[0x1a7e1e0,0x1a7e178,], try=1
 DEBUG root [2018-07-02 23:13:14,467] - TPThread::~TPThread(): 0x1a7e1e0
 DEBUG root [2018-07-02 23:13:14,467] - TPThread::~TPThread(): 0x1a7e178
 DEBUG root [2018-07-02 23:13:14,467] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-07-02 23:13:14,479] - Bundle::destroyObjPool(): size 10.
 DEBUG root [2018-07-02 23:13:14,479] - Channel::destroyObjPool(): size 16.
 DEBUG root [2018-07-02 23:13:14,480] - TCPPacket::destroyObjPool(): size 1.
 DEBUG root [2018-07-02 23:13:14,480] - UDPPacket::destroyObjPool(): size 0.
 DEBUG root [2018-07-02 23:13:14,480] - EndPoint::destroyObjPool(): size 15.
 DEBUG root [2018-07-02 23:13:14,480] - Address::destroyObjPool(): size 0.
 DEBUG root [2018-07-02 23:13:14,480] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2018-07-02 23:13:14,480] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2018-07-02 23:13:14,480] - loginapp(9000) has shut down.
  INFO root [2018-07-02 23:13:15,499] - EventDispatcher()::~EventDispatcher: Num timers = 2
  INFO root [2018-07-02 23:13:40,054] - 
  INFO root [2018-07-02 23:13:40,056] - -----------------------------------------------------------------------------------------


  INFO root [2018-07-02 23:13:40,058] - Resmgr::initialize: KBE_ROOT=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/
  INFO root [2018-07-02 23:13:40,059] - Resmgr::initialize: KBE_RES_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/res/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/scripts/;C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/assets/res/
  INFO root [2018-07-02 23:13:40,059] - Resmgr::initialize: KBE_BIN_PATH=C:/Users/Public/Documents/workspace/kbe/kbengine-kbengine-v1.0.0/kbengine/kbe/bin/server/
  INFO root [2018-07-02 23:13:40,098] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:20013 )
  INFO root [2018-07-02 23:13:40,099] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.31.56:20013, SOMAXCONN=128.
  INFO root [2018-07-02 23:13:40,121] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.31.56 ( 192.168.31.56:5238 )
  INFO root [2018-07-02 23:13:40,121] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.31.56:5238, SOMAXCONN=128.
  INFO root [2018-07-02 23:13:40,122] - server-configs:
  INFO root [2018-07-02 23:13:40,122] - 	internalAddr : 192.168.31.56:5238
  INFO root [2018-07-02 23:13:40,122] - 	externalAddr : 192.168.31.56:20013
  INFO root [2018-07-02 23:13:40,122] - 	componentID : 9000
  INFO root [2018-07-02 23:13:41,028] - Components::findLogger: found logger, addr:192.168.31.56:5243
  INFO root [2018-07-02 23:13:41,029] - Components::addComponent: reset orderLog, uid=11050!
  INFO root [2018-07-02 23:13:41,029] - Components::addComponent[logger], uid=11050, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-07-02 23:13:41,036] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 23:20:06 Jun 15 2018. AppID: 9000. UID: 11050. PID: 5556 ----
  INFO root [2018-07-02 23:13:41,037] - Server :        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz with 4194303kB RAM
  INFO root [2018-07-02 23:13:41,038] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-07-02 23:13:41,038] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-07-02 23:13:41,207] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-02 23:13:41,208] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-07-02 23:13:41,209] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-02 23:13:41,216] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-02 23:13:41,216] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-07-02 23:13:41,216] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-02 23:13:41,217] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-02 23:13:41,272] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-02 23:13:41,363] - Script::install(): is successfully, Python=(3.4.2 (default, Jun 15 2018, 23:20:02) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-07-02 23:13:41,364] - Script::install(): KBExtra is successfully!
S_INFO root [2018-07-02 23:13:41,369] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-07-02 23:13:41,370] - TelnetServer server is running on port 31000
  INFO root [2018-07-02 23:13:42,530] - ---- loginapp is running ----
 DEBUG root [2018-07-02 23:13:42,532] - Components::process(): Request for the process of identity...
  WARN root [2018-07-02 23:13:49,170] - Forwarding logs to logger[192.168.31.56:5243/0/0/0]...
 ERROR root [2018-07-02 23:15:43,609] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-07-02 23:15:43,629] - The following logs sent to logger failed:
  WARN root [2018-07-02 23:15:43,630] - ==> [2018-07-02 23:15:43 606] TCPPacketReceiver::processPendingEvents(192.168.31.56:5243): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-07-02 23:15:43,631] - ==> [2018-07-02 23:15:43 610] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-07-02 23:15:43,722] - TCPPacketReceiver::processPendingEvents(192.168.31.56:5236): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-07-02 23:15:43,733] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-07-02 23:15:43,747] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-07-02 23:15:43,754] - onLoginAppShutDown()
  INFO root [2018-07-02 23:15:43,754] - Shutdowner::onShutdown: shutting down
  INFO root [2018-07-02 23:15:43,755] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-07-02 23:15:43,755] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-07-02 23:15:43,756] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-07-02 23:15:43,756] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-07-02 23:15:43,756] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-07-02 23:15:43,756] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-07-02 23:15:43,757] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-07-02 23:15:43,757] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-07-02 23:15:43,757] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-07-02 23:15:43,776] - Script::uninstall(): is successfully!
 DEBUG root [2018-07-02 23:15:43,777] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-07-02 23:15:44,077] - ThreadPool::destroy(): waiting for thread(2)[0x53de10,0x53dda8,], try=1
